### ISSUE TITLE
Отчет по обновлению прайса по API в двумя файлами

### ISSUE THREAD

**Issue by Alexeyttn** [onlinerby/onliner-b2b-api#100]
https://yadi.sk/i/s7yvbd_4HAd3tg

    при загрузке по Апи мы делим файл на 2, т.к. одним куском он не проходит по размеру

    1 часть идет обновление полное (все удаляется и по новой заливается файл)

    2 часть как дополнение (добавляет товары

    Задача - получить отчет по 2 части по API как это сделать? интересуют вот эти данные https://yadi.sk/i/D0-zcDdJ8nRilw 

    наш программист формулирует так вопросы:

    "первый файл грузится как файл и пожтому апи дает ID процесса, по которому потом можно запросить этот отчет,  второй файл грузится не как файл, а методом POST (чтобы не затерерть результат первого файла) и поэтому ID нет и запросить отчет по второму файлу технически невозможно - все претензии к техподдержке онлайнера.....   "

**Comment by sidorovich** [comment]
не совсем понятны технические детали: на какие именно URL выполняются запросы?
Для импорта прайс-листов используются методы PUT и PATCH.  Оба этих запроса возвращают идентификатор выгрузки, по которому можно получить результаты обработки

Метод POST не используется для импорта прайс-листов.

https://github.com/onlinerby/onliner-b2b-api/blob/master/shop.md#%D0%B8%D0%BC%D0%BF%D0%BE%D1%80%D1%82
