### ISSUE TITLE
Выгрузить лог ошибок для Магазин №965 «21vek.by»

### ISSUE THREAD

**Issue by AlexyZviyalov** [onlinerby/onliner-b2b-api#102]
Были ошибки "Не указан производитель" Хочу найти на каких товарах Пожалуйста, выгрузите мне товары с такими ошибками

**Comment by Olden** [comment]
такие выгрузки не делаем. по каждому отдельному импорту вы можете просмотреть лог

**Comment by Olden** [comment]
Добрый день, недавно добавили возможность выгрузить отчет об импорте в csv формате. Попробуйте может вам подойдет
<img width="864" alt="Screen Shot 2019-09-03 at 14 59 18" src="https://user-images.githubusercontent.com/546682/64171522-8e85f400-ce5b-11e9-87b4-533e8591bf96.png">

**Comment by Olden** [comment]
@dzmitrylukashuk вам тоже может быть интересно
