### ISSUE TITLE
Лишняя выгрузка товаров

### ISSUE THREAD

**Issue by LacosteR** [onlinerby/onliner-b2b-api#103]
Магазин: ускорение.бел №13375
https://catalog.onliner.by/motor_oil/shell/helixhx80w304/prices?town=minsk
Магазин дает три предложения товара. У нас не привязан не один товар к этому товару, с чем это может быть связано?

**Comment by Olden** [comment]
не вижу предложений по этому товару от этого магазина

**Comment by LacosteR** [comment]
Ситуация: у нас был привязан только один товар к этому товару, но давало три предложения. После я удалил связку, но предложение оставалось висеть некоторые время, поэтому и написал, сейчас вижу, что предложение пропало. Извиняемся за беспокойство!

**Comment by Olden** [comment]
эта страница попадает к 10 минутный кеш, поэтому могут быть задержки в этом временном интервале
