### ISSUE TITLE
Статус "Нет в наличии"

### ISSUE THREAD

**Issue by LacosteR** [onlinerby/onliner-b2b-api#104]
Как указать статус "нет в наличии" при обновлении товара?

**Comment by sidorovich** [comment]
просто не заполняйте это поле (передавайте пустым), это не обязательный для заполнения параметр

**Comment by LacosteR** [comment]
Да, но сегодня получили заказ на товар которого у нас нету в наличии. При обновлении цен статус наличия не указывается. Мы передали поле пустым и товар появился в наличии каталога онлайнера:
http://joxi.ru/KAxQzzPiZQx8lr

**Comment by sidorovich** [comment]
Мне кажется вы путаете понятие "ценовое предложение" и "статус наличия на складе".
<img width="913" alt="Снимок экрана 2019-07-31 в 14 10 09" src="https://user-images.githubusercontent.com/3040359/62207524-ffd61100-b39c-11e9-8402-cb38cce886f1.png">
В первом случае ценовое предложение с указанным статусом наличия, во втором случае - с неуказанным. В обоих случаях ценовое предложение отображается на сайте. 

Если вы хотите скрыть ценовое предложение, то независимо от статуса наличия, вы либо должны вызвать метод нашего API для удаления ценовых предложений https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/delete/list.md , либо не передавать эту позицию в прайс-листе.

**Comment by LacosteR** [comment]
Спасибо!
