### ISSUE TITLE
 Ошибка при загрузке прайса

### ISSUE THREAD

**Issue by ka4an4eg** [onlinerby/onliner-b2b-api#106]
Добрый вечер. Авторизацию прохожу успешно, но при попытке отправить данные, получаю ошибку что переданные токен невалидный http://joxi.ru/zANeX8YCva7n82 . Подскажите с чем может быть связана подобная ситуация?

**Comment by sidorovich** [comment]
Подскажите номер магазина

**Comment by sidorovich** [comment]
Судя по длине токена, вы скорее всего используете ClientId и Client secret для доступа к Cart API, а не к B2B API.
Проверьте авторизационные данные в личном кабинете и выберите нужные.
