### ISSUE TITLE
ошибка добавления товаров

### ISSUE THREAD

**Issue by enjeeq** [onlinerby/onliner-b2b-api#107]
магазин 6 0 9 7, не добавляются товары через b2b:

Xiaomi Redmi Note 4X Snapdragon 625 4GB/64GB (черный)
Xiaomi Redmi Note 4X Helio X20 4GB/64GB (черный) [MBT6A5]
Xiaomi Redmi Note 4X Helio X20 4GB/64GB (темно-серый) [MBT6A5]
Xiaomi Redmi Note 4X Helio X20 4GB/64GB (розовый) [MBT6A5] 
Xiaomi Redmi Note 4X Helio X20 4GB/64GB (золотистый) [MBT6A5]
Xiaomi Redmi K20 Pro 6GB/128GB китайская версия (черный)
Xiaomi Redmi K20 Pro 6GB/128GB китайская версия (синий)
Xiaomi Mi A1 4GB/64GB (черный)
Xiaomi Mi A1 4GB/64GB международная версия (золотистый)
Xiaomi Redmi 7A 2GB/16GB международная версия (матовый синий)
Xiaomi Redmi 7A 2GB/32GB международная версия (матовый синий)
Xiaomi Redmi K20 6GB/64GB китайская версия (синий)
Xiaomi Redmi K20 6GB/128GB китайская версия (черный)
Xiaomi Redmi Note 5 3GB/32GB M1803E7SG международная версия (золотист.
Xiaomi Redmi Note 5 4GB/64GB M1803E7SG международная версия (черный)
Xiaomi Redmi Note 6 Pro 3GB/32GB международная версия (розовый)

https://prnt.sc/orn5b8

**Comment by sidorovich** [comment]
Наши специалисты обновили Вам прайс-лист и Вы можете вручную добавлять позиции.
В случае повторения данной проблемы более оперативно Вы сможете получить помощь обратившись по телефону в отдел работы с клиентами.

**Comment by enjeeq** [comment]
проблема осталась с этой позицией "Xiaomi Mi A1 4GB/64GB (черный)"

**Comment by sidorovich** [comment]
проверьте сейчас
