### ISSUE TITLE
Все запросы в b2b таймаутятся

### ISSUE THREAD

**Issue by ivan-leschinsky** [onlinerby/onliner-b2b-api#108]
Добрый день. Не проходят любые запросы в b2b с IP: 195.201.20.83. С этого же IP не работает онлайнер вообще

**Comment by Olden** [comment]
находимся под ddos атакой, внешний трафик временно заблокирован

**Comment by ivan-leschinsky** [comment]
Понял, спасибо

**Comment by Olden** [comment]
пока доступ разблокировали, но если атака продолжится, то снова закроем
