### ISSUE TITLE
Уточнение по работе с курьерскими доставками

### ISSUE THREAD

**Issue by julia-korotkina** [onlinerby/onliner-b2b-api#111]
Добрый день!

Хотела уточнить, несколько вопросов, в связи с новыми условиями установки цен на доставки. 
1) Если мы сейчас добавим поле courierDeliveryPrices, то вычисление доставок будет уже осуществляться по тарифной сетке или по данным в полях deliveryTownPrice и deliveryCountryPrice? Если первое, то можем ли мы сейчас удалить поля deliveryTownPrice и deliveryCountryPrice?

2) У нас все товары подходят под условия тарифной сетки. То есть нам надо, чтобы цены на доставку брались из нее. Как я понимаю, поле будет выглядеть:
"courierDeliveryPrices": {
            "rb": {
                "type": "default",
            },
            "minsk": {
                "type": "default"
            }
        }

3) Если же нам будет необходимо для какого-то товара/региона сделать специальную цену, то как это осуществить, если цена доставки зависит не только от региона доставки, но и от суммы заказа? Не нашла в описании api поля, отвечающего за этот параметр.
 
Номер магазина 987. Работа с api осуществляется через json.

**Comment by sidorovich** [comment]
1. Поля deliveryTownPrice и deliveryCountryPrice необходимо передавать до окончательного обновления каталога и мобильных приложений, так как старые версии мобильных приложений по прежнему используют эти данные.

2. Поле courierDeliveryPrices опционально и лучше его не передавать, если Ваша тарифная сетка покрывает все варианты для расчета. Передача этого поля замедляет импорт прайс-листов. JFYI для типа default будет использоваться общий тариф, тарифная сетка не будет использоваться для расчета.

3. Правила расчета стоимости доставки для всего заказа настраиваются в личном кабинете.

Вы можете обратиться к документации https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/import/courier_delivery.md

Напоминаю, что передача стоимости курьерской доставки для каждого ценового предложения предполагается как исключительная мера, если тарифная сетка по тем или иным причинам не справляется. Настоятельно рекомендуем, обращаться к этой возможности только в редких ситуациях и более внимательнее и ответственнее относиться к настройке тарифной сетки.

**Comment by julia-korotkina** [comment]
Отлично, спасибо большое, всё понятно.
