### ISSUE TITLE
Запрос к API через аргумент

### ISSUE THREAD

**Issue by Xershi** [onlinerby/onliner-b2b-api#112]
> После получения Access Token вы можете обращаться к ресурасм API, указав токен одним из двух способов:
> 
> аргумент запроса (пример с использованием библиотеки curl)
> curl -H 'Accept: application/json' \
>   https://b2bapi.onliner.by/shop?access_token=RECEIVED_TOKEN_STRING
Я указал так:
`СтруктураПараметровЗапроса.АдресРесурса = "/shop?access_token=" + Объект.ТокенДоступа;
`
Получаю в отчет ошибку:
> Only one method may be used to authenticate at a time (Auth header, GET or POST)
Что это значит? 
Если в заголовок добавляю:
`НоваяСтрока = ТаблицаЗаголовков.Добавить();
НоваяСтрока.Заголовок			= "Authorization";
НоваяСтрока.ЗначениеЗаголовка	= "Bearer " + Объект.ТокенДоступа;
`
То ответ приходит.
Метод аргумента не работает?

**Comment by sidorovich** [comment]
Какой именно запрос и куда выполняете? Вполне может быть, что осталась только поддержка авторизации через заголовок и это устаревшая документация.

**Comment by Xershi** [comment]
> Какой именно запрос и куда выполняете? Вполне может быть, что осталась только поддержка авторизации через заголовок и это устаревшая документация.
https://b2bapi.onliner.by/shop?access_token=ТокенДоступа

**Comment by Xershi** [comment]
Если документация устарела прошу проверить ее актуальность и устаревшие данные убрать, чтобы не вводить в замешательство.

**Comment by sidorovich** [comment]
Мы проверили. Работают оба способа. Документация актуальна и верна.

Ошибка "Only one method may be used to authenticate at a time (Auth header, GET or POST)" может возникать если вы передаете авторизационный токен одновременно двумя способами.

Внимательно проверьте какие именно данные вы отправляете.
Для удобства отладки можно использовать сервис https://requestbin.com/
Используйте его вместо нашего адреса во время отладки и вы сможете увидеть все заголовки и все данные, которые передает ваша программа.

**Comment by Xershi** [comment]
АдресРесурса = "/shop?access_token=ТокенДоступа"
В заголовках только:
"accept" = "application/json"
Метод:
"GET"
Само соединение:
ЗащищенноеСоединение | ЗащищенноеСоединениеOpenSSL
ИспользоватьАутентификациюОС | Ложь
Пароль | "ClientSecret"
Пользователь | "ClientID"
Порт | 443
Прокси |  
Сервер | "b2bapi.onliner.by"
Таймаут | 0
Что-то пропустил?

**Comment by sidorovich** [comment]
Это не выглядит как HTTP-запрос. 
Замените адрес и домен на "https://requestbin.com/r/enji3v6q4qsbg"
Вместо https://b2bapi.onliner.by/shop запрос нужно отправить на https://requestbin.com/r/enji3v6q4qsbg

**Comment by sidorovich** [comment]
Извините, адрес некорректный.
Корректный https://enji3v6q4qsbg.x.pipedream.net

**Comment by Xershi** [comment]
АдресРесурса ="/?access_token=" + Объект.ТокенДоступа
{"success":true}

**Comment by Xershi** [comment]
АдресРесурса = "/shop?access_token=" + Объект.ТокенДоступа
{"error":"invalid_request","error_description":"Only one method may be used to authenticate at a time (Auth header, GET or POST)"}

**Comment by sidorovich** [comment]
Как и предполагалось
Зайдите в браузере и посмотрите https://requestbin.com/r/enji3v6q4qsbg/1R6aOSX8v4vJn7X1Lo6uemCz35K
<img width="1154" alt="Снимок экрана 2019-09-20 в 17 35 21" src="https://user-images.githubusercontent.com/3040359/65335425-1181ab00-dbcd-11e9-90aa-4081a422630b.png">

**Comment by Xershi** [comment]
authorization
Basic NmRjNGMxOWE0ZGQ1OGNhYTUxMjA6YWY3MThhOGI4NTY5NjQ2OTQ3ZGJiZDVlYWQ1YzZiMmU2NGIzYjhmYw==
В этом проблема? 1С дописала некий заголовок сама?

**Comment by sidorovich** [comment]
Да, проблема в этом заголовке.
Где именно проблема у Вас в коде я затрудняюсь ответить.

**Comment by Xershi** [comment]
НоваяСтрока.Заголовок			= "Authorization";
//НоваяСтрока.ЗначениеЗаголовка	= "Bearer " + Объект.ТокенДоступа;
НоваяСтрока.ЗначениеЗаголовка	= "";
Сделал так...
И получил результат!
Т.е. у вас идет проверка на значение и не важно что там не текст:
"Bearer " + Объект.ТокенДоступа?

**Comment by sidorovich** [comment]
как вы видите на скриншоте мы получаем от вас текст и система не может определить какой именно авторизационный токен ей использовать.

**Comment by Xershi** [comment]
Да я понял. Просто выходит что если указать так:
НоваяСтрока.Заголовок = "Authorization";
НоваяСтрока.ЗначениеЗаголовка = "Любой текст и не важно что не токен";
То система будет искать токен.
Тут больше проблема была в том что 1С неявно добавила сама 4 заголовка и ключевой из них "Authorization". Когда явно указал, то все стало работать предсказуемо.
Есть ли у вас возможность, чтобы система анализировала наличие именно слова "Bearer " + ТокенДоступа или это оставляете на откуп разработчикам использующим АПИ?

**Comment by sidorovich** [comment]
Нет смысла пытаться искать токен в переданной строке (тратить на это ресурсы системы) если мы все равно получили 2 токена и не можем однозначно понять, что именно имел ввиду клиент.

**Comment by Xershi** [comment]
В таком случае стоит сделать оговорку в документации, что если заголовок "Authorization" будет не пустой, то система будет думать что там токен, хоть его и нет там. И нужно разработчику позаботиться, чтобы он там был или значение заголовок явно было пустое.
