### ISSUE TITLE
не могу получить список смесителей grohe

### ISSUE THREAD

**Issue by zharikovartem** [onlinerby/onliner-b2b-api#114]
возвращается null, но остальные бренды работают id=1684

**Comment by sidorovich** [comment]
по какому URL и какой запрос выполняете? можете привести пример полного HTTP-запроса?

**Comment by zharikovartem** [comment]
https://b2bapi.onliner.by/sections/106/manufacturers/1684/products
1684 - это grohe
1719 - Hansgrohe, и он работает
Вообще на смесителях работают все бренды кроме четырех.

**Comment by sidorovich** [comment]
завтра посмотрю

**Comment by sidorovich** [comment]
не можем воспроизвести. все работает
`curl -H "Accept: application/jsonections/106/manufacturers/1684/products?access_token=ВАШ_АВТОРИЗАЦИОННЫЙ_ТОКЕН --verbose`
единственное что было при первом запросе ответ формировался довольно долго. проверьте, чтобы у вас ничего не отваливалось по таймауту

**Comment by zharikovartem** [comment]
я использую данную функцию: 
function get_products($section, $brend) {
    global $TOKEN;
    $url = 'https://b2bapi.onliner.by/sections/'.$section.'/manufacturers';
    $url .= '/'.$brend.'/products';
    $process = curl_init($url);
    curl_setopt(
        $process,  
        CURLOPT_HTTPHEADER, 
        array(
            'Accept: application/json', 
            'Content-Type: application/json', 
            'Authorization: Bearer '.$TOKEN
            )
        );
        curl_setopt($process, CURLOPT_RETURNTRANSFER, TRUE);
        curl_setopt($ch, CURLOPT_CONNECTTIMEOUT ,0);
        $result = curl_exec($process);
        curl_close($process);
        return json_decode(get_utf($result), true);
}

другие разделы респонс нормальный а грое null

**Comment by sidorovich** [comment]
1. скорее всего проблема в функции get_utf, это не стандартная функция языка PHP, посмотрите какие манипуляции она производит со строкой. может быть в ответе есть какой-то символ, на который она не рассчитана и нарушается структура JSON строки.
2. попробуйте вывести содержимое `$result = curl_exec($process);` удобно проверить корректность JSON-содержимого можно на разных сайтах, например https://jsoneditoronline.org/
3. если проблема не с содержимым, а с самими запросом, то для отладки CURL-запросов можете обратиться к документации PHP https://www.php.net/manual/ru/function.curl-getinfo.php (примеры 1 и 2)

**Comment by zharikovartem** [comment]
огромное спасибо! затык тут))
