### ISSUE TITLE
Возможно нужно создать отдельный тикет.

### ISSUE THREAD

**Issue by sidorovich** [onlinerby/onliner-b2b-api#115]
Возможно нужно создать отдельный тикет.
Но получаю ошибку:
{"errors":{"contentType":["VALUE_NOT_INCLUDED_IN_ARRAY"]}}
courierDeliveryPrices сначала пустой отправлял, а затем вообще убрал.
Что она означает?

_Originally posted by @Xershi in https://github.com/onlinerby/onliner-b2b-api/issues/101#issuecomment-554323511_

**Comment by sidorovich** [comment]
неправильный HTTP-заголовок Content-Type

https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/import/info.md

выберите нужный для вашего формата данных

**Comment by Xershi** [comment]
Добрый день!
Спасибо за ответ!
Руководствовался вот этой ссылкой:
https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/import/update.md
А там не было описание нужного заголовка.
Под "Тип данных" я думал используется заголовок "accept" как и в других запросах.

**Comment by Xershi** [comment]
Единственное после успешного импорта слетели все артикулы при получении каталога.

**Comment by sidorovich** [comment]
Accept это формат нашего ответа
Content-Type это формат вашего запроса

По поводу артикулов проверьте выгрузку, есть ли они там. Мы выполняем полную замену данных ценового предложения, ничего не объединяем с существующими полями.

**Comment by Xershi** [comment]
Метод "/positions" возвращает теперь без артикула.
Возможна такая ситуация?
Отправляя данные методом "/pricelists"
Мы получили результат, что прайс обрабатывается.
Пока он не обработан мы повторно используем  "/positions" он возвращает пустой список артикулов, до обработки прайса и затем мы  "/pricelists" повторно отправляем данные без артиколов и все затираем?

**Comment by sidorovich** [comment]
не уверен, что я вас до конца понял и если отвечу на заданные вопросы, то мы можем запутаться.
попробуйте переформулировать вопросы и расположить ваши действия в точном хронологическом порядке, указывая, дожидаетесь ли вы окончания обработки прайслиста

**Comment by Xershi** [comment]
Также еще хочу заметить, что метод "/pricelist/renew"
Не потребовал заголовка "Content-Type". Поэтому и спотокнулся на выгрузке прайса.
Сейчас попробую последовательность описать.

**Comment by Xershi** [comment]
1. "/positions" вернул с артикулами 
2. "/pricelists" отправили с артикулами
3. "/positions" вернул без артикулов шаг 2 на вашем сервере не завершился
4. "/pricelists" отправили без артикулов
Все артикулы потерлись в итоге.

**Comment by Xershi** [comment]
Нашел ошибку, пропустил тег артикула при отправке.
Выходит, если я по ИД отправил без артикула, то он затерется?

**Comment by sidorovich** [comment]
"Мы выполняем полную замену данных ценового предложения, ничего не объединяем с существующими полями."
Фактически мы сначала удаляем соответствующую строку в базе данных, а потом создаем ее вновь с переданными вами данными

**Comment by Xershi** [comment]
Т.е. если я укажу свои артикулы, то они восстановятся?
А что с позициями, которые и до замены были без артикула?
Ранее менеджер говорила, что вы их вручную указывали.

**Comment by sidorovich** [comment]
Если вы передадите артикулы, и они есть у нас в базе данных, и они связаны с данным производителям, то они сохранятся.

Если замена для таких позиций передается в прайс-листе, то они будут обработаны так как переданы, будь то с артикулами или без них. Если замена для таких позиций не передается в прайс-листе, то зависит от метода, который вы используете для обновления прайс-листа: 
- PATCH обновит только те, позиции, которые переданы в выгрузке https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/import/update.md
- PUT удалит весь ваш сохраненный у нас прайс-лист и сохранит только переданные в выгрузке.

Если я правильно понимаю о чем вы, то вручную вами указываются артикулы при управлении своим прайс-листом через личный кабинет.

**Comment by Xershi** [comment]
А как связан ИД и артикул конкретного магазина? Есть скрытая таблица, которая решает обновить артикул или нет?
Использовалась команда "PATCH".

**Comment by sidorovich** [comment]
ИД?

**Comment by Xershi** [comment]
Ид товара и артикул товара конткретного магазина.
id": "1",
"article": "ipod16gb",

**Comment by sidorovich** [comment]
из какого контекста вырван пример? из вашего прайс листа?

**Comment by Xershi** [comment]
Был допустим такой прайс:
"id": "1",
"article": "ipod16gb",
Далее
"id": "1"
А затем:
"article": "КакойМнеПонравится",

**Comment by sidorovich** [comment]
article - это артикул производителя, а не строковый код нашего товара, он может совпадать, а может не совпадать.
id - это уникальный идентификатор позиции в вашем прайс-листе, вы задаете его как хотите

является ли артикул корректным для данного ценового предложения определяется по товару, к которому относится ценовое предложение, а точнее по производителю к которому относится товар.

о том, какие артикулы каким товарам соответствуют, можно узнать из файла со структурой каталога - https://content.onliner.by/catalog/structure.xml аккуратнее! он довольно велик. обновляется раз в сутки.

**Comment by Xershi** [comment]
Понял, спасибо. Все вопросы решены!

**Comment by sidorovich** [comment]
закрывайте!

**Comment by Xershi** [comment]
А как это делается?)

**Comment by Xershi** [comment]
Я автор вопроса. А автор тикета вы?

**Comment by sidorovich** [comment]
эх, точно )
