### ISSUE TITLE
можно ли импортировать объекты недвижимости через api?

### ISSUE THREAD

**Issue by 6umpukc-uHKBu3umop** [onlinerby/onliner-b2b-api#116]
не нашел описания

как выгружать свойства типа Этажность, Площадь кухни  и т п 

хотя видно что есть на сайте https://r.onliner.by/pk/apartments/298866

и как указать раздел 1 комнатная продажа и тп?

**Comment by Olden** [comment]
Вы представляете какое-то агенство недвижимости?

**Comment by 6umpukc-uHKBu3umop** [comment]
нет
но был запрос от наших клиентов - агенств недвижимости 
которые рассматривают такой вариант через api
т к ваша площадка не поддерживает популярные форматы Yandex, CIAN, Avito

**Comment by Olden** [comment]
технически возможность импорта через API есть, есть подробная документация, НО прежде чем вы получите к этому доступ агенство недвижимости должно стать нашим клиентом. Для этого им необходимо связаться с менеджером +375297755080 или написать на почту info@onliner.by.

Этот репозиторий не про недвижимость поэтому закрываю issue.
