### ISSUE TITLE
Тарифная сетка доставки

### ISSUE THREAD

**Issue by Vtc18** [onlinerby/onliner-b2b-api#117]
Добрый день. Если я правильно понял, то я настраиваю тарифную сетку в b2b и больше не передаю никакой другой информациию по API, верно ?
И такой момент, как настроить если я хочу в разделе кондиционеры поставить на все товары бесплатную доставку, но на какой то один платную, как это будет работать ?

**Comment by sidorovich** [comment]
Вы можете передавать информацию по каждой конкретной позиции в прайс-листе с указанием стоимости доставки в любой регион из вашей тарифной сетки. Данные из прайс-листа будут иметь более высокий приоритет по сравнению с тарифной сеткой. Однако мы рекомендуем использовать это только в крайне редких случаях, так как обработка прайс-листов со специфической стоимостью курьерской доставки замедляется.

Мы уже описывали данный случай в нашей документации:
https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/import/courier_delivery.md

Следить за актуальностью вы можете нажав кнопку Watch вверху страницы или читая changelog
https://github.com/onlinerby/onliner-b2b-api/blob/master/shop-changelog.md

**Comment by Vtc18** [comment]
Хорошо, а если у меня доставка еще зависит от маржи. К примеру если маржа на товар меньше 50 рублей то у меня берется платная доставка 5 рублей и не важно какая категория и какая стоимость товара. Как тогда тут быть ?

**Comment by sidorovich** [comment]
Прошу обратить внимание, что мы здесь занимаемся сугубо технической поддержкой, а это уже вопрос из области вашего бизнеса. 

В тарифной сетке помимо разделов есть еще и производители.
Насколько я знаю, нашими специалистами подразумевалось, что разграничение групп товаров по категории/производителю и стоимости позволит решать подобные задачи.

**Comment by Vtc18** [comment]
Вы меня не поняли, я у себя в программе это все настроил и это передается уже, но просто будет ли старая выгрузка работать? или надо, что то настраивать дополнительно, что бы грузить доставку через API

**Comment by sidorovich** [comment]
Значит я вас скорее всего до сих пор не понимаю.
Если вы настроили тарифную сетку и передаете уже сейчас информацию о стоимости доставки в каждый конкретный регион в ценовом предложении и прайс-лист успешно импортируется, то все хорошо и после запуска эти цифры будут видны пользователям.
Если вы будете передавать прайс-лист в старом формате, без указания стоимости доставки в каждый конкретный регион, то стоимость будет вычисляться на основании заполненной тарифной сетки.

**Comment by table-of-rates** [comment]
@sidorovich 
Тут скорее вопрос в другом,
Сейчас для всех товаров есть настроенные сроки доставки (на основании маржи/категории/бренда/поставщика/...), которые передаются через

```
[...]
"deliveryTownTime": 1,
"deliveryTownPrice": "1.00",
"deliveryCountryTime": 5,
"deliveryCountryPrice": "2.00",
[...]
```

Что будет с этими значениям после включения на проде Тарифной сетки? Они просто будут игнорироваться или будут в каком-то виде использоваться для отображения клиентам?

**Comment by sidorovich** [comment]
Буду игнорироваться:
deliveryTownPrice
deliveryCountryPrice

Буду отображаться пользователю:
deliveryTownTime - доставка по Минску
deliveryCountryTime - доставка по РБ

На данном этапе со сроками пошли на определенные упрощения исходя из анализа прайс-листов по всем магазинам.
