### ISSUE TITLE
Получить список актуальных мнемоник регионов доставки через API

### ISSUE THREAD

**Issue by table-of-rates** [onlinerby/onliner-b2b-api#118]
День добрый!

1. Как получить актуальную конфигурацию Тарифной сетки через API?
2. Как получить список актуальных мнемоник из Тарифной сетки через API?

**Comment by sidorovich** [comment]
На данный момент подобных публичных роутов нет в нашем API.
Какой магазин вы представляете?

**Comment by table-of-rates** [comment]
Магазин не важен, но при необходимости могу сообщить через службу поддержки

Откуда возникли данные вопросы?!

**Сценарий 1:**
Точно знаю на какие товары стоимость доставки отличается от той, которая будет рассчитана на основании Тарифной сетки. Хочу эту стоимость передать вместе с импортом, но в этом случае необходимо вручную актуализировать мнемоники из Тарифной сетки + нет возможности дать пользователям выбрать мнемоники из доступных вариантов (то есть снова надо вручную это актуализировать)

**Сценарий 2:**
Сейчас все рассчитывается на основании большего количества параметров, нежели цена товара, категория и/или бренд.
Согласно вашим рекомендациям стоимость доставки стоит передавать только в исключительных случаях (для более быстрой обработки). 

Но как мне узнать какая стоимость доставки будет рассчитана на основании Тарифной сетки, чтобы решить надо передавать "custom" или нет?! 

Один из вариантов -- получать конфигурацию Тарифной сетки через API и на своей стороне рассчитывать предполагаемое значение стоимости доставки и при необходимости добавлять "custom" для некоторых товаров.

Второй вариант -- иметь на вашей стороне endpoint, который позволяет по uid товара и цене получить конфигурацию доставки по регионам, которая будет рассчитана на основании опубликованной Тарифной сетки. То есть будет возможность передать список товаров с их стоимостью и обратно получить рассчитанные стоимости доставки по регионам. Для тех товаров, которые не совпадут с нашими мы можем передать "custom"

Но вообще решение Тарифная сетка изменяемая на вашей стороне не очень ложится в концепцию автоматизации со стороны клиента, значительное усложнение появляется. Для тех, кто пользуется только ЛК -- скорее всего добавляется какая-то гибкость.

**Comment by sidorovich** [comment]
Планировалось, что регионы не будут часто меняться. Правильно настроенная тарифная сетка позволяет менять стоимость доставки и способы оплаты как угодно часто. 

Для первого сценария достаточно настроить один раз тарифную сетку и передать мнемоники в IT-отдел, для автоматизации.

По поводу второго сценария: Если вы знаете как настроена Ваша тарифная сетка, то вы можете узнать какая будет стоимость доставки. 

По первому варианту: вы можете ее посмотреть в личном кабинете. Роут для получения настроенной тарифной сетки не планировался, так как мы предполагали, что вы сами настраиваете тарифную сетку и знаете что в ней настроено.

Для второго варианта: такой роут тоже не планировался и будет довольно затруднительно реализовываться, так как расчет стоимости доставки зависит от населенного пункта каждого конкретного пользователя. Сначала мы определяем в какой регион попадает населенный пункт тарифной сетки магазина и лишь потом смотрим пересечение с товарной группой.

Данных роутов не планировалось и не планируется к разработке, чтобы данные роуты попали в работу в технический отдел, Вам стоит обратиться в отдел поддержки со стороны бизнеса.

Именно поэтому хотелось бы знать какой магазин вы представляете. Потому что такое решение как тарифная сетка было согласовано с крупными клиентами и оно хорошо ложится в концепцию автоматизации данных клиентов.

Если технических вопросов больше нет, то просьба закрыть тикет. Спасибо
