### ISSUE TITLE
Выгрузка

### ISSUE THREAD

**Issue by vserozetki** [onlinerby/onliner-b2b-api#120]
Добрый день. 
Сайт на битрикс, помогите, пожалуйста, настроить выгрузку к Вам определенных категорий.
Либо через Api программы мой склад.

**Comment by sidorovich** [comment]
В чем именно у Вас возникают проблемы?
К сожалению, мы не можем предлагать готовые решения для бизнеса  с нуля под ключ.

**Comment by vserozetki** [comment]
Скачиваю csv файл, но нам абракадабра.

**Comment by sidorovich** [comment]
Проверьте правильность кодировки, должна быть UTF-8.

Как и откуда скачиваете? Вручную или скриптом?

**Comment by vserozetki** [comment]
![онл](https://user-images.githubusercontent.com/59083363/71250323-6d74e080-2330-11ea-877b-ef4567a30a81.png)

**Comment by sidorovich** [comment]
Понятия не имею откуда этот скриншот. Хотелось бы технических деталей. Как скачивается этот файл? По какому URL? Какая реализация под капотом?

Кодировку пробовали менять при открытии файла?
