### ISSUE TITLE
заливка прайс листа с одного магазина на др онлайнера оба

### ISSUE THREAD

**Issue by andrey55511** [onlinerby/onliner-b2b-api#121]
добрый, подскажите как в настройках в админке онлайнера поставить перезаливку всего прайса на другой магазин

**Comment by sidorovich** [comment]
- либо укажите во втором магазине такую же ссылку на прайс-лист, как и в первом магазине;
- либо сделайте экспорт прайс-листа в первом магазине и загрузите его вручную во втором.
