### ISSUE TITLE
Поля товара

### ISSUE THREAD

**Issue by EvgeniyBy** [onlinerby/onliner-b2b-api#122]
Добрый день! Подскажите поле артикул в выгрузке товаров должно содержать значение артикула производителя или может быть артикул присвоенный магазином? Артикул является обязательным полем или его можно не заполнять в случае если у нас используются другие артикула. 
Как правильно должно быть заполнено поле модель? Оно должно быть идентично названию товара в каталоге онлайнера?

**Comment by sidorovich** [comment]
Поле артикул должно содержать артикул производителя. По артикулу и названию производителя происходит сопоставление ценового предложения в прайс-листе с товаром в каталоге. Если артикула по каким-то причинам нет в нашем каталоге у нужного товара, то сопоставить можно по названиям категории, производителя и модели, либо обратиться в отдел наполнения каталога с просьбой добавить артикул к товару. 

Поле артикула является не обязательным, используется для удобства сопоставления. Если поле артикула не заполнено, то названия категории, производителя и модели являются обязательными к заполнению. Все эти названия должны соответствовать названиям в каталоге онлайнера. 

Корректные названия можно брать из файла со структурой каталога  https://content.onliner.by/catalog/structure.xml Но он довольно велик и обновляется раз в сутки.
