### ISSUE TITLE
Экспорт данных / courierDeliveryPrices не выгружается

### ISSUE THREAD

**Issue by table-of-rates** [onlinerby/onliner-b2b-api#123]
День добрый!

Пробуем выгрузить данные с помощью API https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/export/positions.md

Но поле courierDeliveryPrices не выгружается. В ЛК XML выгружается аналогично (то есть без этого поля) и только в CSV выгрузке можем найти информацию ранее переданную по API (для изменения стоимости доставки в выбранный регион, например 
`[...]courierDeliveryPrices: {"osnovnoj-region": {type: "custom", amount:  "1.99"}}`).

**Comment by sidorovich** [comment]
добрый день!
номер магазина подскажите, пожалуйста - проверим корректность мнемоники `osnovnoj-region`
а так же подскажите идентификатор ценового предложения, по которому вы хотите внести правки.
если это не поможет, то хотелось бы получить все содержимое JSON-запроса, который вы нам отправляете

**Comment by sidorovich** [comment]
Хотя, скорее всего у Вас просто синтаксическая ошибка в JSON: все ключи объектов должны быть в двойных кавычках. Речь про `type`, `amount`, `courierDeliveryPrices`.

Проверить корректность JSON данных можно, например, здесь - https://jsoneditoronline.org/

**Comment by table-of-rates** [comment]
Что значит ошибка, если эти данные выгружаются через CSV файл, то есть вы их приняли и обработали без ошибок. Не совсем понимаю как это может быть одновременно: и ошибки в запросе, и успешная обработка с последующей выгрузкой в CSV, но отсутствием информации в JSON/XML

**Comment by sidorovich** [comment]
В CSV-файле другой формат и указание региона происходит не через мнемонику, а через "человеческое" название региона из тарифной сетки.

**Comment by table-of-rates** [comment]
Данный передавались в JSON формате при обновлении.

Про экспорт CSV -- это был поиск вариантов проверить, получили ли вы данные или нет. Смотрите первое сообщение

**Comment by sidorovich** [comment]
Вы хотите сделать экспорт прайс-листа (от нас к вам), и он успешно формируется в формате csv, но не корректно в формате JSON?

Если я вас правильно понимаю, то мне все равно нужно знать номер вашего магазина.

**Comment by table-of-rates** [comment]
Да, Павел, все верно. 

Изначально пробовали через API сделать экспорт, там не получили нужного поля. Потом уже пробовали в ЛК сформировать XML/CSV. И только в CSV увидели информацию небходимую

Тестируем на магазине: Магазин №16207 «Тестовый» (Тестовый)

**Comment by sidorovich** [comment]
Принято, проверяем.

**Comment by sidorovich** [comment]
Да, к сожалению есть проблема на нашей стороне. На этой неделе вряд ли успеем выкатить фикс, на следующей должны. Спасибо!

**Comment by table-of-rates** [comment]
Ожидаем, спасибо!

**Comment by ivan-leschinsky** [comment]
@sidorovich 
такая  же проблема в магазине №13598. ПРи выгрузке через json нет данных об успешно загруженных ранее `courierDeliveryPrices`

**Comment by sidorovich** [comment]
проблема массовая, устраняем!

**Comment by table-of-rates** [comment]
@sidorovich Есть уже какие-нибудь сроки по планируемому фиксу для данной проблемы?

**Comment by scharniauski** [comment]
@table-of-rates @ivan-leschinsky, 
Фикс задеплоен, проверьте пожалуйста и закройте пожалуйста issue, если все ок.

**Comment by ivan-leschinsky** [comment]
@scharniauski да, теперь данные возвращаются
