### ISSUE TITLE
Не можем получить отчет по загруженному прайс листу

### ISSUE THREAD

**Issue by alex-webmaster** [onlinerby/onliner-b2b-api#124]
Добрый день!

Не можем получить отчет по загруженным прайс-листам. Хотим получить не распознанные позиции.
Загружаем прайс-лист через API, все ок. Смотрим через личный кабинет - он содержит часть нераспознанных позиций. Пробуем получить 
Например: ID 5e2e94016061aca036452fe2

Пример кода:

`
$process = curl_init("https://b2bapi.onliner.by/pricelists/'.$lastPriceListId.'/report");

        curl_setopt(
            $process,
            CURLOPT_HTTPHEADER,
            array(
                'Accept: application/json',
                'Content-Type: application/json',
                'Authorization: Bearer '.$aKey['access_token'].''
            )
        );

        curl_setopt($process, CURLOPT_CUSTOMREQUEST, 'GET');
        curl_setopt($process, CURLOPT_RETURNTRANSFER, TRUE);
        $result = curl_exec($process);
        curl_close($process);
`

В результате ничего не возвращается.

**Comment by kamadoss** [comment]
Добрый день. Подскажите, пожалуйста, ID магазина

**Comment by alex-webmaster** [comment]
17958

**Comment by kamadoss** [comment]
По вашему ID импорта получаем список ошибок, всё работает как и должно. 
Можете предоставить полное тело запроса и ответа от нашего сервера?

**Comment by alex-webmaster** [comment]
Спасибо, разобрались, была опечатка.
