### ISSUE TITLE
Порт для доступа по адресу b2bapi.onliner.by

### ISSUE THREAD

**Issue by julia-korotkina** [onlinerby/onliner-b2b-api#125]
Добрый день. У нашего хостинга доступ к внешним ресурсам закрыт по умолчанию.  Уточните, пожалуйста, по какому порту требуется открыть доступ для адреса b2bapi.onliner.by?

**Comment by Olden** [comment]
Добрый день. Подскажите как вы поняли что вам доступ закрыт? если ping, то для ping доступ действительно закрыт. Уточните по какому протоколу вы пытаетесь обратиться к api ?

**Comment by julia-korotkina** [comment]
Тех. поддержка active.by сказала, что доступ к внешним ресурсам закрыт, но они могут открыть конкретный адрес по запросу.

**Comment by Olden** [comment]
тогда пусть открывают по домену) но если отвечать на ваш вопрос прямо до api доступно по протоколу https и как следствие порт 443

**Comment by julia-korotkina** [comment]
Спасибо!
