### ISSUE TITLE
Блокировка запроса

### ISSUE THREAD

**Issue by julia-korotkina** [onlinerby/onliner-b2b-api#126]
Добрый день.
Извините, не стоило закрывать предыдущий issue до решения вопроса.

Проблема такова: не проходит соединение с нашего хостинга с адресом b2bapi.onliner.by. Обратились к провайдеру, попросили открыть соединение (так как ранее оговаривалось, что это у них закрыт доступ к внешним ресурсам). Попросили открыть для доступа к вашему домену. Получили следующий ответ: "На данный момент видим, что соединиться с сервера by137.atservers.net с адресом b2bapi.onliner.by не удается, так как соединение блокируется на стороне b2bapi.onliner.by.
Рекомендуем обратиться к системному администратору ресурса b2bapi.onliner.by."

Ранее работали на другом хостинге и проблем с доступом не возникало. К сожалению, на данный момент имеем возможность работать только с active.by, поэтому надо как-то решить проблему.

**Comment by Olden** [comment]
скажите ip вашего сервера с которого вы делаете запросы

**Comment by julia-korotkina** [comment]
178.159.247.47

**Comment by Olden** [comment]
этот ip адрес у нас не заблокирован. повторюсь если провайдер проверяет доступность нашего домена ping'ом, ТО он действительно будет недоступен!

**Comment by julia-korotkina** [comment]
Произошло чудо, они всё починили, теперь соединение работает. Спасибо большое за оперативные ответы,

Есть еще маленький вопрос по поводу ошибки импорта - пишет "неуникальная цена". Это означает, что для этого товара поле с ценой дважды отправляется через json?  Или что означает эта ошибка?

**Comment by Olden** [comment]
Для каждого товара, если там несколько позиций, они (позиции) должны быть с разными ценами
