### ISSUE TITLE
История загрузок прайса, отображение в Список закачанных в систему файлов в личном кабинете

### ISSUE THREAD

**Issue by b0tanics** [onlinerby/onliner-b2b-api#127]
Добрый день. 
Будьте добры, подскажите по вопросам: 

1. Есть ли возможность посмотреть историю загрузок прайсов больше чем отображено в личном кабинете?
2. Возможна ли отправка прайса методом PATCH без отражения его в _"Список закачанных в систему файлов"_ ?
yadi.sk/i/SnvF9pkz7jE5lw

Проблема заключается в том, что если по API в течении дня отправляется много прайсов, то мы не можем увидеть историю, что было загружено до этого, а в ряде случаев это было бы полезно.

**Comment by Olden** [comment]
Добрый день.
1. Сейчас храним 10 последних загрузок.
2. Сейчас мы не разделяем загрузки прайса файлом через интерфейс, или через апи, или через механизм когда мы сами скачиваем с ваших серверов файлы.
