### ISSUE TITLE
Доставка

### ISSUE THREAD

**Issue by Vtc18** [onlinerby/onliner-b2b-api#129]
Добрый день. Заметил, что не корректно выгружается стоимость доставки на площадку.
Выгрузка идет по API товар Electrolux EWH 50 Quantum Pro доставка по минску и РБ бесплатная, но вижу,что по минску 5 рублей по РБ бесплатная. В чем может быть нюанс ?
--

**Comment by sidorovich** [comment]
Стоимость доставки в данный момент рассчитывается согласно настроенной тарифной сетке. Существующие в прайс-листе колонки в данный момент не используются и скоро будут удалены. Так как вопрос скорее всего не технический, Вам быстрее помогут в отделе по работе с клиентами Тел. +375 (29) 77-55-080, +375 (44) 77-55-080, email: info@onliner.by

Здесь мы оказываем поддержку только по каким-либо техническим проблемам при работе с нашим API.
