### ISSUE TITLE
Есть ли готовые модули для систем типа opencart?

### ISSUE THREAD

**Issue by ikitby** [onlinerby/onliner-b2b-api#131]
мы давно работаем с вашей платформой но основой все же является сайт https://showers.by он организован на opencart Версия ocStore 2.3.0.2.3 и содержит в себе всю нашу номенеклатуру, часть из которой мы периодически выкладываем у вас. Что не очень удобно в ручном режиме. Можно ли связать каталог у нас с обновлением цен автоматически при изменении на сайте цен или курса?

**Comment by gladkyby** [comment]
через zoomos.by меняется цена на сайте и в каталоге, если их модуль к себе прикрутите

**Comment by ikitby** [comment]
Зумус не совсем то. что нам надо. Точнее совсем не то. у нас нет проблем с ценами поставщика. Надо связать наш каталог и каталог на онлайнере. Как вообще связать наши цены и цены на онлайнере, наличие и вообще как тестировать и получить более подробную информацию о работе с API? Мы хотим связать каталоги сайта и каталог, который выгружается у вас. Хотим чтобы по ссылке в личном кабинете шло обновление наличия и прайса

**Comment by sidorovich** [comment]
Мы не занимаемся поддержкой модулей для сторонних систем, для opencart у нас модуля нет, есть ли сторонние реализации я не знаю. 

Вся документация по API доступна в данном репозитории. Я не знаю деталей вашего бизнес-процесса и структуры ваших баз данных, чтобы давать вам какие-либо советы по реализации вашей системы. 

Сопоставлять товары в вашей системе и в нашей вы можете 2 способами: 
- название раздела-название производителя-название товара
- название производителя-артикул производителя

Если каких-либо товаров или артикулов в нашем каталоге нет - обращайтесь в отдел наполнения каталога, оставляйте соответствующие заявки.

Информация о наших товарах доступна в файле со структурой каталога. На странице "Импорт Экспорт" в админке есть ссылка "Структура каталога Onliner (xml)".
Файл довольно большой. Обновляется раз в сутки, ночью.

**Comment by ikitby** [comment]
А есть ли какая то песочница, где можно было бы покопаться не создавая проблем себе и системе?

**Comment by sidorovich** [comment]
нет
