### ISSUE TITLE
Импорт\экспорт тарифной сетки

### ISSUE THREAD

**Issue by iktomy** [onlinerby/onliner-b2b-api#132]
Есть или планируется функция экспорта и импорта тарифной сетки.
При настройке в кабинете руками наблюдается дичайшее педалирование

**Comment by sidorovich** [comment]
Вообще не планировали. А вы какой магазин? Посмотрим, может быть сможем чем-то помочь.

**Comment by iktomy** [comment]
Магазин 21vek.by

**Comment by sidorovich** [comment]
а не подскажете характеристики вашей системы? у нас немного подлагивает, на тарифной сетке примерно с вашими настройками но в целом работать можно.
