### ISSUE TITLE
смена id предложений каталога

### ISSUE THREAD

**Issue by gladkyby** [onlinerby/onliner-b2b-api#134]
Здравствуйте!
Некоторое время назад заметил, что перестали синхронизироваться товары, потому что в каталоге сменились некоторые id предложений.
С чем это связано?

**Comment by sidorovich** [comment]
id ценовых предложений введены для удобства маппинга предложений с CRM магазинов, это ответственность каждого магазина. они вправе менять их когда захотят и как им удобно.

если у вас поменялись id ваших предложений, то, скорее всего, ваш магазин не использует импорт ценовых предложений по API либо не передает идентификаторы и они генерируются каждый раз заново для обеспечения совместимости.

в любом случае, мы могли бы постарались более детально ответь на ваш вопрос, если бы вы привели конкретные примеры идентификаторов.

**Comment by gladkyby** [comment]
мы используем экспорт из каталога по api и связь товаров настроена по id предложений. При удалении товара из каталога и добавлении его вновь, мы указывали новый id у себя и все работало как прежде. Несколько лет не менялись id предложений, которые постоянно есть в прайсе, и недавно заметили, что у них также изменились номера.

**Comment by sidorovich** [comment]
не совсем понимаю ваш процесс:

1) какой у вас номер магазина?
2) я правильно понимаю, что наша система является первоисточником данных для вашей внутренней системы?
3) что вы использовали чтобы создавать ценовые предложения в вашем прайс-листе: веб-интерфейс или API?
4) указывали ли вы вручную id предложений при создании?
5) можете ли вы привести примеры товаров с которыми возникли проблемы?

**Comment by gladkyby** [comment]
1. 1042
2. true
3. веб-интерфейс
4. false
5. Лампа	FJLED-209AS: old_id 903177025 => new_id 575198001
Зеркальный фотоаппарат EOS 77D Body: old_id 4350123427 => new_id 1087113001
Зеркальный фотоаппарат EOS 800D Body: old_id 4263513990 => new_id 1064348001

**Comment by sidorovich** [comment]
исходя из вашей информации я вижу противоречия. постараюсь вам их объяснить не вдаваясь глубоко в детали реализации.

при создании ценового предложения через интерфейс невозможно вручную задать id-предложения. соответственно id  предложения будет автоматически сгенерирован. мы используем правило - числовой идентификатор товара и порядковый номер ценового предложения на данный товар у данного магазина. например, 575198001 => 575198 001

идентификаторы 4350123427 4263513990 выглядят непохожими, значит были переданы в таком виде с вашей стороны либо в прайс-листе, либо через API.

если был выполнен переход от кастомных идентификаторов к автоматически сгенерированным, то такое возможно только если ценовые предложения были удалены и созданы вновь через web-интерфейс, либо переданы через API без указания идентификатора.

отсюда могу сделать вывод, что проблема с работой с идентификаторами предложений где-то на вашей стороне. возможно, у вас несколько человек управляют прайс-листом и не согласовывают свои действия. либо какие-то еще проблемы.

еще раз: данные идентификаторы мы не меняем, только можем автоматически сгенерировать при создании ценового предложения, если идентификатор явно не задан.

посему, боюсь, что помочь вам я больше ничем не могу. надеюсь вам хватит этой информации для поиска проблемы.
