### ISSUE TITLE
Невалидный csv при импорте файла

### ISSUE THREAD

**Issue by AlexanderSekerin** [onlinerby/onliner-b2b-api#136]
При импорте прайс-листа выдало информацию в б2б о невалидном прайсе.

"Отчет об импорте прайс-листа "price-list2020-03-25.csv"
Не удалось импортировать файл. Невалидный csv."

дата импорта 2020-03-25

В приложении снимки из б2б и сам прайс для импорта.
==============================

Почему данный csv система восприняла как невалидный?
![Screenshot_1](https://user-images.githubusercontent.com/59997777/77618080-b0091300-6f46-11ea-9c5b-462d22f77aa5.png)
![Screenshot_2](https://user-images.githubusercontent.com/59997777/77618081-b0a1a980-6f46-11ea-81ac-6c22fe679925.png)

[price-list2020-03-25.zip](https://github.com/onlinerby/onliner-b2b-api/files/4385465/price-list2020-03-25.zip)

**Comment by sidorovich** [comment]
Ваш прайс-лист не содержит названий колонок, мы перестали поддерживать данный формат. Рассылка об этом была около 2 недель назад.

Добавьте в первую строку таблицы названия колонок:
https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/formats.md#csv-%D1%81-%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%D0%BC-%D0%BA%D0%BE%D0%BB%D0%BE%D0%BD%D0%BE%D0%BA

Это связано с запуском тарифной сетки курьерской доставки. В связи с этим из прайс-листов убрана поддержка колонок для указания стоимости доставки по минску и по РБ.
