### ISSUE TITLE
Ресурс b2bapi.onliner.by снова не доступен по порту 443

### ISSUE THREAD

**Issue by julia-korotkina** [onlinerby/onliner-b2b-api#138]
Добрый день.

Не доступен ресурс с сервера.
Ответ тех поддержки хостинга:

На стороне сервера правила для доступа к ресурсу добавлены.
$ telnet b2bapi.onliner.by 443
Trying 178.124.129.16...
telnet: connect to address 178.124.129.16: No route to host
Trying 178.124.129.14...
telnet: connect to address 178.124.129.14: No route to host
Trying 178.124.129.12...
telnet: connect to address 178.124.129.12: No route to host

На данный момент не удается подключиться к данному ресурсу с IP-адреса 178.159.247.46, подключение блокируется на стороне b2bapi.onliner.by.
Рекомендуем обратиться к системному администратору ресурса b2bapi.onliner.by и уточнить информацию.

**Comment by Olden** [comment]
Попробуйте:
curl https://b2bapi.onliner.by 
или
telnet b2bapi.onliner.by 80

ваш IP не в бане

**Comment by julia-korotkina** [comment]
Спасибо за ответ!
Тех. поддержка скорректировала настройки фаервола, теперь всё работает.
