### ISSUE TITLE
Старая версия прайс-листа

### ISSUE THREAD

**Issue by michael-borisov** [onlinerby/onliner-b2b-api#14]
С 05.08.2015 по запросу **GET /positions** стала возвращаться старая версия прайс-листа. Возможно ли, что работает какое-то *странное кэширование* и можно это как-то исправить?

**Comment by michael-borisov** [comment]
пинг @pmonliner

**Comment by pmonliner** [comment]
@michael-borisov подскажите номер вашего магазина
Опишите пожалуйста подробнее на каком этапе вы видите старую версию прайс листа?
После POST/PATCH? 
Кеширования нет, похожих жалоб от других магазинов так же нет

**Comment by michael-borisov** [comment]
@pmonliner 
Номер 252, api client начинается b048....
Версия прайс-листа возвращается по запросу **GET /positions** в любой момент . Данные забираются в JSON. Возвращается 671 позиция из 827 (все позиции видны при экспорте в csv).
Спасибо!

**Comment by pmonliner** [comment]
Заврос GET /positions  для вашего магазина вернул мне именно 827 позиций
Запрашивал в csv для того, что бы быстро их посчитать.

**Comment by michael-borisov** [comment]
@pmonliner вполне вероятно, что я мог ошибиться с номером магазина и api client id.
Запросил в csv, тоже 671 строка.

**Comment by michael-borisov** [comment]
@pmonliner действительно, моя ошибка. Спасибо большое!
