### ISSUE TITLE
Ошибка авторизации при выгрузке заказов

### ISSUE THREAD

**Issue by IvanFilipchik** [onlinerby/onliner-b2b-api#140]
Добрый день!
При формировании GET-запроса 
На адрес: https://cart.api.onliner.by/orders
С параметрами:
1)Authorization: Bearer<Токен>;
2)Accept:application/json; charset=utf-8;
Выдает ошибку авторизации. Хотя, если до этого,авторизироваться в личном кабинете партнера и простой перейти по адресу "https://cart.api.onliner.by/orders" (в адресной строке), то все ок.
Может быть есть еще какая-либо авторизации для получения данных заказа? 
Спасибо!

**Comment by sidorovich** [comment]
Документация по cart-api доступна здесь:
https://github.com/onlinerby/onliner-cart-api

Авторизация для web-интерфейса и для клиентов API отличается.

Получаете токен как описано в документации? 
Client ID и Client Secret отличаются для работы с b2b-api и cart-api.

Если все правильно скиньте нам HTTP код и тело нашего ответа. По возможности с вашим запросом (вместе с заголовками).

**Comment by IvanFilipchik** [comment]
Я понимаю что отличается, поэтому и вопрос. 
Токен успешно создается(eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ1c2VyX3R5cGUiOiJiMmJfc2hvcCIsInVzZXJfZGF0YSI6eyJpZCI6MTgxMTksIm5hbWUiOiJLRVk0WU9VIn0sImFwaV90eXBlIjoiY2FydCIsImIyYl9vcGVyYXRvciI6IjE4MTE5QGFwaS1jbGllbnQuY2FydCIsImlhdCI6MTU4ODc1MTc0NCwic2NvcGVzIjpbXSwiZXhwIjoxNTg4NzU1MzQ0fQ.Mo453AWrwRXrxEQlf5_yWJh52b8Wb7SHUnnPijvrqRT7X9kLXuaMeOWYMeWN0Oo9Z_tQbcZUlsYLWuZTOwTNfQ);
GET запрос: https://cart.api.onliner.by/orders?Authorization=Bearer<eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ1c2VyX3R5cGUiOiJiMmJfc2hvcCIsInVzZXJfZGF0YSI6eyJpZCI6MTgxMTksIm5hbWUiOiJLRVk0WU9VIn0sImFwaV90eXBlIjoiY2FydCIsImIyYl9vcGVyYXRvciI6IjE4MTE5QGFwaS1jbGllbnQuY2FydCIsImlhdCI6MTU4ODc1MTc0NCwic2NvcGVzIjpbXSwiZXhwIjoxNTg4NzU1MzQ0fQ.Mo453AWrwRXrxEQlf5_yWJh52b8Wb7SHUnnPijvrqRT7X9kLXuaMeOWYMeWN0Oo9Z_tQbcZUlsYLWuZTOwTNfQ>

**Comment by sidorovich** [comment]
в cart-api токен можно передавать только в заголовках, через URL-параметры не примет

**Comment by IvanFilipchik** [comment]
![image](https://user-images.githubusercontent.com/46783599/81153614-c1a0fa00-8f8b-11ea-84a0-1655438fba1f.png)

**Comment by sidorovich** [comment]
попробуйте в содержимом заголовка писать "Bearer СОДЕРЖИМОЕ_ТОКЕНА_БЕЗ_УГЛОВЫХ_СКОБОК_ЧЕРЕЗ_ПРОБЕЛ_ПОСЛЕ_СЛОВА_BEARER"
без кавычек

**Comment by IvanFilipchik** [comment]
Понял, спасибо
