### ISSUE TITLE
Ошибка при выгрузке обновлений для товаров: WinHttp.WinHttpRequest: The connection with the server was terminated abnormally

### ISSUE THREAD

**Issue by MrMurom** [onlinerby/onliner-b2b-api#141]
Появилась ошибка при выгрузке файла для обновления товаров в каталоге.
Перестало работать примерно в 05.05.2020 17:00:29
Запрос на сайт отправляю через WinHttp.WinHttpRequest.5.1
Пример кода на 1с ниже.
Ошибка появляеться при вызове 
`HTTP.WaitForResponse(1200000);`
Текст ошибки
`Произошла исключительная ситуация (WinHttp.WinHttpRequest): The connection with the server was terminated abnormally`

```
HTTP=Новый COMОбъект("WinHttp.WinHttpRequest.5.1");
HTTP.SetTimeouts(300000, 300000, 700000, 700000);
Метод = ?(ТолькоИзменения,"PATCH","PUT");
HTTP.Open(Метод,УРЛ,1);
ЗаголовокHTTP = ПолучитьЗаголовкиДляАвторизацииОнлинер(глСтруктураПараметровСайтаОнлинер,ТипФайла);

Для каждого врСтрока Из ЗаголовокHTTP Цикл
	HTTP.SetRequestHeader(врСтрока.Ключ,врСтрока.Значение);
КонецЦикла;
Попытка
	HTTP.Send(Источник);
Исключение
КонецПопытки;
HTTP.WaitForResponse(1200000);
```

**Comment by sidorovich** [comment]
Дайте ваш IP-адрес - проверим не попали ли вы случайно под блокировку, попутно проверьте соединение между вашим сервером и нашим доменом, уточните у своего провайдера.

1С код нам ничего не говорит, гораздо полезнее было бы посмотреть на полный HTTP ответ, если он есть.

**Comment by MrMurom** [comment]
Наш IP 194.158.212.1девять
Сайт онлайнера и каталог открывается с сервера откуда идут запросы.

**Comment by sidorovich** [comment]
Мы посмотрели логи и обнаружили, что часть запросов от Вас проходит.

```
194.158.212.19 [06/May/2020:09:50:06 +0300] https "POST /oauth/token HTTP/1.1" 317 0.657 200 776 "-" "1C+Enterprise/8.3" "194.158.212.19" "BY/Minsk" fpm_upstream=- ssl=TLSv1.2
194.158.212.19 [06/May/2020:09:50:06 +0300] https "POST /oauth/token HTTP/1.1" 317 0.691 200 769 "-" "1C+Enterprise/8.3" "194.158.212.19" "BY/Minsk" fpm_upstream=- ssl=TLSv1.2
194.158.212.19 [06/May/2020:09:59:13 +0300] https "GET /pricelists/5eb25f953666ac1584587722/status HTTP/1.1" 253 0.018 200 629 "-" "1C+Enterprise/8.3" "194.158.212.19" "BY/Minsk" fpm_upstream=- ssl=TLSv1.2
194.158.212.19 [06/May/2020:09:59:13 +0300] https "GET /pricelists/5eb25f953666ac1584587722/report HTTP/1.1" 253 0.255 200 13956 "-" "1C+Enterprise/8.3" "194.158.212.19" "BY/Minsk" fpm_upstream=- ssl=TLSv1.2
194.158.212.19 [06/May/2020:09:59:14 +0300] https "GET /pricelists/5eb25f9a3666ac11165169d2/status HTTP/1.1" 253 0.022 200 630 "-" "1C+Enterprise/8.3" "194.158.212.19" "BY/Minsk" fpm_upstream=- ssl=TLSv1.2
194.158.212.19 [06/May/2020:09:59:14 +0300] https "GET /pricelists/5eb25f9a3666ac11165169d2/report HTTP/1.1" 253 0.201 200 128380 "-" "1C+Enterprise/8.3" "194.158.212.19" "BY/Minsk" fpm_upstream=- ssl=TLSv1.2
194.158.212.19 [06/May/2020:09:59:16 +0300] https "GET /pricelists/5eb25fa0445eac51562b9d42/status HTTP/1.1" 253 0.023 200 630 "-" "1C+Enterprise/8.3" "194.158.212.19" "BY/Minsk" fpm_upstream=- ssl=TLSv1.2
194.158.212.19 [06/May/2020:09:59:16 +0300] https "GET /pricelists/5eb25fa0445eac51562b9d42/report HTTP/1.1" 253 0.188 200 66349 "-" "1C+Enterprise/8.3" "194.158.212.19" "BY/Minsk" fpm_upstream=- ssl=TLSv1.2
```

Однако, последний успешный запрос на обновление прайс-листа был, как вы и сказали в 16:51
```
194.158.212.19 [05/May/2020:16:51:51 +0300] https "PATCH /pricelists HTTP/1.1" 167379 0.089 202 554 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)" "194.158.212.19" "BY/Minsk" f
pm_upstream=- ssl=TLSv1
```

Но если посмотреть внимательно, то оказывается, что у этих запросов разные User-Agent и как следствие разные версии TLS

POST GET - 1C+Enterprise/8.3 - ssl=TLSv1.2 - все хорошо
PATCH - Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5) - ssl=TLSv1 - все плохо

Наши системные администраторы вчера в 17:00 прекратили поддержку TLS1. К сожалению вам стоит проверить версию TLS и обновить библиотеки, которые вы используете, чтобы обеспечить поддержку TLS 1.2 в обоих клиентах.

Возможно эта статья Вам как-то поможет. 
https://support.microsoft.com/ru-ru/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-wi

**Comment by MrMurom** [comment]
Все понятно.
Удалите, пожалуйста, наши IP из ваших сообщений.
Спасибо.
