### ISSUE TITLE
Товар не в наличии

### ISSUE THREAD

**Issue by heavydott** [onlinerby/onliner-b2b-api#142]
Здравствуйте. Подскажите, пожалуйста, как сделать товар не в наличии.
В описании API у вас написано "Опциональный параметр. Наличие: in_stock (есть на складе и доступен для покупки), run_out_of_stock (осталось мало или заканчивается)".
А если сейчас товар совсем закончился, но завтра он может появиться. И чтобы сейчас нельхя было его купить.

**Comment by Olden** [comment]
указывайте цену 0

**Comment by heavydott** [comment]
Понял, спасибо.

**Comment by heavydott** [comment]
А как долго проходит обновление? В самом каталоге товар еще имеет цену и доступен для покапки.

**Comment by Olden** [comment]
до 10 минут

**Comment by heavydott** [comment]
Отлично! На этом все, спасибо)
