### ISSUE TITLE
Перестала работать отправка файлов для обновления каталога. Ошибка 429

### ISSUE THREAD

**Issue by MrMurom** [onlinerby/onliner-b2b-api#144]
Добрый день.
Перестала работать отправка файлов для обновления каталога. Пытаемся сделать полное обновление каталога , но получаем ошибку 429.
Вчера все работало.
У нас часто меняются цены и большой ассортимент товара. Несколько магазинов на вашей площадке. 
Как нам сейчас обновлять каталог ?

**Comment by sidorovich** [comment]
Какой номер магазина? Сколько файлов вы отправляете?

**Comment by MrMurom** [comment]
Получаю заголовок 
"Retry-After" "1224"
Нам что ждать по примерно 20 минут чтоб изменить цены и остатки на сайте ?

Номер магазина: 1791 и 2033. Примерно по 80k товаров в магазине.
Отправляем по 5-20 файлов по 300 позиций примерно в  каждом. Зависит от количества изменений цен и остатков в базе.
Если сделать размер порции больше, то бывает не обрабатываются файлы с вашей стороны.

**Comment by sidorovich** [comment]
ограничение на 50 необработанных прайс-листов одномоментно. ограничение выставляется на час. следите за результатами обработки ваших прайс-листов. данную штуку мы ввели, потому что некоторые магазины злоупотребляют частым обновлением и загружают очередь на столько, что остальные прайс-листы не успевают обрабатываться. пока что группируйте в более большие файлы.

у нас действует кэш цен на 10 минут, так что обновлять цены чаще не имеет смысла. собирайте в более большие пачки ваши данные.  мы сейчас обсудим куда можно подвигать лимит и стоит ли это делать.

**Comment by sidorovich** [comment]
Ваши магазины не попали в список злоупотребляющих, поэтому согласовали уменьшение лимитов. 
На данном этапе лимиты общие для всех. Сейчас это будет 100 одновременных прайс-листов в работе, блокировка в случае превышения на 10 минут. Ограничения начнут действовать когда истечет Ваша текущая блокировка. 

Будем совместно подстраивать систему.
Спасибо за понимание! Это первая версия системы мониторинга за загрузкой, в дальнейшем будем ее подстраивать, но все цифры для понимания ограничений есть в ответе: время бана в заголовке, ограничения по прайс листам в теле ответа.

**Comment by MrMurom** [comment]
Лимиты устанавливаются на магазин или на IP адрес, с которого обновление идет ?
Мы сейчас перенастроим выгрузку на 5k-10k и обновление раз в 15мин. Проверим.
Очень хотелось бы, чтоб вы заранее предупреждали о введении новых функций. Чтобы мы и другие пользователи вашей системы могли заранее предусмотреть ошибки и держать обмены на контроле, а не в спешном порядке потом пытаться исправить ошибки.
Спасибо.

**Comment by sidorovich** [comment]
Очень хотелось бы, чтобы магазины тоже заранее предупреждали, когда собираются выгрузить 15000 прайс-листов одномоментно ) Это была экстренная мера, чтобы не пострадали остальные магазины на площадке.

Лимиты срабатывают по магазину, IP адрес не учитывается.

**Comment by sidorovich** [comment]
А может вы можете подсказать все магазины, которые являются "другими пользователями вашей системы", чтобы мы могли проверить нет ли их в списке злоупотреблявших?

**Comment by MrMurom** [comment]
> А может вы можете подсказать все магазины, которые являются "другими пользователями вашей системы", чтобы мы могли проверить нет ли их в списке злоупотреблявших?

У нас только 2 этих магазина.
Под "другие пользователи вашей системы" я подразумевал не наши магазины а всех пользователь вашей системы.
"Злоупотреблениями" мы не занимаемся, мы лишь стараемся держать наши цены и остатки в актуальном состоянии с учетом конъюнктуры рынка.
Сейчас мы настроили обмены на 5k-10k товаров и обновление раз в 10-15мин. Сейчас обмены работают.
