### ISSUE TITLE
Перестала идти выгрузка данных через API.

### ISSUE THREAD

**Issue by chicco-onliner** [onlinerby/onliner-b2b-api#145]
C 2020-05-05 перестали выгружаться данные по API.

При попытке выгрузки пишет. 

{ОбщийМодуль.OnlinerBy.Модуль(344)}: Ошибка при вызове метода контекста (Send)
	HTTPЗапрос.Send(ПараметрыПОСТ); 
по причине:
Произошла исключительная ситуация (WinHttp.WinHttpRequest): Соединение с сервером было неожиданно прервано

Наш магазин: №14335 «Chicco.by» (Chicco.by) 

Магазин временно отключался где-то на 2 месяца. Сейчас мы возобновили деятельность и столкнулись вот с такой ошибкой. С нашей стороны софт не дорабатывался и не обновлялся.

**Comment by Olden** [comment]
Добрый день. Подскажите ваш IP адрес

**Comment by Olden** [comment]
Так же почитайте этот комментарий проблема может быть аналогичная:

https://github.com/onlinerby/onliner-b2b-api/issues/141#issuecomment-624482407

**Comment by chicco-onliner** [comment]
Наш IP: 195.222.78.162

**Comment by Olden** [comment]
почти на 100% уверен, что у вас старая версия tls

**Comment by chicco-onliner** [comment]
Да. У нас старая версия TLS. Спасибо разъяснили ситуацию.
