### ISSUE TITLE
PATCH /pricelists (оптимизация импорта)

### ISSUE THREAD

**Issue by table-of-rates** [onlinerby/onliner-b2b-api#146]
Добрый день!

Так как метод PUT /pricelists имеет ограничение по размеру payload, то приходится использовать комбинацию с PATCH /pricelists.

Вопрос: как лучше посылать PATCH /pricelists для более быстрой обработки на вашей стороне? То есть если надо отправить 50к товаров, то лучше отправить 2 запроса по 25к или 10 по 5к позиций?

**Comment by sidorovich** [comment]
абсолютно не имеет значения. все прайс-листы будут обрабатываться по очереди. мы отказались от параллельной обработки прайс-листов, так как большинство магазинов на своей стороне не разделяют зоны ответственности по прайс-листам и обновляют цены на одни и те же товары в разных прайсах, которые в случае параллельной обработки порождают взаимные блокировки. пробуйте, смотрите время обработки ваших данных.

как показывает общая практика: лучше всего 2-3 раза в сутки выгружать полный прайс-лист, в остальное время присылать обновления только по изменившимся позициям, но не каждый момент, а собирать их в пачки за 10-15-30 минут.

имейте ввиду, что на нашей стороне для ценовых предложений может срабатывать 10-минутный кэш. то есть обновлять цены чаще чем в 10 минут абсолютно не имеет смысла

**Comment by table-of-rates** [comment]
Понятно, спасибо!
