### ISSUE TITLE
Соблюдение лимита на категорию

### ISSUE THREAD

**Issue by table-of-rates** [onlinerby/onliner-b2b-api#148]
Добрый день!

Для определенных разделов у вас есть лимиты. Например, ноутбуки - 1200 для базовой стоимости тарифа.

Предположим, что сейчас есть 1199 ноутбуков в разделе. Какая должна быть последовательность методов API, чтобы заменить 100 ноутбуков на другие предложение и не превысить лимит?

То есть надо сделать 1199 - 100 + 100, но никак не 1199 + 100 - 100.

Запросы на удаление не отображаются в ЛК и, соответственно, нет понимания очередности их выполнения. Выполняются ли они в общей очереди, необходимо ли дожидаться их обработки и т.д.

Итого: **как правильно заменить товары и не превысить лимит?**

**Comment by table-of-rates** [comment]
@sidorovich 
То есть можно отправлять DELETE /pricelists с указанием ID на удаление нужных 100 товаров и как только метод вернул HTTP/1.1 202 Accepted (Задача на удаление успешно поставлена в очередь) можно сразу отправлять PATCH с указанием новых 100 товаров?

В этом случае не будет технической возможности превысить лимит, верно?

**Comment by sidorovich** [comment]
Не совсем. Если удаление не произойдет или пройдет частично, а вы не дождетесь результатов обработки, то успешный PATCH с новыми товарами превысит лимит. Если удаление пройдет успешно, то лимиты не превысятся.

**Comment by table-of-rates** [comment]
@sidorovich 
Ok, а как тогда узнать результаты удаления? Когда оно завершится (или завершилось) и что удалилось/не удалилось (частично или полностью прошло)?

**Comment by sidorovich** [comment]
https://github.com/onlinerby/onliner-b2b-api/blob/master/shop.md#%D0%BE%D1%82%D1%87%D0%B5%D1%82-%D0%BF%D0%BE-%D0%B8%D0%BC%D0%BF%D0%BE%D1%80%D1%82%D1%83

**Comment by sidorovich** [comment]
да, пожалуй вы правы. по удалению отчета нет. пометим в доработки, большинство пользуется только методами PUT и PATCH.

**Comment by sidorovich** [comment]
Вы можете не отправлять DELETE, если хотите обновить цены. Используйте PATCH и будут обновлены цены только на переданные товары в прайс-листе.

**Comment by table-of-rates** [comment]
@sidorovich Тут как раз вопрос в том, как заменить одни предложения на другие без превышения лимита. Про PATCH для изменения цены знаем, но тут совершенно другая ситуация.

**Comment by table-of-rates** [comment]
@sidorovich  Но еще проще будет, если вы будете гарантировать порядок обработки запросов PUT/PATCH/DELETE в общей очереди в порядке получения ответа HTTP/1.1 202 Accepted.


То есть если мы отправили PUT(1), PATCH (2), DELETE (3), PATCH (4), PATCH (5) и вы в там же порядке ответили 202, то вы гарантируете, что в таком же порядке будут обработаны запросы и в этом случае на не столь важен статус для DELETE (3) операции, так как она будет обработана до PATCH (4), PATCH (5), но после PATCH (2) и мы можем на это рассчитывать.

**Comment by sidorovich** [comment]
Порядок выполнения запросов гарантированно будет соблюден. 
Проблема может возникнуть, только если DELETE из-за ошибочных данных в запросе не удалит какие-то ценовые предложения.
В остальном все верно: предложенная вами модель должна работать, если в прайсах все передано верно.

А можно полюбопытствовать, зачем в вашей цепочке DELETE, если первым запросом PUT вы очищаете весь старый прайс-лист? в запросе PATCH (2) или PUT(1) идут ошибочные данные?

**Comment by table-of-rates** [comment]
DELETE в нашем случае убирает распроданные товары или товары, которые уже не являются актуальным для продажи (товар закончился у поставщика на складе, например)

**Comment by sidorovich** [comment]
их можно не включать в PUT и они тоже будут удалены

**Comment by table-of-rates** [comment]
1. Полностью обновили прайс с PUT
2. Изменили цены по некоторым товарам
3. Сняли с продажи несколько товаров
4. Изменили цены
5. Изменили описание / сроки

У вас ограничение на размер PUT, мы не можем каждый раз полностью отправить прайс. А если каждый раз дробить на PUT PATCH PATCH, то возникает пауза, когда представлены не все товары на площадке (то есть пока не обработается второй и третий patch). Приходится использоваться DELETE+PATCH чтобы как-то иметь возможность синхронизировать прайс.

**Comment by sidorovich** [comment]
ясно, я вас понял. и время задержки вас не устраивает. спасибо.

**Comment by table-of-rates** [comment]
Да, время задержки и стало проблемой.

**Comment by onliner-api-beta-tester** [comment]
Столкнулись с аналогичной проблемой.

1) Вы пишете, что гарантируете последовательность обработки запросов, на деле это не так, т.е. если отправить первым запрос DELETE и получить ответ 200, а следом отправить запросы PATCH - нет никакой гарантии, что DELETE будет обработан первым. Более того, если даже просто отправить последовательно 3 запроса PATCH (каждый раз дожидаясь ответа 200) - они могут быть обработаны в совершенно любой последовательности. Очередь обработки запросов на вашей стороне работает некорректно.

2) Из-за этого бага, у магазина были несколько раз списаны деньги за превышение лимита. Есть ли возможность получить компенсацию за эти дни?

**Comment by sidorovich** [comment]
Пришлите пожалуйста идентификаторы выгрузок PATCH, которые прошли непоследовательно.

**Comment by onliner-api-beta-tester** [comment]
Идентификаторы запросов не сохранились, но вы можете сделать такой тест самостоятельно (отправить 3 PATCH запроса по 20к товаров), т.к. в отчетах у вас не фиксируется время начала обработки, с нашей стороны это сделать проблематично. Т.е. у вас в отчетах отображается только дата получения запроса, а дата начала обработки запроса - не отображается. Кроме того, DELETE запросы вообще не отображаются в админке и их увидеть невозможно с нашей стороны. Было бы удобно, если бы вы добавили в отчеты эту информацию (дату начала обработки, дату завершения обработки, delete запросы)

Т.е. нам чтобы отследить этот баг, нужно сидеть в админке и жать F5, чтобы отловить момент и сделать скриншот, когда запросы перешли в статус обработки в неверной последовательности, но такую картину наблюдали неоднократно.

**Comment by onliner-api-beta-tester** [comment]
Решили всеже потратить время и воспроизвести ошибку (т.к. на слово вы не верите). Вот скриншоты ситуации, когда обработка запросов происходит в совершенно случайно последовательности (не по очереди отправки).

![Selection_574](https://user-images.githubusercontent.com/67737417/86348770-d1c21680-bc68-11ea-9df7-9b0b53ade7f0.png)
![Selection_573](https://user-images.githubusercontent.com/67737417/86348773-d25aad00-bc68-11ea-841e-bd738ae47157.png)
![Selection_572](https://user-images.githubusercontent.com/67737417/86348775-d2f34380-bc68-11ea-83f6-8343ab873685.png)

Прошу так-же дать ответ насчет компенсации за превышение лимита (5 дней)

**Comment by onliner-api-beta-tester** [comment]
![Selection_575](https://user-images.githubusercontent.com/67737417/86349211-717fa480-bc69-11ea-9ffd-598276ebd9a8.png)

**Comment by sidorovich** [comment]
Скажите ваш номер магазина. Мы попробуем ваши данные на нашем тестовом магазине. Если проблема воспроизведется, передадим информацию в отдел по работе с клиентами. С ними будете решать вопрос о компенсации. Здесь сугубо техническая поддержка и финансовые вопросы мы решать не уполномочены.

**Comment by onliner-api-beta-tester** [comment]
Номер магазина на котором сейчас воспроизвели - 16207

**Comment by sidorovich** [comment]
Спасибо. Постараемся сегодня дать ответ, получилось ли воспроизвести проблему.

**Comment by onliner-api-beta-tester** [comment]
Прошу уточнить, что значит "если проблема воспроизведется" помоему на скрине явно видно, что проблема воспроизводится, разве нет? И мы это наблюдали много раз.

**Comment by sidorovich** [comment]
Нам чтобы что-то исправить надо воспроизвести самим и определить где есть проблема. Иначе просто не понятно что именно нужно исправлять. Просто хотим держать с вами обратную связь

**Comment by onliner-api-beta-tester** [comment]
Спасибо за информцию, ждем от вас подтверждения проблемы и информацию по срокам исправления. На наших тестах воспроизводится довольно стабильно, думаю у вас тоже получится легко ее воспроизвести.

Рассмотрите пожалуйста также возможность добавления в отчет полей - "дата начала обработки" и "дата завершения обработки" и добавления DELETE запросов в отчеты.

**Comment by sidorovich** [comment]
Смогли воспроизвести Вашу проблему только в том случае, если отправлять прайс-листы друг за другом с коротким интервалом не дожидаясь окончания загрузки предыдущего. Если дожидаться окончания загрузки предыдущего, то загрузка происходила в нужном порядке.

Проблема в том, что время импорта отмечается временем обращения к серверу, а задачи в очередь все таки попадают по окончанию загрузки всего содержимого. Соответственно если загружать файлы как Вы, с интервалом в 1-3 секунды, и последующий файл меньше предыдущего, то вероятность того, что в очередь последующий файл попадет раньше предыдущего сильно увеличивается.

Данную проблему мы озвучили бизнесу и планируем ее решать, но сориентировать по срокам я пока не могу - само техническое решение довольно затруднительно из-за особенностей реализации нашей очереди, а так же сам процесс согласования плана работ может занять какое-то время. 

По поводу компенсации, как я и говорил, Вы можете обратиться в отдел по работе с клиентами - мы передали им информацию о данной проблеме с Вашим магазином.

На данное время могу лишь посоветовать Вам дожидаться окончания загрузки одного прайс-листа прежде чем отправлять следующий.

Приношу извинения за причиненные неудобства.

**Comment by onliner-api-beta-tester** [comment]
На наш взгляд вы описали проблему не совсем корректно.

Проблема в данном случае не в том, что мы часто отправляем файлы с интервалом "1-3 секунды(с)", интервал отправки в данном случае совершенно не имеет значения, мы отправляем файлы последовательно, один за одним, и при отправке дожидаемся ответа 200 от вас, и как только получили ответ 200 от вашего сервера, отправляем следующий файл. (т.е. параллельной многопоточной отправки запросов у нас нет - она последовательная)

Соответственно мы ожидаем, что принятые запросы становятся в очередь у вас и обрабатываются последовательно (как вы утверждаете, должно так работать). Дожидаться на нашей стороне завершения обработки каждого запроса нерационально (а для DELETE запроса невозможно, ввиду отстстувия идентификатора запроса), т.к. это равноценно тому, чтобы делать очередь на нашей стороне. Т.е. всем вашим клиентам придется реализовывать очередь обработки на своей стороне, логичнее починить очередь обработки на вашей стороне.

Т.е. если даже мы поставим задержку между отправкой, например 60 секунд, это может не помочь, т.к. запрос на обновление 25к товаров может обрабатываться 5 минут, и эта задержка нас так же не спасет.

**Comment by onliner-api-beta-tester** [comment]
Добрый день. Подскажите, есть информация по срокам решения данной проблемы?

**Comment by onliner-api-beta-tester** [comment]
Добрый день. Подскажите, есть информация по срокам решения данной проблемы?

**Comment by sidorovich** [comment]
информации по срокам нет

**Comment by onliner-api-beta-tester** [comment]
Добрый день!

Нужно что-то решать с проблемой обработки запров в случайном порядке. Запросы в API должны обрабатываться в порядке очереди поступления, как это заявлено в документации.

Сейчас с появлением возможности размещать больше товаров в каталоге, эта проблема становится еще более актуальной, поясню на простом примере:

0. Предусловие: товара в нет наличии, и в b2b онлайнера он стоит под заказ (например, срок доставки 14 дней)
1. Товар появляется у поставщика в наличии, идет к вам запрос №1 на выставление статуса "в наличии" (срок доставки - 1 день)
2. Товара у поставщика не стало, идет к вам запрос №1 на выставление статуса "под заказ" (срок доставки - 14 день)
3. Вы обрабатываете сначала запрос №2 а потом запрос №1

Результат: в админке онлайнера стоит по товару срок доставик 1 день.

Проблема актуальна для многих, нельзя ее бесконечно игнорировать: см. аналогичную задачу - https://github.com/onlinerby/onliner-b2b-api/issues/165
