### ISSUE TITLE
Error from API

### ISSUE THREAD

**Issue by AnastasiaPle** [onlinerby/onliner-b2b-api#153]
Здравствуйте! 

Не позволяет ваша API авторизоваться 21vek.by для обновления данных о товарах с 2020-08-04 09:06:08. 
В 2020-08-04 09:03:07 обновление прайс-листа прошло успешно, спустя 3 минуты пришла ошибка "invalid_client : The client credentials are invalid". Данные для авторизации мы не меняли. Скажите, пожалуйста, меняли ли вы что-то, что могло повлечь за собой эту ошибку?

Спасибо!

**Comment by sidorovich** [comment]
Вроде ничего не менялось. Массовых жалоб не поступало. Проверьте авторизационные данные, посмотреть можно в личном кабинете магазина. На какой роут вы стучите? Какой статус ответа и полное тело ответа?

**Comment by AnastasiaPle** [comment]
Спасибо! Как всю информацию соберу, отпишусь.

**Comment by sidorovich** [comment]
JFYI: вчера от имени 21го века обращался человек с другим ником, https://github.com/onlinerby/onliner-b2b-api/issues/152
думаю, что имеет смысл убедиться, что у вас нет проблем с параллельной разработкой, если это были не вы, а кто-то из другой команды

**Comment by AnastasiaPle** [comment]
Обращался другой отдел и по другому вопросу. Но спасибо за информацию, это может быть как-то связано

**Comment by AnastasiaPle** [comment]
Извините, а есть ли у вас песочница для проверки запросов на тестовом окружении?

**Comment by sidorovich** [comment]
нету
