### ISSUE TITLE
A1. Автоматизация выгрузки продуктов, цен, остатков

### ISSUE THREAD

**Issue by TatianaHotkina** [onlinerby/onliner-b2b-api#154]
Добрый день.

Для магазина №475   хотим настроить автоматизацию выгрузки продуктов цен и остатков из внутренних систем компании. в связи с этим есть несколько вопросов:

1. Ряд атрибутов в магазине onliner и в наших внутренних системах отличаются (ID, category, vendor, model, article),Можем ли мы c выгрузкой передавать только ID продукта, который будет равен ID продукта в магазине onliner, а остальные атрибуты, которые используются в магазине - category, vendor, model, article, будут подтягиваться автоматически?

2. Какие поля для формирования файла, представленные в примере API являются обязательными:
"id": 
"category"
"vendor"
"model"
"article"
"price"
"currency"
"comment"
"producer"
"importer"
"serviceCenters"
"warranty"
"deliveryTownTime"
"deliveryCountryTime"
"productLifeTime"
"isCashless"
"isCredit"
"stockStatus"
"courierDeliveryPrices"

3. Т.к. основные позиции уже внесены  в ручную в кабинете onliner, необходимо ли будет перегружать продукты (делать первую выгрузку) через PUT / pricelist? Или мы сможем сразу начать обновлять продукты через PATCH/ pricelist

4. Как часто мы можем высылать обновления по продуктам? Вопрос связан с тем, что обновление остатков на сайте a1.by происходит каждые пять минут. Сможете ли вы поддержать обновленные выгрузки прайслистов в такой период времени? Или нам ориентироваться не на такое частое время выгрузок.

5. При изменении остатков цена на продукт у нас не меняется, только меняется остаток. Если мы передадим статус Out of stock для продукта, у которого цена не будет равна 0, обработает ли система такой файл  и произойдет ли автоматическое закрытие карточки продукта в магазине onliner? Или скрытие карточек полностью на стороне бизнес-пользователя Личного кабинета. 

6. Каким образом определять товары, которые находятся в статусе "Предзаказ"? Тоже через сток статус или у вас это отдельный атрибут? Или такого статуса вообще нет?

7. Есть ли Swagger к API PUT/pricelist и PATCH/ pricelist и можете ли вы их предоставить.

8. Если мы настроим выгрузку, останется ли возможность у бизнес-пользователя вносить правки в Личном кабинете. Вопрос связан с тем, что ряд атрибутов у нас отсутствует. 

Спасибо.

**Comment by TatianaHotkina** [comment]
Добрый день.
Подскажите, можно ли получить ответы на вопросы выше?

**Comment by gladkyby** [comment]
Были похожие на ваши вопросы. посмотрите [тут](https://github.com/onlinerby/onliner-b2b-api/issues/134) и [тут](https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/import/update.md)

**Comment by TatianaHotkina** [comment]
Добрый день.
По предложенным ссылкам не нашла ответов на вопросы выше.

**Comment by sidorovich** [comment]
1. Нет, в данный момент есть 2 способа идентификации: по category, vendor, model, либо по vendor, article, однако не у всех товаров есть артикулы. Также следует иметь ввиду, что товары могут перемещаться между разделами и производителями.
См. документацию: https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/import/replace.md

2. Все, кроме "stockStatus" и "courierDeliveryPrices", некоторые можно передавать пустыми, но передавать нужно.

3. Зависит от того, насколько вы уверены в надежности связи между вами и нами. Если Вы будете работать только по модели частичного обновления и какой-либо импорт не пройдет корректно, то возникнет неконсистентность данных, которую может быть сложно исправить. Большинство магазинов 1-2 раза в сутки делают полное обновление прайс-листа и в течении дня присылают изменения по некоторым позициям для поддержания актуальности.

4. У нас действует 10 минутный кэш на ценовые предложения. Чаще обновлять точно не имеет смысла. Более детальный совет по настройкам сможем вам дать в будущем, в зависимости от интенсивности ваших импортов и количества предложений в прайс-листе. Можете пока воспользоваться моделью 1-2 раза в сутки полное обновление и раз в час обновление актуальных остатков. Если Вы будете присылать обновления слишком часто (осознанно или по ошибке) у нас сработает бан на 10 минут в том случае, если в очереди будет одновременно 100 или более задач на обновление данных.

5. Передавайте стоимость 0, если товар закончился. Если передавать флаг отсутствия наличия на складе, то у нас просто не будет отображаться значок наличия, но само ценовое предложение остается висеть на сайте. Это просто информационная, но не управляющая фича, так как вводилась позже и мы не ломали совместимость со старыми магазинами.

6. Предзаказа у нас нет, мы продаем только те товары, которые есть в наличии у наших магазинов.

7. Нет. Примеры кода на PHP можете найти в документации. Больше на данный момент ничего нет.

8. Личный кабинет и API работают параллельно. Но следить за консистентностью и актуальностью данных в любом случае нужно на Вашей стороне.

**Comment by TatianaHotkina** [comment]
@sidorovich , спасибо большое за развернутые ответы. Стартовали разработку.

Но появилось еще несколько уточнений:

1. не по всем передаваемым параметрам получилось найти тип:

Параметр | Тип
-- | --
ID | string
Category | ?
vendor | ?
model | ?
article | string
price | string
currency | string
comment | ?
producer | ?
importer| ?
serviceCenters | ?
warranty | ?
deliveryTownTime | ?
deliveryCountryTime | ?
productLifeTime | ?
isCashless | ?
isCredit | ?
stockStatus | string

Для параметров с вопросом также использовать string? Или есть особенности?

2. Второй вопрос связан с авторизацией. У нас уже создан личный кабинет Магазин №475 «ИП "Велком"»
Для доступа к API попробовали использовать креды Личного кабинета.
Получили ошибку
![image](https://user-images.githubusercontent.com/69791278/95443105-db909f80-0964-11eb-8d3d-1cf1cc35f255.png)

Верно ли я понимаю, что для доступа к API креды Личного кабинета нам не подойдут, и нам требуется новая регистрация в приложении, согласно документу https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/application.md

Спасибо.

**Comment by sidorovich** [comment]
1. Посмотрите примеры https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/formats.md#json
В общих чертах сложно ответить, так как это зависит от выбранного Вами протокола и Вашей технической базы. Например, JSON-типизированный формат, а в CSV все значения представлены как строки.

2. Да, реквизиты доступа к личному кабинету и к нашим API различны, для каждого API нужно получать свои токены внутри личного кабинета. Это сделано для того, чтобы Вы могли на своей стороне разделять доступ к данным на уровне управляющего стаффа и технических специалистов. Например, можно отдать на аутсорс интеграцию API без прямого доступа к кабинету.

**Comment by TatianaHotkina** [comment]
@sidorovich , спасибо.

**Comment by TatianaHotkina** [comment]
@sidorovich , добрый день.

Мы заканчиваем разработку с нашей стороны и появилось несколько вопросов в рамках предстоящего тестирования:

1. есть ли какая-то тестовая среда, где мы можем протестировать корректность выгрузок? Или только прод?
2. Что значат кнопки "Сохранить приложение" и "Удалить" в разделе личного кабинета B2B API?
3. Нужна ли какая-то подготовка Личного кабинета перед стартом работ с B2B API?

![image](https://user-images.githubusercontent.com/69791278/95972676-6832d600-0e1b-11eb-97f9-3f3a944b736c.png)

Спасибо.

**Comment by sidorovich** [comment]
1.  Нет, пробуйте выгрузки на прод в неполном формате на менее популярные позиции.

2. "Сохранить приложение" - если мне не изменяет память, позволяет переименовать (комментарий только для вас используется) "Удалить" - позволяет отозвать авторизационные реквизиты, например, если они были скомпрометированы. Дальше их придется создавать вновь и прописывать в Вашем приложении. После удаления восстановить их нельзя, задать вручную тоже нельзя.

3. Только сгенерировать ключи и подключить необходимые разделы.

4. Нет. Прайс-листы из обоих источников попадают в единую очередь обработки и будут обработаны последовательно.

5. PATCH позволяет добавлять позиции.
