### ISSUE TITLE
Ошибка обновления прайса по API

### ISSUE THREAD

**Issue by Denis-Leshchuk** [onlinerby/onliner-b2b-api#156]
Добрый день!
У нас кроном ежечасно обновляется файл прайса. После обновления файла мы его загружаем по API.
В личном кабинете вижу, что последний раз прайс обновлен в 12:00 01.09.20.
На свей стороне мы ничего не меняли.
Прошу помочь разобраться в проблеме. Магазин №3467

![image](https://user-images.githubusercontent.com/43576738/91960766-f8f19e80-ed12-11ea-8e40-66d9b4e5316a.png)
![image](https://user-images.githubusercontent.com/43576738/91960632-d069a480-ed12-11ea-8490-70c7b2db6a17.png)

**Comment by sidorovich** [comment]
на какой операционной системе работает ваш код?
делали диагностику сетевую? возможно проблемы со связью между нашими серверами

**Comment by Denis-Leshchuk** [comment]
Проблема найдена. Оказалась на нашей стороне. спасибо.
