### ISSUE TITLE
Идентификатор вендора

### ISSUE THREAD

**Issue by iktomy** [onlinerby/onliner-b2b-api#157]
Здравствуйте,
А ID производителя одинаковое для всех разделов, где представлены его товары, или для каждого раздела оно уникально?

**Comment by sidorovich** [comment]
ID производителя уникален между собой, но могут быть разные комбинации:
- чаще всего один и тот же бренд/производитель доступен в разных разделах, например Samsung это телевизоры, телефоны, пылесосы и т.д.
- реже, у бренда выводится суббренд/производитель, который производит только товары одной группы, например Mitsubishi Heavy Industries производитель бренда Mitsubishi, который занимается только системами кондиционирования.

Более подробно и конкретно Вам должны помочь либо в отделе по наполнению каталога, либо в отделе по работе с клиентами. Здесь сугубо техническая поддержка.

**Comment by iktomy** [comment]
Спасибо, сейчас будет технический вопрос: как возникают ситуации, что по одному производителю меняется его идентификатор? Связано ли это с суббрендами?

**Comment by sidorovich** [comment]
Опять не технический вопрос - эти данные полностью в ведении отдела по наполнению каталога. Они управляют и названиями, и идентификаторами, и переносят товары от раздела к разделу, от бренда к бренду.

Здесь поддержка сугубо по вопросам нашего API. За каждой записью в нашей базе данных мы не следим.

**Comment by iktomy** [comment]
Спасибо
