### ISSUE TITLE
Не обновляются статусы и цены на товары через API

### ISSUE THREAD

**Issue by iktomy** [onlinerby/onliner-b2b-api#158]
**Предусловия:**
Магазин 21vek.by - не обновляются статусы по товарам в каталоге. Запросы на удаление товара из каталога или обновления цены по товару выполняются, но не отображаются в каталоге Онлайнер.

**Шаги воспроизведения:**
Выполнялось через REST-клиент для теста
1. Выполнен запрос на удаление позиции 1789069 из каталога: HTTP-метод DELETE - https://b2bapi.onliner.by/pricelists/1789069, получен ответ с кодом 202 Accepted
2. Выполнен запрос на получение статуса позиции 1789069 в системе: https://b2bapi.onliner.by/sections/114/manufacturers/2126/products/1789069/positions, получен ответ для состояния "stockStatus": "run_out_of_stock",
3. С некоторыми промежутками (от одной до 10 минут) выполнялись повторные запросы на статус позиции, и результат был тот-же: https://b2bapi.onliner.by/sections/114/manufacturers/2126/products/1789069/positions, получен ответ для состояния "stockStatus": "run_out_of_stock"

**Фактический результат:**
Запрос на удаление висит в очереди и не удаляется. Предложение для товара продолжает быть актуальным для магазина 21vek.by в каталоге - https://catalog.onliner.by/food_dehydrator/kitfort/kt1911

**Ожидаемый результат:**
Задание в очереди обработалось, предложение товара отсуствует для магазина 21vek.by

**Дополнительные материалы:**
Запрос на удаление позиции
![выява](https://user-images.githubusercontent.com/46050234/92590184-75045d00-f2a4-11ea-8914-6e1b7739918d.png)
Запрос на получение состояния позиции
![выява](https://user-images.githubusercontent.com/46050234/92590655-43d85c80-f2a5-11ea-96cf-0507e61a9cb9.png)

**Устройства, на которых воспроизводится проблема:**
не важно

**Comment by sidorovich** [comment]
Не могли бы вы прислать тело и заголовки запроса, который отправляли нам в пункте

Выполнен запрос на удаление позиции 1789069 из каталога: HTTP-метод DELETE - https://b2bapi.onliner.by/pricelists/1789069, получен ответ с кодом 202 Accepted

на время выяснения проблемы можем удалить позицию вручную

**Comment by scharniauski** [comment]
Здравствуйте. 
ID 1789069, который был передан, является не ID позиции, а ID товара.
В вашем случае необходимо передать ID `onliner5890022`

![image](https://user-images.githubusercontent.com/47104084/92715898-c37a3000-f366-11ea-9ee9-b039841c9568.png)

**Comment by scharniauski** [comment]
Напишите пожалуйста, удалось ли вам решить проблему.

**Comment by iktomy** [comment]
Спасибо. С таким идентификатором всё хорошо работает, и товар удаляется с сайта
