### ISSUE TITLE
Описание значений для поля stockStatus

### ISSUE THREAD

**Issue by iktomy** [onlinerby/onliner-b2b-api#159]
Отправляя запрос GET /sections/{sectionId}/manufacturers/{manufacturerId}/products/{productId}/positions по кеонкретному товару, получаю данные в поле stockStatus = "run_out_of_stock"
Что значит этот статус для каталога? И где можно почитать про все статусы для этого поля?

**Comment by sidorovich** [comment]
<img width="1339" alt="Снимок экрана 2020-09-10 в 20 59 24" src="https://user-images.githubusercontent.com/3040359/92777089-859dfb80-f3a8-11ea-91d9-76eaa6109799.png">

**Comment by iktomy** [comment]
Спасибо
