### ISSUE TITLE
Добавить новое поле в блок с информацией о ценовой позиции

### ISSUE THREAD

**Issue by 727d34cafd8d275379c2** [onlinerby/onliner-b2b-api#160]
Добрый день. Скажите, есть ли возможность добавить в Описание блока с информацией о ценовой позиции (каждый объект в массиве positions) новое поле? 
![image](https://user-images.githubusercontent.com/69187081/93308569-1cd0dc00-f80b-11ea-9232-8df62bb98c01.png)

**Comment by sidorovich** [comment]
Речь про B2B API или про Cart API ?
В b2b идентификаторы передаются

**Comment by 727d34cafd8d275379c2** [comment]
Про Cart API

**Comment by sidorovich** [comment]
Тогда вы не там завели issue.
Подобный вопрос уже поступал. https://github.com/onlinerby/onliner-cart-api/issues/50
Задача в работе. Скорее всего до конца следующей недели будет выполнена.

**Comment by sidorovich** [comment]
Добавили идентификатор ценового предложения в ответы API
https://github.com/onlinerby/onliner-cart-api/blob/master/CHANGELOG.md#17092020

**Comment by 727d34cafd8d275379c2** [comment]
Спасибо большое, что проинформировали
