### ISSUE TITLE
Ошибка валидации

### ISSUE THREAD

**Issue by Denis-Leshchuk** [onlinerby/onliner-b2b-api#163]
Добрый день! Магазин 3467
Пробуем переделать выгрузку по API в CSV формате.
Столкнулись с проблемой  ошибки валидации, но при загрузке этого же файла вручную через ЛК ошибка валидации отсутствует. https://prnt.sc/vhy95s

 отправляем так    curl_setopt($process, CURLOPT_POSTFIELDS, ['file' => new CurlFile($filename, 'text/csv')]);
При скачивании прайслиста через ЛК первыми строками вставляется "шапка"
![image](https://user-images.githubusercontent.com/43576738/98937783-f7eda200-24f7-11eb-856e-fa3b6f70a5e2.png)
Подскажите пример php curl запроса загрузки csv-прайлиста в ваш апи?

**Comment by sidorovich** [comment]
Попробуйте слать не файл, как файл в форме, а просто его содержимое.
Пример: https://github.com/onlinerby/onliner-b2b-api/blob/9d3e20fd62074e768b36f9b9a82a4271a5cb3e16/docs/price-lists/import/update.md

curl_setopt($process, CURLOPT_POSTFIELDS, $data);
