### ISSUE TITLE
Нет возможности передать пустой артикул товара, используя API

### ISSUE THREAD

**Issue by onliner-api-beta-tester** [onlinerby/onliner-b2b-api#164]
**Предусловия:**

Тестирование проводили на примере товара у которого есть два варианта артикулов:
```
<model id="1388041" name="RK621PS4">
    <articles>
     <article>RK621PS4</article>
     <article>730742</article>
    </articles>
   </model>
```

В b2b.onliner.by есть возможность для данного товара выбрать артикул  **RK621PS4** либо **730742**, также есть возможность указать пустой артикул, пункт в дропбоксе - **"Без артикула"**.

Соответетснно должна быть возможность сделать тоже и используя API.

Но, **через API можно только выбрать один из артикулов** - RK621PS4 либо 730742, **возможности передать пустой артикула через API - нет**. Пробовали в JSON передавать для поля артикул пустое значение, также пробовали удалять этот атрибут - безуспешно. Примеры запросов:

`
    {"model": "RK621PS4", "article": "", ... }
`
`
    {"model": "RK621PS4", ... }
`
Результат:
При отправке пустого значения для поля артикул (либо при удалении этого атрибута из JSON), onliner выбирает первый попавшийся артикул из списка (это видно в b2b.onliner.by)

Ожидаемый результат:
При отправке пустого значения для поля артикул (либо при удалении этого атрибута из JSON), onliner выбирает значение **"Без артикула"**

**Comment by sidorovich** [comment]
Во-первых, артикул может передаваться только один для ценового предложения. См. формат передачи: https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/formats.md#xml

Если вы не передали артикул, то он не будет сохранен в ценовом предложение - в этом можно убедиться выполнив экспорт прайс-листа с нашего сайта после импорта.

В веб-интерфейсе в данный момент, если ничего не задано, подставляется первый известный нам артикул по товару. Это сделано для того, чтобы пользователи, которые используют только веб-интерфейс и не используют API плавно пополняли свой прайс-лист артикулами. Однако по данному сценарию периодически поступают жалобы и, возможно, в скором времени он будет изменен.

**Comment by onliner-api-beta-tester** [comment]
> Во-первых, артикул может передаваться только один для ценового предложения. 
Мы и передаем только 1 артикул.

> Во-вторых, в веб-интерфейсе в данный момент, если ничего не задано, подставляется первый известный нам артикул по товару
Выходит установить пустой артикул через API невозможно. Прошу подтвердить.

**Comment by onliner-api-beta-tester** [comment]
> Во-первых, артикул может передаваться только один для ценового предложения

Мы и передаем только 1 артикул

> Во-вторых, в веб-интерфейсе в данный момент, если ничего не задано, подставляется первый известный нам артикул по товару. Это сделано для того, чтобы пользователи, которые используют только веб-интерфейс и не используют API плавно пополняли свой прайс-лист артикулами. Однако по данному сценарию периодически поступают жалобы и, возможно, в скором времени он будет изменен.

Да, это как минимум супер неочевидно - артикул не задан, а в b2b отображается как будто он задан...

**Comment by sidorovich** [comment]
Для веб-интерфейса фикс на днях выгрузили.
