### ISSUE TITLE
Обновление файлов через API

### ISSUE THREAD

**Issue by AMDby1689** [onlinerby/onliner-b2b-api#165]
Я отравляю вам на обновление 4 файла, все в разное время, почему в обработку берутся файлы не по очереди? Что первое пришло то и обработать в первую очередь.

**Comment by onliner-api-beta-tester** [comment]
Добрый день!

Нужно что-то решать с проблемой обработки запров в случайном порядке. Запросы в API должны обрабатываться в порядке очереди поступления, как это заявлено в документации.

Сейчас с появлением возможности размещать больше товаров в каталоге, эта проблема становится еще более актуальной, поясню на простом примере:

Предусловие: товара в нет наличии, и в b2b онлайнера он стоит под заказ (например, срок доставки 14 дней)
Товар появляется у поставщика в наличии, идет к вам запрос №1 на выставление статуса "в наличии" (срок доставки - 1 день)
Товара у поставщика не стало, идет к вам запрос №1 на выставление статуса "под заказ" (срок доставки - 14 день)
Вы обрабатываете сначала запрос №2 а потом запрос №1
Результат: в админке онлайнера стоит по товару срок доставик 1 день.

Проблема актуальна для многих, нельзя ее бесконечно игнорировать: см. аналогичную задачу - #168

**Comment by sidorovich** [comment]
проблема нарушения хронологии нам известна и запланирована для решения, в текущей ситуации мы рекомендуем отправлять запросы только после обработки предыдущего.
