### ISSUE TITLE
Получение url на страницу товара

### ISSUE THREAD

**Issue by julia-korotkina** [onlinerby/onliner-b2b-api#166]
Добрый день!

Хотелось бы иметь возможность получать url страниц товаров (например https://catalog.onliner.by/games/ps5/marvelspmanmmps5). Например, в методе GET /positions. Скажите, пожалуйста, есть ли возможность добавить это поле?

**Comment by Olden** [comment]
up @sidorovich

**Comment by sidorovich** [comment]
На сколько актуальна проблема?

**Comment by julia-korotkina** [comment]
@sidorovich всё ещё хотелось бы иметь данную опцию))

**Comment by sidorovich** [comment]
зафиксируем просьбу, но по срокам пока ничего не могу сказать.
