### ISSUE TITLE
Добавление связки товар - пункт выдачи в api

### ISSUE THREAD

**Issue by krylov-as** [onlinerby/onliner-b2b-api#172]
Добрый день. 

Сейчас через я api можно передать только количество товаров на складе. Но у нас часть товаров есть только в магазине. Можно ли доделать возможность связывать товар с конкретным пунктов выдачи товара?

**Comment by sidorovich** [comment]
Пока не планировали, но мы зафиксировали Ваше пожелание.

**Comment by krylov-as** [comment]
Добрый день, 
Может изменился статус и планируете добавить такую возможность?

**Comment by sidorovich** [comment]
Статус изменился, но не в лучшую сторону. Поэтому в ближайшее время не планируем. Работаем над другими направлениями.
