### ISSUE TITLE
Получить размер комиссии

### ISSUE THREAD

**Issue by chuduk** [onlinerby/onliner-b2b-api#173]
Где можно в API смотреть размер комиссии на категорию? Может смогли бы вывести этот показатель в /sections/{id} ?

**Comment by Olden** [comment]
up @sidorovich

**Comment by sidorovich** [comment]
Данная задача стоит в плане работ, в ближайший месяц вряд ли мы добавим эту информацию.
Пока что можете использовать ссылку https://docs.google.com/spreadsheets/d/1SGFaTkV_Ru4vI29ml9yvR-dMz9rOl7DVVpKk64w5lqM/edit#gid=372016392
