### ISSUE TITLE
Автоматизация выгрузки для магазина №475

### ISSUE THREAD

**Issue by TatianaHotkina** [onlinerby/onliner-b2b-api#174]
**Предусловия:**
Добрый день.
Настраиваем автоматизацию выгрузки продуктов в магазин №475.
Приложение активировано
Пытаемся получить авторизационный токен, но в ответ на запрос получаем ошибку

**Шаги воспроизведения:**
Отправляем запрос 

URI         : [https://b2bapi.onliner.by/oauth/token]
21.04.28 14:44:58:534	INFO	Method      : [POST]
21.04.28 14:44:58:534	INFO	Headers     : [{Accept=[application/json], Authorization=[Basic NmViNTYwNjVmZTdjMzFkM2Y0MDA6NzNmODU0ZTdjZjBmNTBkMDFhMGVmMTNlMDg4YTdkM2MxZGY3ODQyOQ==], Content-Type=[application/x-www-form-urlencoded], Content-Length=[29]}]
21.04.28 14:44:58:534	INFO	Request body: [grant_type=client_credentials]

**Фактический результат:**
Получаем ответ

[JSON_Response.txt](https://github.com/onlinerby/onliner-b2b-api/files/6391786/JSON_Response.txt)

**Ожидаемый результат:**
Получение токена для дальнейшего импорта продуктов. 

Просьба проверить, почему приходит ошибка.

**Comment by TatianaHotkina** [comment]
Добрый день.
Можно ли получить ответ?

**Comment by scharniauski** [comment]
Здравствуйте,
Проверьте пожалуйста верно ли указаны Client ID и Client Secret со страницы настройки OAuth-приложения.
Для этого сделайте запрос через curl, не используя приложение, как в примере https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/oauth20.md

К сожалению, в предоставленном файле не смог найти тело ответа и статус код, который вернул запрос. Пришлите пожалуйста эти данные для более детального понимания сути проблемы.

**Comment by scharniauski** [comment]
@TatianaHotkina подскажите пожалуйста удалось ли решить проблему?
