### ISSUE TITLE
Не отключаются неактивные товары по API

### ISSUE THREAD

**Issue by venompro** [onlinerby/onliner-b2b-api#175]
Магазин №6498 «Newton.by»

По API не отключаются неактивные товары
Отправляем запрос:
DELETE /pricelists
Accept: application/json
["676219"]

Приходит ответ:
HTTP/1.1 202 Accepted 
[]

При это товар по-прежнему активен в кабинете и на сайте:
https://catalog.onliner.by/tv/artelgroup/32ah90gsmart

В запросе передаётся также "Content-Type: application/json", но не помогает всё равно.
Прошу срочно исправить.

**Comment by drcreazy** [comment]
Добрый день. 

Проверил только что удаление позиции для тестового магазина на роут DELETE /pricelists не увидел каких либо проблем. 

Необходимо убедиться, что значение в теле запроса ("676219")  это именно ID позиции (а не например ID товара)

Из-за технических особенностей операция удаления может выполнится не моментально, в интерфейсе b2b после обработки, в интерфейсе catalog по мере перестроения отображения. 

Если эта проблема повторяется хотелось бы еще получить от вас IP адрес откуда вы шлете запрос и насколько это возможно точный временной диапазон запроса.

**Comment by NadyaGornostay** [comment]
Добрый день.
 Аналогичная проблема. 
Магазин 17175. Отправляю запрос на удаление одной позиции в прайслисте, передаю id позиции, который отправляла, когда эту позицию в прайс добавляла. Приходит ответ 202. Позиция сохраняется 1,5 часа (отправляла запрос на DELETE /pricelists, id "53" в 12:15).

**Comment by drcreazy** [comment]
Добрый день. 

В базе не вижу позиции с id 53 для магазина 19175. 
Уточните пожалуйста  еще IP адрес с которого вы шлете запрос. 

Я так понимаю позиция сохраняется в интерфейсе catalog. Если есть возможность при повторении проблемы посмотрите остается ли эта позиция в интерфейсе b2b.

**Comment by NadyaGornostay** [comment]
Я могу вам сообщить информацию об IP в личных сообщениях?

**Comment by NadyaGornostay** [comment]
в прайслисте это позиция samsung Galaxy J8 3GB/32GB (золотистый) в разделе мобильные телефоны

**Comment by drcreazy** [comment]
так, вы отправляете для удаления Galaxy:

DELETE /pricelists
Accept: application/json
["61"]

И он не удаляется?

![image_2021-05-06_15-48-16](https://user-images.githubusercontent.com/3186282/117300895-b3c5d380-ae82-11eb-9455-b4f8324909cd.png)

ip можете сюда скинуть, я прочитаю удалим сразу

**Comment by NadyaGornostay** [comment]
Спасибо за информацию, буду проверять id. я отправляла другой.

**Comment by zoomos-elena** [comment]
Добрый день!
Магазин №6498 «Newton.by»
еще один пример товара, который не отключается 
последний запрос на удаление был отправлен в 16:02
ip = 185.38.166.207
запрос DELETE https://b2bapi.onliner.by/pricelists
https://catalog.onliner.by/heater/termia/evna10230c2m товар активен

просьба срочно проверить

**Comment by sidorovich** [comment]
Посмотрели по логам доступа.
Запросов DELETE на данный домен с указанного IP за текущие сутки не было.
В блокировке указанный IP отсутствует.
Видели от Вас успешные запросы на авторизацию.

**Comment by zoomos-elena** [comment]
подскажите, пожалуйста, а каким образом мы тогда ответ от Вас получили с пустым массивом:

12.05.2021 16:02:19.923
https://b2bapi.onliner.by/pricelists
response code: 202
out length: 2, time = 740 ms, out first chars: [], out last chars: []

**Comment by sidorovich** [comment]
А с какого IP-адреса Вам ответили?

**Comment by sidorovich** [comment]
Были только успешные POST и PATCH с ответами 202... 

185.38.166.207 [12/May/2021:16:02:03 +0300] https "PATCH /pricelists HTTP/1.1" 2052 0.081 202 588 "-" "-" "185.38.166.207" "LT/-" fpm_upstream=- ssl=TLSv1.2
185.38.166.207 [12/May/2021:16:02:08 +0300] https "PATCH /pricelists HTTP/1.1" 2052 0.137 202 588 "-" "-" "185.38.166.207" "LT/-" fpm_upstream=- ssl=TLSv1.2
185.38.166.207 [12/May/2021:16:02:11 +0300] https "POST /pricelists HTTP/1.1" 20502005 4.670 202 460 "-" "Java/1.8.0_232" "ouid=0C817CB27C4F9B60FD4B832A02528C45" "LT/-" fpm_upstream=- ssl=TLSv1.2
185.38.166.207 [12/May/2021:16:02:15 +0300] https "PATCH /pricelists HTTP/1.1" 1560 0.041 202 588 "-" "-" "185.38.166.207" "LT/-" fpm_upstream=- ssl=TLSv1.2
185.38.166.207 [12/May/2021:16:02:19 +0300] https "POST /pricelists HTTP/1.1" 11286306 3.723 202 460 "-" "Java/1.8.0_232" "ouid=0C817CB27C4F9B60FD4B832A02528C45" "LT/-" fpm_upstream=- ssl=TLSv1.2
185.38.166.207 [12/May/2021:16:02:20 +0300] https "POST /pricelists HTTP/1.1" 1562139 0.726 202 254 "-" "Java/1.8.0_232" "ouid=0C817CB27C4F9B60FD4B832A02528C45" "LT/-" fpm_upstream=- ssl=TLSv1.2
185.38.166.207 [12/May/2021:16:02:30 +0300] https "PATCH /pricelists HTTP/1.1" 1674 0.151 202 588 "-" "-" "185.38.166.207" "LT/-" fpm_upstream=- ssl=TLSv1.2
185.38.166.207 [12/May/2021:16:02:58 +0300] https "PATCH /pricelists HTTP/1.1" 4012 0.123 202 588 "-" "-" "185.38.166.207" "LT/-" fpm_upstream=- ssl=TLSv1.2

**Comment by sidorovich** [comment]
Авторизации тоже были. В принципе довольно странно, что разные User-Agent. Это нормально?

185.38.166.207 [12/May/2021:01:16:02 +0300] https "POST /oauth/token HTTP/1.1" 420 0.014 200 386 "-" "Java/1.8.0_232" "ouid=0E817CB227FD9960643D541A021AEA29" "LT/-" fpm_upstream=- ssl=TLSv1.2
185.38.166.207 [12/May/2021:16:02:03 +0300] https "POST /oauth/token HTTP/1.1" 503 0.066 200 547 "-" "-" "185.38.166.207" "LT/-" fpm_upstream=- ssl=TLSv1.2
185.38.166.207 [12/May/2021:16:02:07 +0300] https "POST /oauth/token HTTP/1.1" 503 0.023 200 547 "-" "-" "185.38.166.207" "LT/-" fpm_upstream=- ssl=TLSv1.2
185.38.166.207 [12/May/2021:16:02:15 +0300] https "POST /oauth/token HTTP/1.1" 503 1.025 200 546 "-" "-" "185.38.166.207" "LT/-" fpm_upstream=- ssl=TLSv1.2
185.38.166.207 [12/May/2021:16:02:30 +0300] https "POST /oauth/token HTTP/1.1" 503 0.025 200 545 "-" "-" "185.38.166.207" "LT/-" fpm_upstream=- ssl=TLSv1.2
185.38.166.207 [12/May/2021:16:02:58 +0300] https "POST /oauth/token HTTP/1.1" 503 0.292 200 545 "-" "-" "185.38.166.207" "LT/-" fpm_upstream=- ssl=TLSv1.2

**Comment by zoomos-elena** [comment]
ip 93.185.28.161
отправили сейчас еще один запрос
пожалуйста, проверьте

**Comment by sidorovich** [comment]
смотрим, но время все же лучше передавать точнее, чем сейчас )

**Comment by sidorovich** [comment]
Есть вот такое

93.185.28.161 [12/May/2021:17:53:43 +0300] https "DELETE /pricelists HTTP/1.1" 316 0.052 202 254 "-" "Java/1.8.0_231" "ouid=0C817CB2F1EB9B60FF4BA62D022E3E61" "RU/St Petersburg" fpm_upstream=- ssl=TLSv1.2
93.185.28.161 [12/May/2021:17:55:13 +0300] https "DELETE /pricelists HTTP/1.1" 1563569 1.314 202 254 "-" "Java/1.8.0_231" "ouid=0C817CB24AEC9B60F04BE18A02082F6A" "RU/St Petersburg" fpm_upstream=- ssl=TLSv1.2

**Comment by zoomos-elena** [comment]
да, оно
в списке есть товар на отключение с id 457473
прошло почти полчаса товар так и не пропал

**Comment by sidorovich** [comment]
Значит что-то с телом запроса. 
Не могли бы Вы все же заменить URL на что-то вроде https://requestbin.com/
И залогировать полностью заголовки и тело Вашего запроса.
Данный роут довольно гибкий c точки зрения формата входных параметров и отвечает 202 без валидации.

Еще, к сожалению, 17:51-17:58 был деплой связанных проектов. В теории могли потерять какую-то дополнительную информацию или само сообщение.

Если у Вас есть возможность выполнить CURL-запросы, то могу предложить Вам проверить руками, независимо от Вашего приложения.

Зашифруйте в формате base64 строку c Вашим Client ID и Client Secret (разделенные двоеточием).
Например, используя сервис https://www.base64encode.org/

<img width="1109" alt="Снимок экрана 2021-05-12 в 18 47 45" src="https://user-images.githubusercontent.com/3040359/118004889-8d0c0f00-b352-11eb-97a0-197b3baacaad.png">

Вставьте полученную строку в запрос (вместо %BASE64_CLEINT_ID_AND_SECRET%)  и выполните из командной строки.

```
curl --request POST \
  --url https://b2bapi.onliner.by/oauth/token \
  --header 'Accept: application/json' \
  --header 'Authorization: Basic %BASE64_CLEINT_ID_AND_SECRET%' \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data grant_type=client_credentials
```

В ответ получите авторизационный токен.
Далее можно использовать его в запросе на удаление ценового предложения.

```
curl --request DELETE \
  --url 'https://b2bapi.onliner.by/pricelists?access_token=%YOUR_ACCESS_TOKEN%' \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --data '["457473"]'
  ```

**Comment by sidorovich** [comment]
Если ценовое предложение не удалится и в таком случае, то возможно у нас проблема с обработкой одиночных массивов в содержимом запроса, тогда имеет смысл попробовать роут удаления одиночного ценового предложения с указанием id-предложения непосредственно в самом URL

https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/delete/one.md

**Comment by zoomos-elena** [comment]
Запрос у нас отправляется верный и для одного, например, товара он работает без проблем.
Возможно, у Вас есть ограничение на кол-во?
Cколько будут отключаться 173 тысячи товаров?

**Comment by sidorovich** [comment]
трудно сказать точную цифру. для отключения такого количества товаров эффективнее использовать 
https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/import/replace.md
и просто загрузить новый актуальный прайс-лист, если новый прайс велик, то лучше использовать PUT-PATCH-PATCH... и т.д. разбивая прайс-лист на куски и дожидаясь обработки предыдущего запроса перед отправкой следующего.

антиспам ограничения на API есть, но мы тогда в ответ отдаем 429 и в заголовке Retry-After время до окончания блокировки. Время блокировки вычисляется динамически, максимум - 10 минут.

**Comment by sidorovich** [comment]
Хотелось бы вернуться ко вчерашним логам: вы как-то прояснили ситуацию, что запросы с "RU/St Petersburg" к нам доходили, а предыдущие с "LT/-" нет?

**Comment by zoomos-elena** [comment]
Cегодня уже должны доходить c LT тоже

**Comment by zoomos-elena** [comment]
Добрый день!
проблема остается актуальной
не все товары отключаются по завершении обновлений
пример товара  
Baseus CCTM-01

ответ приходит 
response code: 202
response body: []

время запроса 11:38:26.156

**Comment by zoomos-elena** [comment]
14Q13EA еще один пример, до сих пор товар в продаже

**Comment by sidorovich** [comment]
Вы опять приводите неполные данные. Я просил указывать полное тело запроса - вы не привели его ни разу.
Сейчас вы дали лишь время и название товара, но не указали IP адрес и не указали ID ценового предложения, которое нужно передавать в запросе.
Я не вижу конструктива с Вашей стороны. 

У нас более 2000 активных магазинов, более 250 активно работают с нашим API. Проблема не массовая, значит явно не на нашей стороне. Я не знаю как Вам помочь в поиске проблемы.

**Comment by zoomos-elena** [comment]
Магазин №6498 «Newton.by»
ID:  395283, 691109 есть в последнем списке на удаление

ip = 185.38.166.207

15.05.2021 11:43:17.919

не отключены до сих пор

**Comment by sidorovich** [comment]
На данный момент мы так и не смогли воспроизвести Вашу ситуацию. Запрос Ваш нашли, содержимого нет, но известно, что тело запроса более 1.5 мегабайт. Предполагаем что передаете большое число ценовых предложений.
Единственная гипотеза, которая есть на данный момент, что происходит взаимная блокировка ценовых предложений двумя параллельными запросами. Первый - объемный запрос на удаление большого числа ценовых предложений. Второй - запрос на обновление ценовых предложений по товарам, которые могут быть затронуты в первом запросе. 

Будем изучать ситуацию на следующей неделе подробнее. Если можете как-то подтвердить данную гипотезу, то было бы неплохо. На данный момент можем лишь порекомендовать не отправлять на удаление одним запросом большое количество ценовых предложений. А также рассмотреть вариант перехода работы с API на PUT-PATCH-PATCH..., как я и писал выше. С такими объемами данных, это должно быть эффективнее с точки зрения нагрузки на нашу систему.

**Comment by venompro** [comment]
Добрый день
при использовании запроса PUT будет происходить полное удаление позиций клиента, и только после этого - накатывание актуального списка товаров. Клиенту это не подходит, поскольку между удалением и обновлением - а это 10-15 минут, предложения клиента на Онлайнера будут отсутствовать.
Сейчас используется метод Patch, удаление происходит после выгрузки актуального перечня товаров.

На сегодняшний момент проблема сохраняется. На удаление неактуальных позиций со стороны Онлайнера в утренние часы уходит по 3-5 часов.
Какие варианты решения проблемы видите со своей стороны? с чем связано настолько длительная обработка запросов?

**Comment by sidorovich** [comment]
Вы дожидаетесь завершения обработки всех PATCH запросов или отправляете запросы на удаление сразу же?

Длительная обработка запросов связана с большим объемом данных от всех магазинов и активной одновременной работой с прайс-листами большого числа магазинов.

**Comment by venompro** [comment]
отправляем запросы на удаление сразу же, так как id не пересекаются

**Comment by sidorovich** [comment]
товары пересекаются?

**Comment by venompro** [comment]
id и товары не пересекаются

**Comment by sidorovich** [comment]
ничего внятного не нашли. попробовали уменьшить лимит одновременно удаляемых ценовых предложений в рамках одной транзакции до 1000. теперь вероятность взаимной блокировки значительно уменьшится. вам дорабатывать ничего не нужно. мы на своей стороне после получения запроса просто разбиваем массив данных на куски и разные куски отправляем в очередь на обработку. теперь вместо одной команды будет несколько.

к сожалению проверить на таких объемах мы не можем. попробуйте понаблюдать после обновления за ситуацией.

**Comment by zoomos-elena** [comment]
Добрый день!

Уточните, пожалуйста, как часто генерируется файл с ценами каталога? Сколько обновлений было сегодня, например?

**Comment by Olden** [comment]
@zoomos-elena Добрый день. Как сейчас работает удаление товаров?

**Comment by venompro** [comment]
Добрый день, появилась другая проблема - уже определенные товары не выставляются, хотя в обновлении передаются корректно:
Metabo PowerMaxx BS Basic 600080500 (с 2-мя АКБ 2 Ah) - не выставляется в каталоге у вас
в последнем обновлении товар был, вся информацию по товару корректно указана

**Comment by zoomos-elena** [comment]
Добрый день!

Также не выставляется предложение магазина по товару:
https://catalog.onliner.by/waterheater/edisson/adissones80v/prices
Edisson ER 80 V
В файле обновления также присутствует.

**Comment by zoomos-elena** [comment]
Добрый день!
Магазин №6498 «Newton.by»
Еще один пример товара 
https://catalog.onliner.by/pool_accs/bestway/bw58094/prices
товар был во всех последних файлах обновления, однако то выгружался на площадку и появлялся в продаже, то нет.
Проверьте, пожалуйста, по какой причине не попадает периодически в продажу.

**Comment by zoomos-elena** [comment]
Магазин №6498 «Newton.by»
и снова товар "выпал" из продажи, хотя есть в последнем файле обновления
https://catalog.onliner.by/screwdriver/metabo/powermaxxbsbasic/prices

**Comment by sidorovich** [comment]
В данный момент у нас недостаточно информации для однозначного нахождения проблемы.
Было принято решение доработать систему для фиксирования всех обращений с детальной информацией к нашей системе от имени магазина №6498.

На реализацию, тестирование и доставку на боевой сервер нам потребуется на это несколько дней.
Мы отпишем в тикет, когда доработка будет готова, чтобы вернуться к изучению данной проблемы.

**Comment by sidorovich** [comment]
Запустили систему для логирования менеджмента ценовых предложений.
Пока включили только для магазина 6498. Пока затрудняемся сказать какой объем информации мы сможем себе позволить хранить.

В случае возникновения проблем ждем от вас идентификаторы ценовых предложений и отметки времени когда должна была произойти операция, но не прошла.
