### ISSUE TITLE
Ошибка обновления прайса по API: Неверно указан артикул

### ISSUE THREAD

**Issue by isiter** [onlinerby/onliner-b2b-api#176]
Добрый день. Магазин №19418 «ochnikby» (ochnikby). Пытаюсь по API загрузить прайс-лист из 1C с помощью функции PUT. загружаю json такого вида 
[
{
"category": "Рюкзаки",
"vendor": "OCHNIK S.A.",
"article": "PLCMS-0008-99",
"price": "499",
"currency": "BYN",
"producer": "OCHNIK S.A.",
"importer": "Охник ЧТУП",
"stockStatus": "in_stock",
"isCashless": "нет",
"isCredit": "нет"
}
]
получаю отчет об ошибках. Может я что не так делаю. 
![image](https://user-images.githubusercontent.com/85126602/120223036-9b5e9400-c249-11eb-87dd-28ed895e9eeb.png)

**Comment by sidorovich** [comment]
у нас в базе нет артикула PLCMS-0008-99 можете убедиться сами, используя поиск.
<img width="651" alt="Снимок экрана 2021-06-01 в 10 36 51" src="https://user-images.githubusercontent.com/3040359/120284777-495b5400-c2c5-11eb-912c-7f9bf5c59d78.png">

Вопросы по добавлению артикулов, либо каких либо других данных в каталог вне компетенций технического отдела. Обращайтесь в отдел по работе с каталогом, либо в отдел по работе с клиентами.
