### ISSUE TITLE
При импорте прайс-листа не загружаются данные в Личный кабинет из json

### ISSUE THREAD

**Issue by TatianaHotkina** [onlinerby/onliner-b2b-api#181]
Добрый день. 

В рамках тестирования автоматизации выгрузки прайс-листов для магазина №475, столкнулись со следующей ситуацией:

Шаги:
Дата и время теста: 21.07 16:49

1. выгружаем прайс-лист (метод PUT)
2. получаем следующий ответ
`21.07.21 16:49:35:096	INFO	Response status: 202
Response headers: {Server=[nginx], Content-Type=[application/json], Transfer-Encoding=[chunked], Connection=[keep-alive], Keep-Alive=[timeout=15], Access-Control-Allow-Origin=[*], Cache-Control=[no-cache], Date=[Wed, 21 Jul 2021 13:49:35 GMT], Set-Cookie=[ouid=snyBEGD4Je8A6QGITeUCAg==; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/; httponly; secure]}
Response body: by.velcom.integrations.service.dto.response.ProductOnlinerDtoResponse@58491e7a[id=60f825ef6061ac0ada7f90b2,shopId=475,fileName=price-list-2021-07-21-16-49-35.json,size=894,date=2021-07-21 16:49:35,status=STATUS_WAITING,contentType=json,statusMessage=<null>]`
3. Прайс-лист загружается в личный кабинет. Файл содержит переданные данные (json во вложении)
4. Отчет при этом содержит следующую информацию: 
Отчет об импорте прайс-листа "price-list-2021-07-21-16-49-35.json"
Прайс-лист был распознан как json-файл и обработан 2021-07-21 16:49:35
Успешно импортировано 0 из 0 записей

Просьба помочь разобраться, из-за чего система не видит данных, переданных в json, при этом сам файл содержит информацию о переданных данных. 

Прикрепляю json, который отправляем на onliner
[Hybris-Onliner.json.log](https://github.com/onlinerby/onliner-b2b-api/files/6856943/Hybris-Onliner.json.log)
а также json из личного кабинета по завершению выгрузки. 
[price-list-2021-07-21-16-49-35.txt](https://github.com/onlinerby/onliner-b2b-api/files/6856987/price-list-2021-07-21-16-49-35.txt)

Спасибо.

**Comment by sidorovich** [comment]
<img width="658" alt="Снимок экрана 2021-07-22 в 16 42 57" src="https://user-images.githubusercontent.com/3040359/126649045-af3034c7-bb21-45e4-8a17-a8127f69be19.png">

Некорректно сформировано тело запроса строка ProductOnlinerDto лишняя

**Comment by TatianaHotkina** [comment]
@sidorovich, спасибо. 
Будем править.
