### ISSUE TITLE
При импорте прайс-листа не загружаются данные в Личный кабинет из json

### ISSUE THREAD

**Issue by TatianaHotkina** [onlinerby/onliner-b2b-api#185]
Добрый день.

При тестировании автоматизации выгрузки прайс-листов для магазина №475, столкнулись со следующей ситуацией:

Шаги:
Дата и время теста: 08.09 16:07

выгружаем один продукт (метод PUT)
получаем следующий ответ
`21.09.08 16:07:41:080	INFO	Response status: 202
Response headers: {Server=[nginx], Content-Type=[application/json], Transfer-Encoding=[chunked], Connection=[keep-alive], Keep-Alive=[timeout=15], Access-Control-Allow-Origin=[*], Cache-Control=[no-cache], Date=[Wed, 08 Sep 2021 13:07:40 GMT], Set-Cookie=[ouid=snyBEGE4tZx8rBTHER3aAg==; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/; httponly; secure]}
Response body: by.velcom.integrations.service.dto.response.ProductOnlinerDtoResponse@656e0b29[id=6138b59c0e63ac13ba419032,shopId=475,fileName=price-list-2021-09-08-16-07-40.json,size=793,date=2021-09-08 16:07:40,status=STATUS_WAITING,contentType=json,statusMessage=<null>]
`

Прайс-лист загружается в личный кабинет. Файл содержит переданные данные (json во вложении)
Отчет при этом содержит следующую информацию:

Отчет об импорте прайс-листа "price-list-2021-09-08-16-07-40.json"
Прайс-лист был распознан как json-файл и обработан 2021-09-08 16:07:40
Успешно импортировано 0 из 0 записей
Просьба помочь разобраться, из-за чего система не видит данных, переданных в json, при этом сам файл содержит информацию о переданных данных.
Ошибки в json, которые были сделаны ранее https://github.com/onlinerby/onliner-b2b-api/issues/181 исправлены

Прикрепляю json, который отправляем на onliner
[Hybris-Onliner.json.log](https://github.com/onlinerby/onliner-b2b-api/files/7129297/Hybris-Onliner.json.log)

а также json из личного кабинета по завершению выгрузки.
https://b2b.onliner.by/pricelists/6138b59c0e63ac13ba419032/download

Спасибо.

**Comment by sidorovich** [comment]
Попробуйте запросить отчет об ошибках, используя метод https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/import/report.md

На вашем содержимом мы получили ошибки:

```json
"errors": {
      "producer": [
        {
          "code": "MUST_NOT_BE_BLANK",
          "message": "поле является обязательным"
        }
      ],
      "importer": [
        {
          "code": "MUST_NOT_BE_BLANK",
          "message": "поле является обязательным"
        }
      ]
    }
```

в личном кабинете отображаются вот так:

![photo_2021-09-08 17 21 36](https://user-images.githubusercontent.com/3040359/132527205-3c6d1c48-63f7-4042-bbcd-cfd0ecdf10e9.jpeg)

**Comment by TatianaHotkina** [comment]
@sidorovich , Павел, спасибо огромное.
