### ISSUE TITLE
Анализ ошибок при импорте прайс-листа

### ISSUE THREAD

**Issue by persey86** [onlinerby/onliner-b2b-api#186]
Доброго времени суток! 
Сегодня мы делали выгрузку прайс-листов по магазину №475 2021-09-10 11:14:43, но в отчете на стороне onliner было следующее: "Отчет об импорте прайс-листа "price-list-2021-09-10-11-14-43.json"
Прайс-лист был распознан как json-файл и обработан 2021-09-10 11:14:43
Успешно импортировано 0 из 0 записей". 
При запросе отчета по импорту возвращает пустой массив. 
![99999](https://user-images.githubusercontent.com/20542271/132827675-de755e06-1e86-4b8c-939e-d3ce2ce949b8.png)

@sidorovich  подскажите, как можно посмотреть сделать корректно запрос отчета об ошибках (в продолжение #185)

**Comment by sidorovich** [comment]
лучше пришлите содержимое прайс-листа

**Comment by persey86** [comment]
https://b2b.onliner.by/pricelists/613b13f30e63acb70e3b9c62/download

**Comment by sidorovich** [comment]
ох.
так просто я его не получу.
попробуем

**Comment by persey86** [comment]
Сейчас файл скину

**Comment by persey86** [comment]
[sentToOnliner.log](https://github.com/onlinerby/onliner-b2b-api/files/7142608/sentToOnliner.log)
Это мы отправили
[responceFromOnliner.txt](https://github.com/onlinerby/onliner-b2b-api/files/7142630/responceFromOnliner.txt)
Это получили как ответ из Onliner

**Comment by sidorovich** [comment]
<img width="743" alt="Снимок экрана 2021-09-10 в 12 12 18" src="https://user-images.githubusercontent.com/3040359/132830560-05762440-71d2-46ea-994b-d2537fb7b5f4.png">

вижу разницу в квадратных скобках в реальном прайсе и в том, что вы прислали
уточняем, но вы на своей стороне тоже уточните содержимое
возможно квадратные скобки добавляются только в логи, а не отправляются как содержимое

мы ожидаем массив ценовых предложений в данном роуте

**Comment by persey86** [comment]
Да, все верно, квадратные скобки мы добавляем только для логирования

**Comment by sidorovich** [comment]
добавляйте в тело запроса, с ними у нас все прошло

мы ждем массив объектов, а не объект

**Comment by persey86** [comment]
Правильно я понял, что ошибка в том, что нужно еще дополнительно body обернуть [...] ?

**Comment by sidorovich** [comment]
да, это позволит вам отправлять более одного объекта в запросе, если соблюдать JSON синтаксис

**Comment by sidorovich** [comment]
на всякий случай предупреждаю, что авторизационные заголовки здесь и в предыдущей задаче компрометируют ваш доступ к API
порекомендовал бы вам после решения проблемы или сменить реквизиты доступа в личном кабинете, или удалить данную информацию из нашей коммуникации.

надежнее первый вариант.
скажите, как вам удобнее?

**Comment by persey86** [comment]
ОК, я удалю

**Comment by persey86** [comment]
@sidorovich можете написать свой скайп на почту kost9937@gmail.com

**Comment by sidorovich** [comment]
нет, вся коммуникация по поддержке только через гитхаб
личные контакты не предусмотрены

**Comment by persey86** [comment]
Можете предоставить контракт данного API, мы следуем данному контракту, но изменений нету:
![000000000000](https://user-images.githubusercontent.com/20542271/132833696-8056c512-0bdc-48c9-acee-08c87d0108a8.png)

**Comment by sidorovich** [comment]
у нас отложенная обработка прайс-листов. изменения применяются не сиюминутно - возможна очередь.
для уточнения деталей процесса используйте соответствующие роуты в API
каждый прайс-лист имеет свой идентификатор

в каком виде вы хотели бы видеть контракт API?
если примеры, которые для вас комфортны?

у нас несколько сотен магазинов работает по API - мы физически не можем поддерживать документацию, которая устраивала бы всех. :(

**Comment by persey86** [comment]
![1111111111111](https://user-images.githubusercontent.com/20542271/132837416-5ef5a6d6-8e2b-4f09-a399-d2b5c52272f1.png)
Можете предоставить список валидных разделов (категорий), которые мы можем использовать?

**Comment by sidorovich** [comment]
https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/catalog/sections.md

**Comment by persey86** [comment]
Добрый день @sidorovich ! Мы делали сегодня выгрузку прайс-листов, но все-равно присутствует ошибка
![222](https://user-images.githubusercontent.com/20542271/133043399-8fa8754f-9bd3-4319-8e79-712f82c9bf7d.png)
Подскажите, что не так?
Вот оригинал отправляемого документа:
![555](https://user-images.githubusercontent.com/20542271/133043952-111f1e89-0537-4545-a76e-c76f34c35a90.png)

**Comment by sidorovich** [comment]
"category": "Мобильные телефоны"

нужно указывать строковое название раздела

**Comment by persey86** [comment]
Я отправил такой запрос тоже 2 минутами ранее, но ошибка не поменялась

**Comment by sidorovich** [comment]
покажите тело запроса.

**Comment by persey86** [comment]
Сделал повторную отправку:
[price-list-2021-09-13-10-46-58.txt](https://github.com/onlinerby/onliner-b2b-api/files/7152452/price-list-2021-09-13-10-46-58.txt)

**Comment by sidorovich** [comment]
судя по скобкам вижу у вас структуру "массив, массив, объект", попробуйте слать "массив, объект"
<img width="345" alt="Снимок экрана 2021-09-13 в 10 49 39" src="https://user-images.githubusercontent.com/3040359/133044640-b7d3cb08-5efa-4287-b26c-d2dddaa22990.png">
[price-list-2021-09-13-10-46-58-fixed.txt](https://github.com/onlinerby/onliner-b2b-api/files/7152457/price-list-2021-09-13-10-46-58-fixed.txt)

**Comment by persey86** [comment]
![model_2021-09-13_10-54-09](https://user-images.githubusercontent.com/20542271/133045315-f900521f-5b95-4745-a836-0f59071f9bf0.png)
Где можно посмотреть разрешенные модели товаров и артикулы?

**Comment by sidorovich** [comment]
Информация о наших товарах доступна в файле со структурой каталога. На странице "Импорт Экспорт" в админке есть ссылка "Структура каталога Onliner (xml)".
Файл довольно большой. Обновляется раз в сутки, ночью.

Какое нужно задавать ID-позиции - технические требования описаны в тексте с ошибкой. ID-позиции должны быть уникальные в рамках вашего магазина. Выбирайте любой удобный для вас механизм для идентификации позиций.

**Comment by persey86** [comment]
@sidorovich ,все с выгрузкой получилось, спасибо!
Можно как-то посмотреть в админке операцию удаления по конкретному продукту?

**Comment by sidorovich** [comment]
![2021-09-13 12 42 45](https://user-images.githubusercontent.com/3040359/133062015-294e2fd9-9ce7-44ef-b48f-512b347e1d09.jpg)

Установка стоимости 0.0 также скрывает ценовое предложение от покупателей.

**Comment by persey86** [comment]
Доброго времени суток!
Сегодня мы делали обновление позиции из прайс-листа по магазину №475, но получили ошибку со стороны Онлайнера
"Failed to send update product request
 org.springframework.web.client.ResourceAccessException: I/O error on PATCH request for "https://b2bapi.onliner.by/pricelists": Invalid HTTP method: PATCH; nested exception is java.net.ProtocolException: Invalid HTTP method: PATCH"
 @sidorovich, можете подсказать в чем ошибка?

**Comment by sidorovich** [comment]
похоже на ошибку в библиотеке на вашей стороне.
поиск выводит на такую штуку
https://stackoverflow.com/questions/25163131/httpurlconnection-invalid-http-method-patch

**Comment by persey86** [comment]
Доброго времени суток @sidorovich! Во время импорта продуктов на некоторых возникла ошибка уникальности цены. Подскажите, на основе каких данных можно проверять уникальность цены?
![7777777](https://user-images.githubusercontent.com/20542271/135281725-dee4e699-594e-4a71-91b3-de569cf7fec8.png)

**Comment by sidorovich** [comment]
такая ошибка возможна, если у вас несколько ценовых предложений на один товар
стоимость должна быть уникальной в рамках одного товара.

**Comment by persey86** [comment]
Есть-ли какая-то API на получение "Модели", "Артикула" продукта по ID-товара?

**Comment by sidorovich** [comment]
К сожалению, в данный момент нет.
Единственный способ -  XML-файл со структурой каталога, о котором я писал выше https://github.com/onlinerby/onliner-b2b-api/issues/186#issuecomment-917938485

**Comment by persey86** [comment]
> такая ошибка возможна, если у вас несколько ценовых предложений на один товар стоимость должна быть уникальной в рамках одного товара.

Как может срабатывать ошибка на уникальность, если мы товар грузим списком через метод PUT ?
Например, вот этот:
{"id":"1860338001",
"category":
"Чехлы для телефонов",
"vendor":"Samsung",
"model":"для Galaxy A51 (винный)",
"article":"GP-FPA515WSAXR",
"price":"20.0",
"currency":"BYN",
"comment":"Возможна рассрочка на 6 и 11 мес. для абонентов тарифных планов A1. Удобный способ погашения платежей с баланса абонента. Широкий ассортимент аксессуаров в рассрочку до 24 мес.",
"producer":"«WITS Co. Ltd», 101-1412, 88, Синво-ро, Енгтонг-гу, г. Сувон, Кёнги-до, Республика Корея",
"importer":"Унитарное предприятие по оказанию услуг А1, 220030, Республика Беларусь, г.Минск, ул. Интернациональная, 36-2",
"serviceCenters":"СООО \"Кенфордбел\", г. Минск, ул. Толбухина, 2",
"warranty":"14 day(s)",
"deliveryTownTime":2,
"deliveryCountryTime":5,
"productLifeTime":0,
"isCashless":"нет",
"isCredit":"нет",
"stockStatus":"in_stock"}

**Comment by persey86** [comment]
> > такая ошибка возможна, если у вас несколько ценовых предложений на один товар стоимость должна быть уникальной в рамках одного товара.
> 
> Как может срабатывать ошибка на уникальность, если мы товар грузим списком через метод PUT ? Например, вот этот: {"id":"1860338001", "category": "Чехлы для телефонов", "vendor":"Samsung", "model":"для Galaxy A51 (винный)", "article":"GP-FPA515WSAXR", "price":"20.0", "currency":"BYN", "comment":"Возможна рассрочка на 6 и 11 мес. для абонентов тарифных планов A1. Удобный способ погашения платежей с баланса абонента. Широкий ассортимент аксессуаров в рассрочку до 24 мес.", "producer":"«WITS Co. Ltd», 101-1412, 88, Синво-ро, Енгтонг-гу, г. Сувон, Кёнги-до, Республика Корея", "importer":"Унитарное предприятие по оказанию услуг А1, 220030, Республика Беларусь, г.Минск, ул. Интернациональная, 36-2", "serviceCenters":"СООО "Кенфордбел", г. Минск, ул. Толбухина, 2", "warranty":"14 day(s)", "deliveryTownTime":2, "deliveryCountryTime":5, "productLifeTime":0, "isCashless":"нет", "isCredit":"нет", "stockStatus":"in_stock"}

Я правильно понял
