### ISSUE TITLE
ERROR_MODEL_NOT_FOUND

### ISSUE THREAD

**Issue by TiEdamn** [onlinerby/onliner-b2b-api#188]
Добрый день

При выгрузке прайсов через API на некоторые товары получаем ошибку **ERROR_MODEL_NOT_FOUND**

**Шаги воспроизведения:**
1. Получаем список товаров через метод **GET /positions**
2. Сопоставляем с нашим каталогом каждый элемент и заполняем цену
3. Отправляем заполненный объект методом **PATCH /pricelists**
4. При просмотре отчета о выгрузке по некоторым товарам из разных категорий получаем ошибку **ERROR_MODEL_NOT_FOUND**, хотя поле модель не редактируем, а передаем модель полученную в пункте 1.

`
[
    {
        "category": "Письменные и компьютерные столы"
        "vendor": "MFMaster"
        "model": "Арто-25 (венге)"
        "article": null
        "id": "1812355001"
        "price": "64.00"
        "currency": "BYN"
        "comment": "Широкий ассортимент письменных и компьютерных столов. Возможна оплата по безналичному расчету или через карты рассрочек. Квалифицированная консультация."
        "producer": "Мебельная фабрика «Мастер», Окружной пр-д, д. 3, г. Фрязино, Московская обл., РФ"
        "importer": "ООО "Жемчужина кухни",г. Минск, ул. Зм.Бядули, 3-7"
        "serviceCenters": "ООО "Жемчужина кухни",г. Минск, ул. Зм.Бядули, 3-7"
        "warranty": "24"
        "deliveryTownTime": "1"
        "deliveryCountryTime": "3"
        "productLifeTime": null
        "isCashless": "нет"
        "isCredit": "нет"
        "stockStatus": ""
        "termHalva": ""
        "priceHalva": "0.00"
        "courierDeliveryPrices": []
    }
]
`

И вот что выдает при просмотре статуса выгрузки
`
"errors": {
    "model": [
        {
            "code": "ERROR_MODEL_NOT_FOUND"
            "message": "Неверно указана или не указана модель товара"
        }
    ]
}
`

**Comment by sidorovich** [comment]
У вас в примере некорректный JSON, нет запятых между свойствами объекта.
Можно получить пример полного корректного запроса для воспроизведения проблемы?

**Comment by TiEdamn** [comment]
> У вас в примере некорректный JSON, нет запятых между свойствами объекта. Можно получить пример полного корректного запроса для воспроизведения проблемы?

Прошу прощения, это встроенный в фреймворк дебаггер так отформатировал

`[
	{
	"category": "Письменные и компьютерные столы",
	"vendor": "MFMaster",
	"model": "Арто-25 (венге)",
	"article": null,
	"id": "1812355001",
	"price": "64.00",
	"currency": "BYN",
	"comment": "Широкий ассортимент письменных и компьютерных столов. Возможна оплата по безналичному расчету или через карты рассрочек. Квалифицированная консультация. Доставка в удобное для Вас время и место. Приятных покупок.",
	"producer": "Мебельная фабрика «Мастер», Окружной пр-д, д. 3, г. Фрязино, Московская обл., РФ",
	"importer": "ООО \"Жемчужина кухни\",г. Минск, ул. Зм.Бядули, 3-7",
	"serviceCenters": "ООО \"Жемчужина кухни\",г. Минск, ул. Зм.Бядули, 3-7",
	"warranty": "24",
	"deliveryTownTime": "1",
	"deliveryCountryTime": "3",
	"productLifeTime": null,
	"isCashless": "нет",
	"isCredit": "нет",
	"stockStatus": "",
	"termHalva": "",
	"priceHalva": "0.00",
	"courierDeliveryPrices": {}
	}
]`

**Comment by sidorovich** [comment]
Спасибо, проверяем.

**Comment by sidorovich** [comment]
Товар находится в другом разделе
![image_2021-11-04_11-21-08](https://user-images.githubusercontent.com/3040359/140281323-32b39185-3779-4249-ae00-f3d8f41df7cf.png)
![image_2021-11-04_11-20-57](https://user-images.githubusercontent.com/3040359/140281332-f3378595-6dc3-4b84-a0e0-c159cbfd6a2c.png)

**Comment by TiEdamn** [comment]
А можно как-то сделать, чтобы этот товар не возвращался в методе 
**GET /sections/{sectionId}/positions** и **GET /sections/{sectionId}/manufacturers/{manufacturerId}/positions**

где {sectionId} - 534 (Письменные и компьютерные столы)
{manufacturerId} - 16243 (MFMaster)

**Comment by sidorovich** [comment]
Удалите данную позицию. Мы возвращаем информацию о ценовых предложениях, которые у нас есть. Данное ценовое предложение было Вами привязано к данному разделу, поэтому оно возвращается.

У нас есть механизм переноса ценовых предложений в случае изменения раздела или производителя у товара в каталоге, но в данном случае, вероятно, произошел какой-то сбой. 

В справочной информации по данному разделу и производителю этот товар не передается
https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/catalog/products.md

В данном случае, проще всего Вам будет обновить весь прайс-лист используя метод PUT https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/import/replace.md

**Comment by TiEdamn** [comment]
Понял, спасибо большое!
