### ISSUE TITLE
Десятичная точность цен через API

### ISSUE THREAD

**Issue by michael-borisov** [onlinerby/onliner-b2b-api#19]
Метод https://b2bapi.onliner.by/positions отдает цены BYN с округлением. Например в каталоге отображается цена 2861,72, но через API цена 2861.70

**Comment by ptrofimov** [comment]
Округления нет, я проверил. Вы уверены, что на странице каталога смотрите ту же самую позицию? Кроме того, на публичных страницах новая цена может обновляться с задержкой.

**Comment by michael-borisov** [comment]
@ptrofimov да, смотрел одну и ту же позицию, но скорее всего она была изменена и обновлялась с задержкой на публичных страницах. Спасибо!
