### ISSUE TITLE
Вопрос по прайсу и сервисным центрам

### ISSUE THREAD

**Issue by Protos-s** [onlinerby/onliner-b2b-api#190]
При выгрузке нового прайса по некоторым позициям получаем статус "Сервисные центры: поле является обязательным".
Как заранее определить товары (разделы), для которых поле 'Сервисный центр' является обязательным?

**Comment by sidorovich** [comment]
Боюсь, что на данный момент механизма для этого нет и мы первый раз сталкиваемся с подобным запросом.
Вероятно, это как-то регулируется нашим законодательством. У нас данная настройка управляется операторами каталога и я не могу вам сказать строгих правил так как не знаю их.

Могу лишь предоставить выгрузку с названиями разделов, которые требуют на данный момент заполнения этого поля.

| Аэрогрили и аэрофритюрницы                                                                                    |
| Тепловые завесы                                                                                               |
| Очистители и мойки воздуха                                                                                    |
| Угловые шлифмашины (болгарки)                                                                                 |
| Автохолодильники, термобоксы, термосумки                                                                      |
| Аудиоинтерфейсы                                                                                               |
| Радионяни и видеоняни                                                                                         |
| Детские весы                                                                                                  |
| Сканеры штрих-кодов                                                                                           |
| Банные печи                                                                                                   |
| Ванны                                                                                                         |
| Автомобильные велобагажники                                                                                   |
| Велосипеды                                                                                                    |
| Брошюровщики                                                                                                  |
| Блендеры                                                                                                      |
| Вентиляторы и охладители воздуха                                                                              |
| Отопительные котлы                                                                                            |
| Подогреватели и стерилизаторы                                                                                 |
| Хлебопечки                                                                                                    |
| Алкотестеры                                                                                                   |
| Bluetooth-гарнитуры                                                                                           |
| Автосигнализации                                                                                              |
| Автомобильные усилители                                                                                       |
| Автомагнитолы                                                                                                 |
| Карт-ридеры                                                                                                   |
| Домкраты                                                                                                      |
| Автоакустика                                                                                                  |
| Автомобильные инверторы                                                                                       |
| Автомобильные багажники                                                                                       |
| Автомобильные радиостанции CB                                                                                 |
| Автомобильные пылесосы                                                                                        |
| Кассовые аппараты и платежные терминалы                                                                       |
| Камеры CCTV                                                                                                   |
| Электро- и бензопилы                                                                                          |
| Корпуса                                                                                                       |
| Автокресла                                                                                                    |
| Настенные и настольные часы                                                                                   |
| Кофеварки и кофемашины                                                                                        |
| Кофемолки                                                                                                     |
| Торговые холодильники                                                                                         |
| Компрессоры                                                                                                   |
| Автомобильные компрессоры                                                                                     |
| Концертная акустика                                                                                           |
| Бетономешалки                                                                                                 |
| Кондиционеры                                                                                                  |
| Игровые приставки                                                                                             |
| Игровые контроллеры и аксессуары                                                                              |
| Кухонные плиты                                                                                                |
| Счетчики банкнот и монет                                                                                      |
| Процессоры                                                                                                    |
| Детекторы валют                                                                                               |
| Радиотелефоны DECT                                                                                            |
| Компьютеры                                                                                                    |
| Предпусковые подогреватели двигателя и топливной системы                                                      |
| Посудомоечные машины                                                                                          |
| Мониторы                                                                                                      |
| Оперативная память                                                                                            |
| Электродрели и строительные миксеры                                                                           |
| DSL-модемы и маршрутизаторы                                                                                   |
| DVD плееры                                                                                                    |
| Электронные книги                                                                                             |
| Яйцеварки                                                                                                     |
| Детские электромобили                                                                                         |
| Электропилы                                                                                                   |
| Эллиптические тренажеры                                                                                       |
| Внешние накопители                                                                                            |
| Огнетушители                                                                                                  |
| Системы охлаждения                                                                                            |
| Факсы                                                                                                         |
| Вспышки и лампы                                                                                               |
| FM-модуляторы                                                                                                 |
| Кухонные комбайны, машины и планетарные миксеры                                                               |
| Сушилки для овощей и фруктов                                                                                  |
| Гидромассажные ванночки для ног                                                                               |
| Электролобзики                                                                                                |
| Фритюрницы                                                                                                    |
| Сейфы                                                                                                         |
| Глюкометры                                                                                                    |
| GPS-навигаторы                                                                                                |
| GPS-трекеры                                                                                                   |
| Шлифмашины                                                                                                    |
| Гитарные комбоусилители                                                                                       |
| Машинки для стрижки волос                                                                                     |
| Фены                                                                                                          |
| Жесткие диски                                                                                                 |
| Боксы для накопителей                                                                                         |
| Наушники и гарнитуры                                                                                          |
| Обогреватели                                                                                                  |
| Тепловые пушки                                                                                                |
| Кусторезы и садовые ножницы                                                                                   |
| Музыкальные центры, колонки для вечеринок (Partybox)                                                          |
| Hi-Fi акустика                                                                                                |
| Варочные панели                                                                                               |
| Вытяжки                                                                                                       |
| Промышленные фены                                                                                             |
| Надувные лодки                                                                                                |
| Ингаляторы                                                                                                    |
| Уничтожители насекомых, отпугиватели, ловушки                                                                 |
| IP-камеры                                                                                                     |
| Утюги                                                                                                         |
| Соковыжималки                                                                                                 |
| Электрочайники и термопоты                                                                                    |
| Самокаты                                                                                                      |
| Детские велосипеды                                                                                            |
| Кухонные весы                                                                                                 |
| Женские электробритвы и эпиляторы                                                                             |
| Ламинаторы                                                                                                    |
| Подставки для ноутбуков, телефонов, планшетов                                                                 |
| Воздуходувки                                                                                                  |
| Объективы                                                                                                     |
| Фонари                                                                                                        |
| Машинки для удаления катышков                                                                                 |
| Маринаторы                                                                                                    |
| Массажеры и массажные кресла                                                                                  |
| Матричные принтеры                                                                                            |
| Мясорубки                                                                                                     |
| Медиаплееры и ТВ-приставки                                                                                    |
| Медицинские термометры                                                                                        |
| Метеостанции, гигрометры и термогигрометры                                                                    |
| Микрофоны                                                                                                     |
| Микроволновые печи                                                                                            |
| Ручные миксеры                                                                                                |
| Мобильные телефоны                                                                                            |
| Моноблоки                                                                                                     |
| Материнские платы                                                                                             |
| Мотоблоки и мотокультиваторы                                                                                  |
| Мыши                                                                                                          |
| Газонокосилки                                                                                                 |
| Мультиварки                                                                                                   |
| Сетевые накопители (NAS)                                                                                      |
| Сетевые адаптеры                                                                                              |
| Ноутбуки                                                                                                      |
| Офисные кресла и стулья                                                                                       |
| Бинокли, подзорные трубы и приборы ночного видения                                                            |
| Оптические приводы                                                                                            |
| Лодочные моторы                                                                                               |
| Духовые шкафы                                                                                                 |
| Оверлоки и распошивальные машины                                                                              |
| Парковочные радары и камеры заднего вида                                                                      |
| Проводные телефоны                                                                                            |
| Фотоаппараты                                                                                                  |
| Цифровые фоторамки                                                                                            |
| Рубанки                                                                                                       |
| Плееры                                                                                                        |
| Портативные зарядные устройства                                                                               |
| Портативные DVD-плееры и телевизоры                                                                           |
| Магнитолы                                                                                                     |
| Сети по электропроводке (Powerline)                                                                           |
| Генераторы                                                                                                    |
| Детские коляски и аксессуары                                                                                  |
| Принтеры и МФУ                                                                                                |
| Проекторы                                                                                                     |
| Насосы                                                                                                        |
| Квадроциклы                                                                                                   |
| Радар-детекторы                                                                                               |
| Радиоприемники                                                                                                |
| AV-ресиверы и усилители                                                                                       |
| Холодильники                                                                                                  |
| Универсальные пульты ДУ                                                                                       |
| Перфораторы                                                                                                   |
| Гребные тренажеры                                                                                             |
| Сэндвичницы                                                                                                   |
| Спутниковые ресиверы                                                                                          |
| Напольные весы                                                                                                |
| Скутеры и мопеды                                                                                              |
| Шуруповерты, гайковерты, электроотвертки                                                                      |
| Швейные машины                                                                                                |
| Электробритвы мужские                                                                                         |
| Душевые кабины                                                                                                |
| Шредеры                                                                                                       |
| Лыжи                                                                                                          |
| Ломтерезки                                                                                                    |
| Электронные парогенераторы                                                                                    |
| Снегоуборщики                                                                                                 |
| Мультимедиа акустика                                                                                          |
| Звуковые карты                                                                                                |
| Док-станции для смартфонов                                                                                    |
| Пуско-зарядные устройства                                                                                     |
| Пароочистители и отпариватели                                                                                 |
| Пароварки                                                                                                     |
| Дровяные камины, печи-камины, порталы                                                                         |
| Студийные мониторы                                                                                            |
| Стайлеры                                                                                                      |
| Электровеники                                                                                                 |
| Коммутаторы                                                                                                   |
| Синтезаторы и рабочие станции                                                                                 |
| Настольные плиты                                                                                              |
| Планшеты                                                                                                      |
| Графические планшеты                                                                                          |
| Телескопы                                                                                                     |
| Приемники цифрового ТВ                                                                                        |
| Принтеры чеков и этикеток                                                                                     |
| Терморегуляторы                                                                                               |
| Тостеры                                                                                                       |
| Тонометры                                                                                                     |
| Электрические зубные щетки и ирригаторы                                                                       |
| Туристические навигаторы                                                                                      |
| Беговые дорожки                                                                                               |
| Триммеры                                                                                                      |
| Штативы и стабилизаторы для фото-, видео- и световой техники                                                  |
| Телевизоры                                                                                                    |
| ТВ-тюнеры и карты видеозахвата                                                                                |
| Источники бесперебойного питания                                                                              |
| Пылесосы                                                                                                      |
| Велотренажеры                                                                                                 |
| Видеокамеры                                                                                                   |
| Видеокарты                                                                                                    |
| Автомобильные видеорегистраторы                                                                               |
| Диктофоны                                                                                                     |
| Стабилизаторы, сетевые фильтры, удлинители                                                                    |
| Вафельницы                                                                                                    |
| Мойки высокого давления                                                                                       |
| Стиральные машины                                                                                             |
| Наручные часы                                                                                                 |
| Фильтры и системы для очистки воды                                                                            |
| Водонагреватели                                                                                               |
| Кулеры для воды                                                                                               |
| Веб-камеры                                                                                                    |
| Сварочные инверторы                                                                                           |
| Винные шкафы                                                                                                  |
| Беспроводные адаптеры                                                                                         |
| Беспроводные точки доступа и усилители Wi-Fi                                                                  |
| Фрезеры                                                                                                       |
| Беспроводные маршрутизаторы                                                                                   |
| Йогуртницы                                                                                                    |
| Видеодомофоны                                                                                                 |
| Клавиатуры                                                                                                    |
| Наборы периферии                                                                                              |
| Блоки питания                                                                                                 |
| Умные часы и браслеты                                                                                         |
| Лазерные нивелиры                                                                                             |
| Лазерные дальномеры                                                                                           |
| Металлические двери                                                                                           |
| Окна ПВХ                                                                                                      |
| Экшен-камеры                                                                                                  |
| Мини-печи (ростеры)                                                                                           |
| Роботы-пылесосы                                                                                               |
| Блинницы                                                                                                      |
| Измельчители (чопперы)                                                                                        |
| Диваны                                                                                                        |
| Увлажнители воздуха                                                                                           |
| Портативные радиостанции                                                                                      |
| Осушители воздуха                                                                                             |
| Пневматические краскопульты                                                                                   |
| Пневматические гайковерты                                                                                     |
| Штроборезы                                                                                                    |
| Мини-тракторы                                                                                                 |
| Электро- и бензорезы                                                                                          |
| Садовые измельчители                                                                                          |
| Электрогрили                                                                                                  |
| Проекционные экраны                                                                                           |
| Заточные станки (точила)                                                                                      |
| Граверы                                                                                                       |
| Виброплиты и вибротрамбовки                                                                                   |
| Видеорегистраторы наблюдения                                                                                  |
| Кровати                                                                                                       |
| SSD                                                                                                           |
| Подъемники                                                                                                    |
| Пневмошлифмашины                                                                                              |
| Беспроводные и портативные колонки                                                                            |
| Усилители для наушников                                                                                       |
| Велокомпьютеры                                                                                                |
| Электрокамины и биокамины                                                                                     |
| Мотоциклы                                                                                                     |
| Двигатели                                                                                                     |
| Биотуалеты                                                                                                    |
| Деревообрабатывающие и металлообрабатывающие станки                                                           |
| Отбойные молотки                                                                                              |
| USB-хабы и док-станции                                                                                        |
| Электрические краскораспылители                                                                               |
| Степперы                                                                                                      |
| Плиткорезы                                                                                                    |
| Сушилки для рук, волос                                                                                        |
| Гироциклы                                                                                                     |
| Информационные панели                                                                                         |
| Резаки для бумаги                                                                                             |
| Вспениватели молока                                                                                           |
| Электрошашлычницы                                                                                             |
| Интерьерные часы                                                                                              |
| Эхолоты                                                                                                       |
| Вакуумные упаковщики                                                                                          |
| Вытяжная и приточная вентиляция                                                                               |
| Навесное оборудование для садовой техники                                                                     |
| Зарядные устройства                                                                                           |
| Паяльники и паяльные лампы                                                                                    |
| Гидроаккумуляторы и расширительные баки                                                                       |
| Дровоколы                                                                                                     |
| Мотопомпы                                                                                                     |
| Виниловые проигрыватели                                                                                       |
| Фонокорректоры                                                                                                |
| Инсталляции для унитазов, раковин, биде и писсуаров                                                           |
| Душевые поддоны                                                                                               |
| 3D-принтеры                                                                                                   |
| Термоклеевые пистолеты                                                                                        |
| Скобозабиватели, гвоздезабиватели, степлеры                                                                   |
| Электрические ножницы по металлу                                                                              |
| Электросамокаты и электроскутеры                                                                              |
| Аккумуляторы и зарядные устройства для инструмента                                                            |
| Умный дом                                                                                                     |

**Comment by Protos-s** [comment]
список разделов подойдёт, спасибо
