### ISSUE TITLE
Массовое создание ПВЗ

### ISSUE THREAD

**Issue by Haletsdz** [onlinerby/onliner-b2b-api#191]
На данный момент не реально создать большое количество ПВЗ. Процесс занимает очень долгое время, если вручную все ПВЗ добавлять, а их более 230!!!
Прошу оперативно предоставить возможность делать массовую загрузку ПВЗ владельцам магазина или по запросу магазина в технический отдел разработки Онлайнера по необходимому шаблону импорта csv или xml.

**Comment by sidorovich** [comment]
Добрый день!

На данный момент у нас нет возможности автоматизировать этот процесс, но если вы обратитесь в отдел по работе с клиентами и предоставите таблицу с полным набором информации, необходимым для создания ПВЗ, то мы постараемся как-то их загрузить в нашу систему.

Формат CSV-будет более чем подходящим. Можете завести колонки исходя из полей формы на нашем сайте. И не забудьте указать координаты (широту и долготу в разных колонках). 

Обязательно обеспечьте единый формат во всех строках - чтобы максимально избежать ручной правки вашего файла нашими специалистами.

**Comment by Haletsdz** [comment]
Огромное спасибо за оперативность и помощь! Все выполнено в короткие сроки!
Огромное спасибо Евгению @EHonliner , а также Павлу @sidorovich . Ребята реально клиентоориентированные и помогают клиенту по всем вопросам.
