### ISSUE TITLE
Получение информации о ценах конкурентов

### ISSUE THREAD

**Issue by kashapov** [onlinerby/onliner-b2b-api#23]
Можно ли как то получить информацию о ценах на конкретный товар в других магазинах?

**Comment by Olden** [comment]
на странице http://b2b.onliner.by/pricelists вашего магазина есть две ссылки:
- Все цены каталога
- Цены конкурентов на товары магазина

**Comment by kashapov** [comment]
а через API нельзя?

**Comment by Olden** [comment]
нет
