### ISSUE TITLE
JSON кавычки

### ISSUE THREAD

**Issue by kashapov** [onlinerby/onliner-b2b-api#25]
как передавать модель товара где используются одинарные кавычки?
пример:
[MacBook Pro 15'' Retina (MJLQ2)](https://catalog.onliner.by/notebook/apple/mjlq2)
- при addslashes выдает ошибку валидации файла
- при htmlspecialchars в отчете пишет "Неверно указана или не указана модель товара"

варианты не подходят:
"model":"MacBook Pro 15'' Retina (MJLQ2)",
"model":"MacBook Pro 15\'\' Retina (MJLQ2)",
`"model":"MacBook Pro 15&#039;&#039; Retina (MJLQ2)",`

**Comment by Olden** [comment]
прикрепите пожалуйста файлом или текстом что у вы нам шлете после addslashes и вам выдает ошибку валидации

**Comment by kashapov** [comment]
после htmlspecialchars получается
`,"model":"MacBook Pro 15&#039;&#039; Retina (MJLQ2)",`
и в отчете пишет "Неверно указана или не указана модель товара"

**Comment by Olden** [comment]
интересует конкретный пример с addslashes и непройденной валидацией

**Comment by kashapov** [comment]
[скачать файл](https://drive.google.com/file/d/0B4K9nLTgggrwV0dYVFA3YkVMT0k/view?usp=sharing)

**Comment by Olden** [comment]
@kashapov конкретно эту проблему исправили, но в файле есть еще другие невалидные позиции.

**Comment by ptrofimov** [comment]
Вариант
```
"model":"MacBook Pro 15\'\' Retina (MJLQ2)"
```
указывать нельзя, потому что это невалидный JSON.

Два других варианта поддерживаются. Первый - можно копировать с веб-страницы товара. Второй - из xml со структурой каталога (ссылка в админке b2b).

**Comment by kashapov** [comment]
спс, начали проходить кавычки.
