### ISSUE TITLE
Позиции указанного товара

### ISSUE THREAD

**Issue by wwwatches** [onlinerby/onliner-b2b-api#26]
Данный GET-запрос не возвращает список позиций товара:

> GET /sections/{sectionId}/manufacturers/{manufacturerId}/products/{productId}/positions

Пример GET /sections/325/manufacturers/3887/products/439083/positions не работает.

Здесь 404-я ошибка: https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/positions.md

В чем проблема?

**Comment by ptrofimov** [comment]
Удалил битую ссылку. Актуальная документация по этому методу https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/export/products.md

**Comment by ptrofimov** [comment]
Все ID в ссылке указаны верно. "Не работает" - это как проявляется?

**Comment by wwwatches** [comment]
Приходит пустой ответ:
http://image.prntscr.com/image/dc0775e679d44d7ea0ee345a68a757f6.png
http://image.prntscr.com/image/4285669e22a748aab3d26bc29c6a350c.png

Причем по остальным запросам, например, список производителей или список товаров производителя, все данные приходят верно.

**Comment by ptrofimov** [comment]
У данного товара нет позиций, поэтому пустой список. Номер магазина 6235, верно?

**Comment by wwwatches** [comment]
Да, номер магазина 6235.

> Попробуйте запросить позиции для всех товаров этого производителя с помощью метода https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/export/manufacturers.md

Такой запрос тоже выдает пустой ответ...
/sections/235/manufacturers/3887/positions

**Comment by ptrofimov** [comment]
Должно быть GET /sections/325/manufacturers/3887 а не /sections/235/manufacturers/3887/positions

**Comment by wwwatches** [comment]
Я пишу через curl_init:
`$process = curl_init("https://b2bapi.onliner.by/sections/235/manufacturers/3887/positions");`
Остальные запросы, написанные аналогичным образом, работают.

**Comment by ptrofimov** [comment]
ID раздела 325

**Comment by wwwatches** [comment]
Спасибо большое! Заработало.
