### ISSUE TITLE
onliner-b2b-api/price-lists/import/status.md - статус импорта

### ISSUE THREAD

**Issue by TSUKER** [onlinerby/onliner-b2b-api#30]
Статус - ОШИБКА_ВАЛИДАЦИИ
`{"id":"589050505d3aa665398b4567","shopId":6008,"statusCode":"STATUS_PARSE_ERROR","statusText":"\u041e\u0448\u0438\u0431\u043a\u0430 \u0432\u0430\u043b\u0438\u0434\u0430\u0446\u0438\u0438","date":"2017-01-31 11:52:32","processedCount":0,"errorsCount":0}`

report - пустой, там нет ошибок, в чем может быть причина?, можете подробнее описать ошибки.

**Comment by Olden** [comment]
данная ошибка свидетельствует о том, что у вас данные невалидны для данного формата(json). 

если говорить конкретнее то тут есть не экранированная двойная кавычка:
```json
"model":"Dell LCD SE2416H 60.5cm(23.8")FullHD/LED/IPS/Antiglare/16:9/1920x1080/250cdm2/6ms/178-178/VGA,HDMI/Tilt/Black",
```

**Comment by TSUKER** [comment]
Соответствует JSON стандарту. json сгенерирован стандартной функцией.

`[{"id":"87574","category":"\u041c\u043e\u043d\u0438\u0442\u043e\u0440\u044b","vendor":"\u0410\u0421\u0421 \u0414\u0438\u0441\u0442\u0440\u0438\u0431\u0443\u0446\u0438\u044f","model":"Dell Single Monitor Arm","price":266.91,"currency":"BYN","comment":"\u0412\u0430\u0448 \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439","producer":"Foxconn,No.2,2nd Donghuan Road,10th Yousong Industrial District,Longhua,Baoan,Shenzhen City,Guangdong Province,China","importer":"\u041e\u041e\u041e \u041c\u0443\u0437\u0442\u0440\u0435\u0439\u0434, \u0433.\u041c\u0438\u043d\u0441\u043a, \u0443\u043b. \u041a\u0440\u043e\u043f\u043e\u0442\u043a\u0438\u043d\u0430, 12\r\n\u041e\u041e\u041e \u041f\u043b\u0435\u0435\u0440\u0441\u0435\u0440\u0432\u0438\u0441, \u0433.\u0413\u043e\u043c\u0435\u043b\u044c, \u0443\u043b. \u041f\u043b\u0430\u0442\u043e\u043d\u043e\u0432\u0430, 16","serviceCenters":"\u041e\u041e\u041e \u041c\u0443\u0437\u0441\u0435\u0440\u0432\u0438\u0441, \u0433.\u041c\u0438\u043d\u0441\u043a, \u0443\u043b. \u041f. \u0411\u0440\u043e\u0432\u043a\u0438, 5\r\n\u041e\u041e\u041e \u041f\u043b\u0435\u0435\u0440\u0441\u0435\u0440\u0432\u0438\u0441, \u0433.\u0413\u043e\u043c\u0435\u043b\u044c, \u0443\u043b. \u041f\u043b\u0430\u0442\u043e\u043d\u043e\u0432\u0430, 16","warranty":"12","deliveryTownTime":1,"deliveryTownPrice":"1.00","deliveryCountryTime":5,"deliveryCountryPrice":"2.00","productLifeTime":36,"isCashless":"\u043d\u0435\u0442","isCredit":"\u043d\u0435\u0442"}]`

ошибка таже - ошибка - "STATUS_PARSE_ERROR"

**Comment by Olden** [comment]
не наблюдаю данную ошибку при таких данных.
Файл поступает в обработку, но позиция не имопртируется: "Неверно указан или не указан производитель товара"

**Comment by TSUKER** [comment]
https://yadi.sk/i/-mSyCSUb3C2wc2
https://yadi.sk/i/x2lNcjHE3C2xH4

При получении статуса ошибка. А в репорте пусто.

**Comment by Olden** [comment]
на скринах вы смотрите статус загрузки прайслиста с id 589050505d3aa665398b4567, который был загружен в 11:52, и после него уже есть куча "успешных" загрузок, вы уверены, что вы смотрите то, что вам на самом деле надо?

**Comment by TSUKER** [comment]
ID выдается тот же постоянно.
https://yadi.sk/i/qRDXo1Uk3C3Mp5
*только что все повторил

**Comment by Olden** [comment]
то что у вас под стрелками:

589050505d3aa665398b4567
58907a857c65645b6d8b4567

на сколько мне известно это разные ID.

**Comment by TSUKER** [comment]
а сори точно. я думал это хеши потому не  по символьно сравнивал.

**Comment by TSUKER** [comment]
на вопрос по обязательность полей https://github.com/onlinerby/onliner-b2b-api/issues/31
ответьте плз.
