### ISSUE TITLE
PATCH /pricelists   - Добовление(Обновление) позиций

### ISSUE THREAD

**Issue by TSUKER** [onlinerby/onliner-b2b-api#31]
Какие поля являются обязательными?

**Comment by Olden** [comment]
Обязательными являются:
category
vendor
model
serviceCenters - зависит от раздела
importer
producer
deliveryCountryTime - если установлена цена доставки по стране
deliveryTownTime - если установлена цена доставки по городу
currency
warranty
price - может быть равен 0


зы. в скоре дополним документацию

**Comment by maryangur** [comment]
Здравствуйте!
Подскажите, пожалуйста, каким методом можно добавить товары в прайс-лист?

**Comment by sidorovich** [comment]
https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/import/update.md

**Comment by maryangur** [comment]
Спасибо! Этим и добавляла, но не проверила статус. А там, оказалось, ошибка.

**Comment by Goldkaras** [comment]
Здравствуйте!
Есть вопрос с обновлением цен через метод PATCH
Алгоритм такой - получаю данные о товаре через 
https://b2bapi.onliner.by/sections/"+IDраздела+"/manufacturers/"+КодПроизводителя+"/products/"+КодТовара+"/positions"

далее устанавливаю поля 
price,
stockStatus
 currency
и методом patch отправляю файлы назад, часть товаров таи обрабзом обновляется а на часть ругается
ERROR_VENDOR_NOT_FOUND
ERROR_MODEL_NOT_FOUND
WARNING_INVALID_ARTICLE

ниже прикрепляю два файла - один нормально обновляет цены , на втором ругается - файлы в части производителя - одинаковые и прежде чем прикрепить сменил расширение с xml на txt

[http_request_0001(обновляется нормально).txt](https://github.com/onlinerby/onliner-b2b-api/files/2085019/http_request_0001.txt)
[http_request_0001(не обновляется).txt](https://github.com/onlinerby/onliner-b2b-api/files/2085020/http_request_0001.txt)

**Comment by sidorovich** [comment]
в процессе вненсения изменений у вас, почему-то, изменились поля модели и артикула

в первом файле `<model>Cascade 50x60 [Л.50х60.К6 (1")]</model>`
во втором файле `<model>Cascade Л.50х100.К9 (1")</model>`

в первом файле `<article>Л.50х60.К6 (1")</article>`
во втором файле `<article>Л.50х100.К9</article>`

а также изменился идентификатор позиции
при этом цена и наличие не изменилось.

**Comment by Goldkaras** [comment]
это не файл до изменения и после, это два уже изменённых файла, для разных позиций. Просто один нормально загружается на onliner а второй нет - хотя алгоритм обработки одинаковый. Это то что я беру все поля по товару с онлайнера, а обновляю только 3 из них 
price,
stockStatus
currency
а все остальные данные - это данные полученные с оналйнера. а назад на онлайнер часть этих файлов не загружается

**Comment by sidorovich** [comment]
то есть проблема только со вторым файлом?

**Comment by Goldkaras** [comment]
файл который называется "http_request_0001(не обновляется).txt", обратите внимание расширение изменил с xml на txt чтобы прикрепить файл в обсуждение

**Comment by sidorovich** [comment]
Вы передаете двойную кавычку в виде одного символа `"`
Согласно файла структуры каталога `https://content.onliner.by/catalog/structure.xml` передавать нужно `&quot;`

**Comment by Goldkaras** [comment]
какие еще ограничения есть? Дабы предусмотреть - или это секретная информация?
И прошу обратить внимание - все значения параметров я получаю от Вашего ресурса и их же возвращаю, только заменяю цену на нужную мне.  Это опять же обратить внимание что это Ваш ресурс передаёт кавычку и обратите внимание, что в файле который принимался Вашим ресурсом "http_request_0001(обновляется нормально).txt" тоже была кавычка - но она нормально воспринималась. Но Ваш совет помог и сейчас уже еще часть товаров стала восприниматься Вашим ресурсом.

**Comment by Goldkaras** [comment]
Вот еще один файл который не загружается, кавычки в нём заменены, (в этом файле как и в предыдущих расширение xml заменено на txt , чтобы можно было прикрепить файлик к данном сообщению)
[http_request_0001(ЕЩЕ ОДИН НЕ ОБНВОЛЯЕТСЯ НО КАВЫЧКИ ЗАМЕНИЛИ).TXT](https://github.com/onlinerby/onliner-b2b-api/files/2088211/http_request_0001.TXT)

**Comment by sidorovich** [comment]
`<model>Standart M [М.60х50 (1&amp;quot)]</model>`

скорее всего проблема в том, что `&quot;` превратился в результате преобразования в `&amp;quot`, т.е. символ амперсанда, который являлся частью HTML-сущности `&quot` был преобразован в самостоятельную HTML-сущность `&amp`, к сожалению не знаю на каком языке реализовано ваше приложение, но если это PHP, то, возможно, на вашей стороне выполняется дополнительное преобразование при формировании XML.

**Comment by Goldkaras** [comment]
Разобрался, суть в том что от вас когда приход наименование в нём знак &, уже заменен на &amp;
а так как я передавал получаемые ваши наименования без преобразований, то он еще раз заменялся на &amp;
Спасибо, за помощь

**Comment by sidorovich** [comment]
если вопросов больше нет, закрывайте текущую задачу.
