### ISSUE TITLE
Не могу получить токен к onliner-b2b-api, хотя к onliner-cart-api токен получается без проблем

### ISSUE THREAD

**Issue by sashaka00120** [onlinerby/onliner-b2b-api#32]
Добрый день!
Проект на Node.js

Собственно, не могу получить токен к onliner-b2b-api, хотя к onliner-cart-api токен получается без проблем.

Листинг ниже:

`const express = require('express'); 
const app = express(); 

var request = require('request')

const credentials = { 
client: { 
id: '***', 
secret: '***' 
}, 
auth: { 
tokenHost: 'https://b2bapi.onliner.by/oauth/token' 
} 
}; 
var authToken; 

const oauth2 = require('simple-oauth2').create(credentials); 

app.get('/', (req, res) => { 
const code = req.query.code; 
const options = { 
code, 
}; 
oauth2.authorizationCode.getToken(options, (error, result) => { 
if (error) { 
console.error('Access Token Error', error.message); 
return res.json('Authentication failed'); 
} 

console.log('The resulting token: ', result); 
authToken=result; 
const token = oauth2.accessToken.create(result); 

return res 
.status(200) 
.json(token); 
}); 

}); 

app.listen(3000, () => { 
console.log('Express server started on port 3000'); // eslint-disable-line 
});`

**Comment by aliaksandr-lindarenka** [comment]
День добрый!

После небольших правок в коде, токен был получен корректно.
Листинг кода ниже:
```js
const express = require('express');
const app = express();

var request = require('request');

const credentials = {
    client: {
        id: '***',
        secret: '***'
    },
    auth: {
        tokenHost: 'https://b2bapi.onliner.by/oauth/token'
    }
};

var authToken;

const oauth2 = require('simple-oauth2').create(credentials);

app.get('/', (req, res) => {
    var token;

    const code = req.query.code,
        options = {
            code
        };

    oauth2.authorizationCode.getToken(options, (error, result) => {
        if (error) {
            console.error('Access Token Error', error.message);
            return res.json('Authentication failed');
        }


        console.log('The resulting token: ', result);
        authToken = result;
        token = oauth2.accessToken.create(result);
    });

    return res
        .status(200)
        .json(token);
});

app.listen(3000, () => {
    console.log('Express server started on port 3000'); // eslint-disable-line
});
```

С уважением, отдел разработки onliner.by.

**Comment by sashaka00120** [comment]
Использовал ваш код, но что то не так.
![screenshot_14](https://cloud.githubusercontent.com/assets/26055820/23356259/3bfce9ea-fcea-11e6-8916-2847a82fa10d.png)

**Comment by aliaksandr-lindarenka** [comment]
Данная ошибка возникает при некорректных авторизационных данных, а именно id и secret.
Если проблема не решится, просьба указать номер магазина.

**Comment by sashaka00120** [comment]
Магазин №14747
Пробовал генерировал новые ключи - не работает.
А с данными onliner-cart-api все работает.

**Comment by aliaksandr-lindarenka** [comment]
```
const express = require('express');
const app = express();

var request = require('request');

const credentials = {
    client: {
        id: '***',
        secret: '***'
    },
    auth: {
        tokenHost: 'https://b2bapi.onliner.by/oauth/token'
    }
};

var authToken;

const oauth2 = require('simple-oauth2').create(credentials);

app.get('/', (req, res) => {
    let token;

    const code = req.query.code,
        options = {
            code
        };

    oauth2.clientCredentials.getToken(options, (error, result) => {
        if (error) {
            console.error('Access Token Error', error.message);
            return res.json('Authentication failed');
        }


        console.log('The resulting token: ', result);
        authToken = result;
        token = oauth2.accessToken.create(result);
    });

    return res
        .status(200)
        .json(token);
});

app.listen(3000, () => {
    console.log('Express server started on port 3000'); // eslint-disable-line
});
```

С данным кодом должно работать.
Вместо authorizationCode нужно использовать clientCredentials.

**Comment by sashaka00120** [comment]
Работает.
Спасибо за оперативность и  помощь.

**Comment by aliaksandr-lindarenka** [comment]
Если проблема решена, закройте, пожалуйста, issue.
