### ISSUE TITLE
Доставка

### ISSUE THREAD

**Issue by mebelart** [onlinerby/onliner-b2b-api#33]
Здравствуйте, можно ли при помощи приложения onliner-b2b-api устанавливать дату доставки для категории, к примеру Blanco моек ("Доставка по Беларуси" - бесплатно")
prntscr.com/efg0rw
"deliveryTownTime":1,
"deliveryTownPrice":"1.00",
"deliveryCountryTime":5,
"deliveryCountryPrice":"2.00",
Эти строчки отвечают за данные в полях доставки и стоимости доставки, верно?
Меня интересует изменение только для отдельных категорий - к примеру Blanco мойки
Доставка по Минску, если "есть в наличии" - 2 дня, если "нет в наличии" 14 дней. Доставка по Беларуси - бесплатно.
А Teka моек: Доставка по Минску, если "есть в наличии" - 2 дня, если "нет в наличии" - 14 дней. Доставка по Беларуси - 12 руб.
А у остальных категорий не осуществляется доставка по Беларуси к примеру.
Это что касается апи.
А в ссылке по которой сейчас у нас загружаются (обновляются) позиции это можно сделать? Сайт на modx. Вот ссылка mebelart.by/onliner.xml

**Comment by sidorovich** [comment]
Данные по доставке (сроки и стоимость) являются атрибутом конкретного ценового предложения, поэтому их нужно указывать для каждого предложения и их нельзя задать для всех предложения одного производителя или одного раздела. 

Вы можете реализовать это на своей стороне. Вам помогут поля `vendor` и `category`.

Также, хочу обратить Ваше внимание, что у нас нет состояния "нет в наличии" все ценовые предложения должны быть актуальными, соответственно сроки доставки для таких предложений Вы должны контролировать сами на стороне Вашего приложения и отдавать нам только сроки и стоимость доставки по каждому предложению.

Так как внутренние детали Вашей реализации и движка MODX нам не знакомы, то более глубокую техническую помощь мы Вам оказать не можем.

Если мы ответили на Ваш вопрос, то закройте эту тему, если нет - то можем продолжить дискуссию.
