### ISSUE TITLE
Get-запрос по ценам

### ISSUE THREAD

**Issue by worker2017** [onlinerby/onliner-b2b-api#34]
Добрый день/вечер

Подскажите какой get-запрос ([подобно](https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/export/positions.md) можно использовать чтобы получить цены по номенклатуре в разрезе магазинов? ([аналог](http://b2b.onliner.by/catalog_prices))

Спасибо.

**Comment by Olden** [comment]
добрый вечер, в api такой возможности нет

**Comment by worker2017** [comment]
Правильно я понял, что в данном случае необходимо парсить файл? Другого варианта нету?
Спасибо.

**Comment by Olden** [comment]
@worker2017 в данный момент все именно так

**Comment by worker2017** [comment]
Спасибо

**Comment by Olden** [comment]
пожалуйста
