### ISSUE TITLE
Импорт прайс-листов

### ISSUE THREAD

**Issue by sericamanco** [onlinerby/onliner-b2b-api#35]
Добрый день! Хотел бы увидеть живой пример отправки прайса средствами API с помощью cURL PHP. А конкретнее нужен запрос с параметрами. Тот запрос, что в документации, как я понял неполный, ведь нужно также передать ещё свой API key и т.д.

И ещё возможно есть некая тестовая среда? Не хотелось бы добавлять неправильные прайс-листы, пока всё не будет как надо работать

**Comment by Olden** [comment]
Добрый день.

Отправка прайса полностью описана тут: https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/import/update.md и тут: https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/import/replace.md

Любой запрос к API требует авторизации по средством oAuth которое описано тут: https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/oauth20.md

Очередность следующая:
- получаете токен
- отправляете запрос на обновление прайслиста с указание полученного токена(он может передаваться как query параметром:access_token=RECEIVED_TOKEN_STRING так и заголовком: Authorization: Bearer RECEIVED_TOKEN_STRING

все описано на указанных страницах.

**Comment by sericamanco** [comment]
<?
	$process = curl_init("https://b2bapi.onliner.by/oauth/token");
	curl_setopt($process, CURLOPT_HTTPHEADER, array('Accept: application/json'));
	curl_setopt($process, CURLOPT_USERPWD, "204da9b95e2480a3455f:7a4bbb61262fdf41d410645292a0489ba752c6b9");
	curl_setopt($process, CURLOPT_POST, 1);
	curl_setopt($process, CURLOPT_RETURNTRANSFER, TRUE);
	curl_setopt($process, CURLOPT_POSTFIELDS, array('grant_type' => 'client_credentials'));
	$result = curl_exec($process);
	curl_close($process);
	print_r($result);
?>

Что нужно передать в grand_type?
Ибо сейчас ответ такой:
{"error":"invalid_client","error_description":"The client credentials are invalid"}

**Comment by Olden** [comment]
@sericamanco 
> Что нужно передать в grand_type?
Ибо сейчас ответ такой:
{"error":"invalid_client","error_description":"The client credentials are invalid"}

С теми параметрами Client ID и Client Secret, которые вы указали, ни один клиент не находится, так что не удивительно, что вы получаете в ответ такую ошибку

**Comment by sericamanco** [comment]
Да, поэтому я и удалил вопрос на гитхабе. Потому что разобрался

14 июня 2017 г. 4:49 PM пользователь "Alexander Katynia" <
notifications@github.com> написал:

**Comment by Olden** [comment]
отлично
