### ISSUE TITLE
Добавление моделей и производителей в каталог

### ISSUE THREAD

**Issue by iamweird** [onlinerby/onliner-b2b-api#36]
Здравствуйте.

Пытаемся импортировать в каталог XML-файл с товарами, но проверка в личном кабинете выдает ошибки "Неверно указана или не указана модель товара", "Неверно указан или не указан производитель товара". Значит ли это, что список моделей и производителей предустановлен и задается самим onliner.by?

Если это так, то есть ли какой-либо API для загрузки моделей и производителей? Т.к. есть группа из около 2000 товаров одного производителя, и этот производитель целиком не представлен в каталоге onliner.by. Что нужно сделать в таком случае, чтобы добавить эти 2000 товаров в каталог?

Кроме того, для моделей, которые есть в каталоге, сравнение производится через точное совпадение строк? То есть в прайсе они должны называться именно так же, как и в каталоге onliner.by, с точностью до символа?

**Comment by sidorovich** [comment]
1. Да, список моделей и производителей предустановлен и задается самим onliner.by
2. Структура каталога доступна по адресу http://content.onliner.by/catalog/structure.xml (можно найти на странице "Импорт/Экспорт" в личном кабинете B2B) Файл обновляется раз в сутки.
3. Для добавления несуществующих в каталоге товаров есть механизм заявок http://b2b.onliner.by/support
4. Абсолютно верно, название раздела, производителя и самого товара должно полностью соответствовать данным, указанным в файле со структурой каталога.

**Comment by iamweird** [comment]
Спасибо за быстрый ответ.

**Comment by iamweird** [comment]
Добрый день.

Хотелось бы уточнить: в случае, если имеется большой объем товаров, которых еще нет в каталоге (скажем, несколько сотен), все равно предполагается их добавление через личный кабинет вручную? Нет ли какого-нибудь механизма API для отправки запроса на добавление товаров в каталог? В данном репозитории я такого не нашел.

**Comment by sidorovich** [comment]
Да, отправляйте через форму. Там в комментариях можно указать ссылку на полный список. Все заявки обрабатываются вручную.

**Comment by Olden** [comment]
@iamweird если вопрос решили, закрывайте тикет
