### ISSUE TITLE
Выгрузка прайс листа (API)

### ISSUE THREAD

**Issue by San4aus** [onlinerby/onliner-b2b-api#37]
Здравствуйте, в чате отправили сюда, в общем пытаемся подключиться через API, выдаёт ошибку валидации: `{"id"=>"596f447c5c2b9492618b4569", "shopId"=>15471, "statusCode"=>"STATUS_PARSE_ERROR", "statusText"=>"Ошибка валидации", "date"=>"‎2017-07-19 14:37:32", "processedCount"=>0, "errorsCount"=>0}`

Также по модели вопрос, сказали в чатике, что нужно экранировать, примерно так: `"model": "Avenue 77 см \[‎3240-02-74\]"`, но это как бы не по стандарту или и так сойдёт?)

Фрагмент JSON запроса:  
[price-list2017-07-19(1).zip](https://github.com/onlinerby/onliner-b2b-api/files/1159011/price-list2017-07-19.1.zip)

**Comment by Olden** [comment]
Добрый день, извините за задержку.
У вас там невалидный json.
именно из-за строки которую вы указали, попробуйте так:
"model": "Avenue 77 см [‎3240-02-74]"

**Comment by San4aus** [comment]
Слеши убрал, появляется теперь эта ошибка: 
`Категория: Чемоданы и дорожные сумки
Производитель: March
Модель: Avenue 54 см [‎3240-16-74]
Цена: 399.99
Подробно
Ошибки:
model
ERROR_MODEL_NOT_FOUND - Неверно указана или не указана модель товара`

**Comment by San4aus** [comment]
Причём некоторые товары прошли, а некоторые нет, в чём проблема, не пойму.

**Comment by ptrofimov** [comment]
Avenue 54 см [‎3240-16-74] не находится в поиске каталога. В первый раз вы указывали другой товар Avenue 77 см [‎3240-02-74], который есть.

**Comment by San4aus** [comment]
С этим разобрались, косяки со стороны заказчика были, не правильно заполнили.

Что значит эта ошибка:
 id
ERROR_POSITION_ID_NOT_UNIQUE - Неуникальный id

**Comment by ptrofimov** [comment]
Эта ошибка значит, что указанный ID позиции уже используется либо в прайсе вашего магазина либо в прайсе другого, так как нумерация позиций общая. Вам нужно либо присвоить другой id, либо не указывать его вообще, тогда при импорте будет присвоен автоматически id, который уже можно использовать для операций с позициями.

**Comment by San4aus** [comment]
И скорее всего последний вопрос, на некоторых товарах такая ошибка:

`
Категория: Чемоданы и дорожные сумки
Производитель: March
Модель: Bumper 76 см [010072-19]
Цена: 249.99
Подробно
{"category"=>"Чемоданы и дорожные сумки", "vendor"=>"March", "model"=>"Bumper 76 см [010072-19]", "price"=>249.99, "currency"=>"BYN", "comment"=>"", "producer"=>"March15 BV. Van Hogenhoucklaan 156, 2596 TJ Den Haag, Нидерланды.", "importer"=>"ЗАО Империя Дождя, г.Минск, ул. Пономаренко, 43а, оф.7, ‎8-017-228-27-46", "serviceCenters"=>"ЗАО Империя Дождя, г.Минск, ул. Воронянского, 4Б, Телефоны: тел.: ‎+375 (17) 219-79-86", "warranty"=>60, "deliveryTownTime"=>1, "deliveryTownPrice"=>"1.00", "deliveryCountryTime"=>5, "deliveryCountryPrice"=>"2.00", "productLifeTime"=>0, "isCashless"=>"нет", "isCredit"=>"нет"}
Ошибки:
price
Неуникальная цена - Неуникальная цена
`

**Comment by ptrofimov** [comment]
Это значит, что на один и тот же товар в прайсе одного магазина есть две позиции с одинаковой ценой. Цены должны быть уникальными.

**Comment by San4aus** [comment]
Благодарю, пока закрываю тикет, вроде всё работает.

**Comment by San4aus** [comment]
Здравствуйте, вопрос по модели.

В общем скопировал модель с каталога (а также сверил со структурой каталога), не хочет выводить цвет на русском в скобках.

Категория: Чемоданы и дорожные сумки
Производитель: Gabol
Модель: Reims () [111010-016]
Цена: 69.99

Как прописано в карточке товара: 

http://prntscr.com/g8pci4

Также проблема наблюдается и в соседнем товаре: 

Категория: Чемоданы и дорожные сумки
Производитель: Gabol
Модель: Reims () [111009-016]
Цена: 69.99

Причём аналогичный товар залился нормально: https://catalog.onliner.by/suitcase/gabol/111012003/prices

**Comment by sidorovich** [comment]
А можете привести пример файла, который пытаетесь импортировать?
Модели `Reims (серый) [111010-016]` и `Reims (серый) [111009-016]` есть в структуре каталога и должны импортироваться корректно.

**Comment by San4aus** [comment]
Конечно, 
[price-list2017-08-15.zip](https://github.com/onlinerby/onliner-b2b-api/files/1225077/price-list2017-08-15.zip)

**Comment by sidorovich** [comment]
У Вас указаны некорректные модели:
`"model": "Reims () [111010-016]"` и `"model": "Reims () [111009-016]"`

**Comment by San4aus** [comment]
В выгрузке да, но в карточке товара, я скидывал скриншот выше, указано как в каталоге онлайнера.

http://prntscr.com/g8pci4

**Comment by sidorovich** [comment]
Это уже внутренняя реализация вашей системы - здесь мы бессильны. Чтобы цены появились у нас на сайте необходимо передавать корректную модель в выгрузке. Почему она в ваших данных некорректная мы знать не можем.

**Comment by San4aus** [comment]
Всё ок, извиняюсь за беспокойство, была допущена ошибка.
