### ISSUE TITLE
Проблема с подключением в onliner-cart-api

### ISSUE THREAD

**Issue by larin-ihor** [onlinerby/onliner-b2b-api#38]
Добрый день компания AMD.by, пытаемся настроить работу через АПИ. в итоге:
приложение в личном кабинете создано, логин и пароль есть.
получили Токен, пытаемся с этим токеном обратится к заказам, возвращает: {"message":"Access denied"}
Подскажите, что мы забыли?

**Comment by sidorovich** [comment]
А покажите токен. После получения нами сможете его удалить или испортить.

**Comment by sidorovich** [comment]
Доброе утро! Прошу прощения за задержку, вчера случились какие-то проблемы с github и ваша issue временно была недоступна. Указанный Вами токен не похож на токен для доступа к cart.api. Проверьте, что используете Client ID и Client Secret для приложения onliner-cart-api со страницы http://b2b.onliner.by/pricelists

**Comment by Olden** [comment]
@larin-ihor если вопрос более не актуален, закрывайте тикет
