### ISSUE TITLE
id товара при добавлении/обновлении

### ISSUE THREAD

**Issue by vex2865** [onlinerby/onliner-b2b-api#39]
Подскажите откуда брать этот id http://joxi.ru/p27O9e0IogDbg2 для добавления/обновления товара? На данный момент мы выгружаемся вручную используя файл csv, там id не указываем...

**Comment by sidorovich** [comment]
для добавления его можно не указывать, а для обновления его можно узнать сделав выгрузку своего прайс-листа и найдя в нем нужную позицию https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/export/products.md

**Comment by Olden** [comment]
@vex2865 если вопрос более не актуален, закрывайте тикет
