### ISSUE TITLE
Delete subject are not specified

### ISSUE THREAD

**Issue by vex2865** [onlinerby/onliner-b2b-api#40]
В теле запроса установлено следующее http://joxi.ru/gmv3vZacLRwLw2
При отправке запроса HTTP-метод DELETE получаю вот такой ответ {"errors":"Delete subject are not specified"}

что делаю не так?

**Comment by Olden** [comment]
Если вы пробуете удалить позиции по id(хотя я только могу догадываться какой DELETE метод вы используете), то вы передаете id в неверном формате. вот тут описан верный формат:
https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/delete/list.md#Пример-запроса
