### ISSUE TITLE
Добавление позиций (как работать с ID)

### ISSUE THREAD

**Issue by kitunovich** [onlinerby/onliner-b2b-api#41]
Добрый день,
объясните плиз получили по API список товаров в нём есть поле ID 
пример: 
5536931841 Товар1
5536931842 Товар2
5536931843 Товар3
соединили со своей базой (изменили цены, наличие, добавили новые позиции!!!)
в итоге имеем
5536931841 Товар1
5536931842 Товар2
5536931843 Товар3
??????????? Товар4(новый)
для обновления на онлайнере 2 варианта:
1. поле ID нового товара оставлять пустым? 
2. или всех товаров делать пустыми?

С Уважением, Алексей

**Comment by ptrofimov** [comment]
Если ID позиции оставить пустым, он будет сгенерирован автоматически. У существующих позиций нужно указывать присвоенные ID, потому что к ним привязываются заказы корзины и другие вещи.

Для нового - оставьте пустым, для остальных - укажите.

**Comment by ptrofimov** [comment]
@kitunovich если проблема решена, закройте, пожалуйста, issue.
