### ISSUE TITLE
Максимальный размер json при изменении

### ISSUE THREAD

**Issue by vex2865** [onlinerby/onliner-b2b-api#42]
https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/import/update.md

При попытке отправить данные на изменение в ответ приходит следующее:

<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>

пытаюсь отправить данные размером ~72 мб

Какой максимальный размер можно отправлять?

**Comment by Olden** [comment]
на данный момент максимальный размер 50мб

**Comment by vex2865** [comment]
т.е. можно послать 2 запроса на изменение, к примеру 1 - 50 мб, 2 - 22 мб и они обработаются в порядке очереди. правильно я понимаю?

**Comment by Olden** [comment]
правильно, но я бы советовал слать более мелкими пачками.
