### ISSUE TITLE
Неуникальный id

### ISSUE THREAD

**Issue by vex2865** [onlinerby/onliner-b2b-api#43]
Добрый день!
Подскажите как быть в данной ситуации. 
Есть товар в разных цветах, и с разными ценами, но это один и тот же товар, только цвет отличается.
Как корректно обменяться данными товарами. При обмене получаем ошибку "неуникальный id".

http://joxi.ru/krD8lebfEX8Nar

**Comment by vex2865** [comment]
В массиве json вижу 4 таких товара, но по идее должны выгрузится 3 товара, так как Ваши коллеги говорили что у товара с одинаковым кодом обмена должна отличаться цена либо описание.

{
  "id": "5596361377",
  "category": "Машинки для стрижки волос",
  "vendor": "Panasonic",
  "model": "ER-GB40",
  "price": "95.34",
  "currency": "BYN",
  "comment": "Цвет Silver. Рассрочка до 12 месяцев без первого взноса и переплат! Халва 5 месяцев, Карта покупок 6 месяцев! Скидки для корпоративных клиентов! Все способы оплат! Гарантия в официальном СЦ! СТБ/ ЕАС! Возможен самовывоз м. Академия наук!",
  "producer": "Мацушита Электрик Индастриал Ко., Лтд.1006 Кадома, Кадома Сити, Осака 571-8501, Япония",
  "importer": "ООО ''Электросервис и Кo'', УНН 100373457, г. Минск, ул. Чернышевского 10А, комн. 412А3",
  "serviceCenters": "ООО «Катрикс» Минск, ул. Чернышевского, 10а-115",
  "warranty": "12",
  "deliveryTownTime": 1,
  "deliveryTownPrice": "5.87",
  "deliveryCountryTime": 2,
  "deliveryCountryPrice": "8.00",
  "productLifeTime": 60,
  "isCashless": "нет",
  "isCredit": "да"
 },
 {
  "id": "5596361377",
  "category": "Машинки для стрижки волос",
  "vendor": "Panasonic",
  "model": "ER-GB40",
  "price": "101.30",
  "currency": "BYN",
  "comment": "Рассрочка до 12 месяцев без первого взноса и переплат! Халва 5 месяцев, Карта покупок 6 месяцев! Скидки для корпоративных клиентов! Все способы оплат! Гарантия в официальном СЦ! СТБ/ ЕАС! Возможен самовывоз м. Академия наук!",
  "producer": "Мацушита Электрик Индастриал Ко., Лтд.1006 Кадома, Кадома Сити, Осака 571-8501, Япония",
  "importer": "ООО ''Электросервис и Кo'', УНН 100373457, г. Минск, ул. Чернышевского 10А, комн. 412А3",
  "serviceCenters": "ООО «Катрикс» Минск, ул. Чернышевского, 10а-115",
  "warranty": "12",
  "deliveryTownTime": 1,
  "deliveryTownPrice": "0.00",
  "deliveryCountryTime": 2,
  "deliveryCountryPrice": "8.00",
  "productLifeTime": 60,
  "isCashless": "нет",
  "isCredit": "да"
 },
 {
  "id": "5596361377",
  "category": "Машинки для стрижки волос",
  "vendor": "Panasonic",
  "model": "ER-GB40",
  "price": "95.34",
  "currency": "BYN",
  "comment": "Цвет Blue. Рассрочка до 12 месяцев без первого взноса и переплат! Халва 5 месяцев, Карта покупок 6 месяцев! Скидки для корпоративных клиентов! Все способы оплат! Гарантия в официальном СЦ! СТБ/ ЕАС! Возможен самовывоз м. Академия наук!",
  "producer": "Мацушита Электрик Индастриал Ко., Лтд.1006 Кадома, Кадома Сити, Осака 571-8501, Япония",
  "importer": "ООО ''Электросервис и Кo'', УНН 100373457, г. Минск, ул. Чернышевского 10А, комн. 412А3",
  "serviceCenters": "ООО «Катрикс» Минск, ул. Чернышевского, 10а-115",
  "warranty": "12",
  "deliveryTownTime": 1,
  "deliveryTownPrice": "5.87",
  "deliveryCountryTime": 2,
  "deliveryCountryPrice": "8.00",
  "productLifeTime": 60,
  "isCashless": "нет",
  "isCredit": "да"
 },
 {
  "id": "5596361377",
  "category": "Машинки для стрижки волос",
  "vendor": "Panasonic",
  "model": "ER-GB40",
  "price": "95.34",
  "currency": "BYN",
  "comment": "Цвет Red. Рассрочка до 12 месяцев без первого взноса и переплат! Халва 5 месяцев, Карта покупок 6 месяцев! Скидки для корпоративных клиентов! Все способы оплат! Гарантия в официальном СЦ! СТБ/ ЕАС! Возможен самовывоз м. Академия наук!",
  "producer": "Мацушита Электрик Индастриал Ко., Лтд.1006 Кадома, Кадома Сити, Осака 571-8501, Япония",
  "importer": "ООО ''Электросервис и Кo'', УНН 100373457, г. Минск, ул. Чернышевского 10А, комн. 412А3",
  "serviceCenters": "ООО «Катрикс» Минск, ул. Чернышевского, 10а-115",
  "warranty": "12",
  "deliveryTownTime": 1,
  "deliveryTownPrice": "5.87",
  "deliveryCountryTime": 2,
  "deliveryCountryPrice": "8.00",
  "productLifeTime": 60,
  "isCashless": "нет",
  "isCredit": "да"
 },

**Comment by ptrofimov** [comment]
JSON, указанный выше, который вы передаете на загрузку, некорректный. У каждой позиции должен быть уникальный id, либо не указан вовсе (в таком случае он будет присвоен автоматически). Исправьте JSON и сделайте повторную загрузку.

**Comment by vex2865** [comment]
Задам вопрос по другому. У меня есть товар:
"category": "Машинки для стрижки волос",
"vendor": "Panasonic",
"model": "ER-GB40",
этот товар есть в разных цветах. 
Как корректно выгрузить этот  товар в разных цветах?

**Comment by ptrofimov** [comment]
Указываете этот товар столько раз сколько есть цветов. У каждого в описании - свой цвет. id нужно указать разные, название товара - одинаковые.

**Comment by vex2865** [comment]
В таком случае цены можно указать одинаковые либо нужно указывать разные?

**Comment by ptrofimov** [comment]
Цены должны быть разные.
