### ISSUE TITLE
id при обмене

### ISSUE THREAD

**Issue by vex2865** [onlinerby/onliner-b2b-api#44]
можно ли для обмена по апи использовать id товара онлайнера, а не id позиции товара который онлайнер присваивает для каждого прайс листа?

**Comment by Olden** [comment]
id позиции товара присваивается не для каждого прайслиста, а для каждой позиции.
этот id уникально иденцифицирует ваше предложение у нас в системе.
вы можете его как указывать так и не указывать. Если вы его указываете, то вы можете обновить товарные позиции по этому ID для корректной работы корзины. Если не указываете, то старые позиции товара будут удалены и созданы новые и будет у них новый ID.


> можно ли для обмена по апи использовать id товара онлайнера?

нет. товар при импорте определяется по 3 параметрам: раздел, производитель, модель
