### ISSUE TITLE
Добавить ссылку в файл structure.xml

### ISSUE THREAD

**Issue by kitunovich** [onlinerby/onliner-b2b-api#45]
Добрый день,
очень бы хотелось 4 поле в structure.xml
именно ссылка, тяжело добавлять позиции,
если никто их не продает. 
Приходиться отдельно в браузере 
открывать онлайнер и по поиску искать.

**Comment by ptrofimov** [comment]
Добрый день. Какую ссылку вы хотите? Ссылку на страницу товара в каталоге? (пример - https://catalog.onliner.by/mobile/xiaomi/r4x16b)

**Comment by kitunovich** [comment]
Да, было бы отлично

**Comment by ptrofimov** [comment]
Эта ссылка нужна, чтобы узнать, продает ли конкретный товар кто-то другой или нет? Вы хотите делать такую проверку перед импортом позиций магазина на onliner? Почему вы не хотите просто добавлять предложения к товарам из списка, которые есть у вашего магазина в продаже?

**Comment by kitunovich** [comment]
Когда кто-то продает проблем нет, в файле "Все цены каталога" поле ссылка есть и менеджер сравнивает нашу позицию на сайте с позицией на онлайнере (цвет, комплектацию и т.д) 
если все гуд добавляет в новый прайс и импортирует.
Если никто не продает ссылку взять неоткуда начинается ручная работа

**Comment by kitunovich** [comment]
+ это избавит от загрузки файла "Все цены каталога" ради только получения ссылки

**Comment by ptrofimov** [comment]
Мы добавим в список возможных изменений. Спасибо.
