### ISSUE TITLE
Onliner API для импортеров

### ISSUE THREAD

**Issue by piton66** [onlinerby/onliner-b2b-api#52]
Добрый день.
Пытають пройти авторизацию. 
Отправляю Json на  https://b2bapi.onliner.by/importers/token 
{client_id: 1111111111111,
    client_secret: 2222222222222222222222}
Выдает ошибку ресурс не найден. Вероятно что-то я делаю не так? 

Client ID и Client Secret для импортеров получать из Приложение onliner-b2b-api (https://b2b.onliner.by/pricelists) ?

**Comment by piton66** [comment]
Client ID  и Client Secret для импортеров получать из Приложение onliner-b2b-api ?

**Comment by sidorovich** [comment]
Нет, реквезиты для доступа к API импортеров на данном этапе нельзя получить на сайте самостоятельно, можно только через запрос к нашим менеджерам.

Текста ошибки "ресурс не найден" недостаточно для того, чтобы мы могли оказать посильную помощь. Проверьте метод, с использованием которого обращаетесь к данному URI а так же корректность формирования заголовков и тела запроса. Как минимум ключи и строки в JSON должны оборачиваться в кавычки. Также проверьте с помощью ping и traceroute доступность нашего API для сервера, на которым выполняются запросы.

**Comment by sidorovich** [comment]
Подскажите от имени какого юридического лица вы обратились? В данный момент данное API запущено в тестовом режиме является ограниченно доступным. Если у Вас есть документация по данному API, то должны быть и ключи для доступа.

**Comment by piton66** [comment]
Ключи доступа получил уже. С получением токена всё норм.

**Comment by sidorovich** [comment]
В данный момент отдельного кабинета нет, но он планируется. На текущем этапе работа возможна только с указанными методами API. Если подобный функционал будет востребован - будем развивать как API так и другие способы для управления этими данными.

**Comment by sidorovich** [comment]
Если все хорошо и вопросов больше нет - закрывайте issue. Спасибо.

**Comment by piton66** [comment]
А как узнать артикул товара? Для обновления наличия товаров.
Например вот этого https://catalog.onliner.by/waterheater/electrolux/elecrt_ewh80rh/prices?town=minsk

**Comment by sidorovich** [comment]
Подразумевается что источниками корректных артикулов для товаров будут сами импортеры. 
Вы передаете все артикулы, что у Вас есть, а наша задача эту информацию обработать и связать с товарами.
Я вкратце могу дать ответ, но вообще концепцию импорта Вам должны были пояснить наши сотрудники, например Евгений Вербицкий.

Существующие артикулы описаны в файле со структурой каталога, ссылку на который можно найти в личном кабинете B2B в разделе "Импорт/Экспорт" Сама ссылка на файл: https://content.onliner.by/catalog/structure.xml
Данный файл обновляется раз в сутки и если мы знаем какой-либо артикул(ы) для товара, то там они появляются.

Конкретно по указанному товару в данный момент у нас нет ни одного артикула.

Далее, по поводу импорта.
Вы передаете информацию о своих остатках в используя связку производитель-артикул, если данная связка есть у нас в каталоге мы сохраняем информацию об остатках по данному SKU, если такой связки нет, то переданная вами информация попадает в наш внутренний отчет о несошедшихся товарах. Наши операторы каталога мониторят данный отчет и разрешают подобные ситуации: в частности, они могут добавить переданный вами артикул к уже существующему товару, либо добавить новый товар в наш каталог. Для этого им может быть полезна любая информация, передаваемая в поле `description`. Пока связка не будет найдена, информация о подобных SKU сохраняться не будет, как только проблема будет устранена и в нашей базе появится связка, при последующем вашем экспорте данных мы сохраним наличие по SKU. На текущем этапе сколько связок производитель-артикул нашлось, а сколько не нашлось мы вам не говорим, но в качестве помощи при интеграции на первом этапе я могу эту информацию посмотреть в базе данных по вашему запросу. Мы рассчитываем, что в будущем (после заполнения основных товаров) подобных ситуаций будет мало и разрешаться они будут максимально быстро.

**Comment by piton66** [comment]
https://content.onliner.by/catalog/structure.xml Тут я смотрел. там артикула нет. 
Обмен у нас из 1с происходить будет.
Т.е я могу передать на этот товар  свой любой артикул и вы его забьете? 

А как быть с теми товарами на онлайнере где уже есть артикул? В нашей то базе он свой. Как их синхронизировать?

**Comment by sidorovich** [comment]
Под словом артикул мы подразумеваем "Заводской артикул – это уникальный в рамках производителя идентификатор товара. "
То есть он не должен отличаться в нашей и вашей базе и источником данного артикула является завод-изготовитель. В случае подобных конфликтных ситуаций на нашей стороне операторы каталога будут их однозначно решать. Если вы используете свои внутренние артикулы или генерируете их сами, то это не является тем артикулом, который мы подразумеваем как "Заводской артикул – это уникальный в рамках производителя идентификатор товара."

**Comment by piton66** [comment]
А делать то что? к примеру у вас в базе артикулов нет, наши вы не примите. потому что это просто созданные нашей базой номера и никакого отношения к производителю они не имеют.  И если мы их отправим вам. как вы поймете что это номер производителя или просто наш. 
Как тогда товары выгружать? Я в тупике пока))

**Comment by sidorovich** [comment]
Какую организацию вы представляете? Вам явно не донесли общую концепцию всего этого проекта. Я передам нашим ребятам, чтобы они устроили дополнительную встречу.

**Comment by piton66** [comment]
Айронтел

**Comment by sidorovich** [comment]
Куда можно отправить контактные данные нашего специалиста, чтобы вы могли связаться и вам ответили на общие вопросы по логике работы? Позднее с техническими вопросами снова вернетесь ко мне.

**Comment by piton66** [comment]
На почту можно по которой уже связывались. Мне передадут. Писал письмо руководитель каталога Onliner. Тема: RE: Кондиционеры AlpicAir каталог

**Comment by sidorovich** [comment]
Тогда свяжитесь с Евгением Вербицким, он должен был вести переписку с Вашими коллегами. По идее там должны быть контакты его и он пояснит детальнее концепцию. Возможно лично Вам что-то не передали из документации или устной информации.

**Comment by leonberg** [comment]
Добрый день.

Подскажите, почему ко мне на почту приходит эта переписка?

>Пятница,  2 марта 2018, 17:06 +03:00 от Pavel Sidorovich <notifications@github.com>:
>
>Тогда свяжитесь с Евгением Вербицким, он должен был вести переписку с Вашими коллегами. По идее там должны быть контакты его и он пояснит детальнее концепцию. Возможно лично Вам что-то не передали из документации или устной информации.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .



С уважением, Кирилл Гуринович.

Тел. + 375 29 6704804, e -mail: leonberg@mail.ru

**Comment by sidorovich** [comment]
Здесь же написано:

> You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub , or mute the thread .

Если Вы не подписывались, то тогда это вопрос скорее к GitHub, а не к нам. Рассылки отправляет github.

**Comment by piton66** [comment]
Добрый день. Закинул товар https://catalog.onliner.by/airpurifier/boneco/w200/prices?town=minsk.
Вот ответ. Вроде всё верно.
{"id":"5a9a6c30f92ea104880f1bd2","importerId":10,"fileName":"stock-list-2018-03-03.json","size":138,"date":"2018-03-03 12:34:40","status":"STATUS_WAITING","contentType":"json","statusMessage":null}

Почему в списке предложений у нужного продавца не появляется наличие на складе?

**Comment by piton66** [comment]
сорри. понял. в очереди.

**Comment by piton66** [comment]
Проверку сделал. Вот ответ
{"id":"5a9a6c30f92ea104880f1bd2","importerId":10,"fileName":"stock-list-2018-03-03.json","size":138,"date":"2018-03-03 12:34:40","status":"STATUS_OK","contentType":"json","statusMessage":null} 
в списке предложений у нужного продавца ничего не поменялось.

**Comment by sidorovich** [comment]
Полученный от Вас данные неконсистентны:

Вы передали артикул 7611408016031 для бренда Boneco Air-O-Swiss
А разрешения для ретейлеров передали для бренда Electrolux для УНП 191776121.

Однако, даже если вы передадите резрешение для бренда Boneco Air-O-Swiss в списке предложений все равно ничего не изменится, так как в данный момент ни один магазин, не передает нам артикул 7611408016031 для своих ценовых предложений.

**Comment by sidorovich** [comment]
Данные о наличии это открытый контракт между магазинами и импортером, если магазин не передает артикул, то он не гарантирует, что представленное ценовое предложение относится к тем товарам, которые он у вас закупает.

**Comment by piton66** [comment]
добрый день.  Выгрузили список.
Вот эта номенклатура https://catalog.onliner.by/conditioners/alpicair/awiawo71hpr1c/prices?town=minsk для актив групп.

**Comment by sidorovich** [comment]
Подскажите Ваш ID импортера и в какое время выполнялась выгрузка?

**Comment by piton66** [comment]
Только что . УНП 191776121 . АЙди списка 5ab8f4add535cf7cf14e8ee2.

**Comment by sidorovich** [comment]
ID выгрузки в данном случае не важен. 
Для артикула A2051OUT и производителя AlpicAir не задано соответствие ни с одним из товаров в нашем каталоге. Заявка попала во внутренний отчет о несошедшихся артикулах и операторы каталога в ближайшее время ее обработают. Проблема не является технической.

**Comment by piton66** [comment]
Я говорил об артикуле A071INOUT

**Comment by sidorovich** [comment]
По артикулу A071INOUT в базе данных никакой информации нет.

**Comment by piton66** [comment]
Посмотрите по этой ссылке . https://catalog.onliner.by/conditioners/alpicair/awiawo71hpr1c/prices?town=minsk.  Второй продавец сверху. Возле цены написано Артикул: A071INOUT

**Comment by piton66** [comment]
Сейчас json перепроверю....

**Comment by sidorovich** [comment]
В информации, которую мы получили и обработали от Вас нет ничего об артикуле A071INOUT. Была выгрузка в 2018-03-26 16:25:01 с артикулом A2051OUT, что и отразилось в отчете о несошедшихся. Скорее всего вы нам не передавали артикул A071INOUT. Если вы передавали артикул A071INOUT в одной и той же выгрузке вместе с A2051OUT, то приложите JSON и мы попробуем его проимпортировать сами. Если вы передавали артикул A071INOUT в другой выгрузки - проверьте ее состояние, возможно там были синтаксические ошибки и она не была обработана.
