### ISSUE TITLE
Проблема с выгрузкой через API

### ISSUE THREAD

**Issue by Vtc18** [onlinerby/onliner-b2b-api#55]
Добрый день. Компания Vtc.by (16184) . 2018-04-09 11:46:51 успешно был выгружен прайс лист с актуальными ценами, вопросов по работе не было. После 18-19 часов каким то образом все розничные цены были изменены на оптовые. Выгрузка после  2018-04-09 11:46:51 никто не делал. Сегодня с 8 часов утра пытаюсь выгрузить новый прайс лист вручную и к сожалению безуспешно. 
В чем может быть проблема ? Вот пример позиции Zanussi ZACS-09 HP/A16/N1

**Comment by ptrofimov** [comment]
время обновления этой позиции 2018-04-10 08:31:42

**Comment by sidorovich** [comment]
кусок данных из вашего прайс-листа, который был выгружен в это время
![2018-04-10 10 30 43](https://user-images.githubusercontent.com/3040359/38542353-59b7c652-3caa-11e8-81e5-9100c919b5d7.png)

**Comment by sidorovich** [comment]
доступен по ссылке из вашего личного кабинета
<img width="538" alt="2018-04-10 10 32 03" src="https://user-images.githubusercontent.com/3040359/38542397-7650c976-3caa-11e8-810a-d60c39d030e5.png">

**Comment by Vtc18** [comment]
Это я сегодня руками делал, а сбой произошел сегодня. Вот в чем нюанс

**Comment by sidorovich** [comment]
У нас есть ночная резервная копия базы данных. Она выполнялась в 03:00 по минскому времени. Я посмотрел в ней: 
![2018-04-10 10 41 43](https://user-images.githubusercontent.com/3040359/38542960-ecbf05e0-3cab-11e8-8e02-1cc403364c06.png)
Из него видно, что до 3 ночи сегодняшнего дня позиция не изменялась с 2018-04-09 11:48:06 и ее стоимость была 590,00 BYN

И так резюмирую: мы видим две выгрузки вчера в 11:46:51 с правильной ценой на товар и сегодня в 08:31:39 с неправильной. Между ними не было никаких загрузок, следовательно цена у нас не могла поменяться мистическим образом.

Если у вас есть доказательства этого мистического превращения цены, излагайте, если же нет, готовы ответить на другие конструктивные вопросы и оказать посильное содействие.

**Comment by Vtc18** [comment]
Понял. Спасибо
