### ISSUE TITLE
Onliner B2B API для импортера: Ошибка авторизации

### ISSUE THREAD

**Issue by dmkolt** [onlinerby/onliner-b2b-api#56]
## При выполнении запроса авторизации из "1С:Предприятие 8.2" в ответ получаю сообщение об ошибке валидации полей. Подскажите что я делаю не так?
Попробовал выполнить запрос используя curl, в результате получаю такую же ошибку.
### Детали ниже:
**Пытаюсь выполнить запрос на авторизацию импортера как показано в примере на странице:**
https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/importers/auth.md#%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80-%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%B0-%D0%BD%D0%B0-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8E
**Посылаю следующий запрос (пример с использованием curl):**
`curl -v https://b2bapi.onliner.by/importers/token -H "Accept: application/json" -H "Content-Type: application/json" -d '{"client_id":"96eda0033cbd8ad25***","client_secret":"42087c41f42056b8f65b0b1a3049b334fc4b7***"}'`

**Запрос:**
> POST /importers/token HTTP/1.1
> Host: b2bapi.onliner.by
> User-Agent: curl/7.53.1
> Accept: application/json
> Content-Type: application/json
> Content-Length: 89

**Получаю ответ:**
< HTTP/1.1 422 Unprocessable Entity
< Server: nginx
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< Keep-Alive: timeout=15
< Access-Control-Allow-Origin: *
< Cache-Control: no-cache
< Date: Mon, 21 May 2018 15:27:56 GMT
< Set-Cookie: ouid=snyBDFsC5Xygpkneg8UjAg==; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/
<
{"code":{"id":"validation.failed","text":"Validation failed"},"errors":{"client_id":[{"id":"validation.required","text":"The client_id field is required"},{"id":"validation.string","text":"Value may only be a string"}],"client_secret":[{"id":"validation.required","text":"The client_secret field is required"},{"id":"validation.string","text":"Value may only be a string"}]}}* Connection #0 to host b2bapi.onliner.by left intact

**Comment by ptrofimov** [comment]
Запрос curl -v https://b2bapi.onliner.by/importers/token -H "Accept: application/json" -H "Content-Type: application/json" -d '{"client_id":"96eda0033cbd8ad25***","client_secret":"42087c41f42056b8f65b0b1a3049b334fc4b7***"}' при подстановке правильных client_id & client_secret абсолютно корректен и приводит к выдаче токена.

Ответ сервера, который вы приводите может быть в случае, если не прислано тело запроса или оно содержит некорректный JSON. Проверьте на всякий случай корректность JSON-а https://jsonlint.com/

**Comment by dmkolt** [comment]
> Проверьте на всякий случай корректность JSON-а https://jsonlint.com/
- Проверил, на всякий случай - всё корректно с форматом Json. 

> при подстановке правильных client_id & client_secret абсолютно корректен и приводит к выдаче токена
- т.е. проблема может быть связана с "не правильными" значениями для client_id & client_secret ?

> если не прислано тело запроса
- Поэтому я и решил воспользоваться curl для проверки. Потому как изначально я пытался выполнить запрос средствами 1С: Предприятия и получал в итоге такую же ошибку которую получил используя curl.
Попробовал сделать такой запрос curl:
`curl -D- -X POST --data '{"client_id":"96eda0033cbd8ad25***","client_secret":"42087c41f42056b8f65b0b1a3049b334fc4b7***"}' -H "Content-Type: application/json" -H "Accept: application/json" https://b2bapi.onliner.by/importers/token
`- ошибка такая же...

Может быть всё таки надо передавать в теле запроса  json другого вида? Потому как сейчас действительно или я передаю Json, или пустую строку - в ответ получаю одну и ту же ошибку!
Я передаю такой json в теле запроса:
![image](https://user-images.githubusercontent.com/39492721/40321083-9b486124-5d36-11e8-942a-3942bbe68cbf.png)

**Comment by sidorovich** [comment]
Какая операционная система? Какая версия CURL?

**Comment by dmkolt** [comment]
На самом деле, culr я стал пробовать после того как у меня не получилось выполнить запрос из "1С:Предприятие 8.2". При этом, у меня всё получается без проблем, когда я подключаюсь к магазину (как в этом примере [https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/oauth20.md](https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/oauth20.md))
вы можете привести пример работающего curl запроса, как это сделано на странице по ссылке выше? Я думаю так будет проще всего.

> Какая операционная система? Какая версия CURL?
- windows 10, curl/7.53.1

**Comment by sidorovich** [comment]
запрос, приведенный вами в первом же посте, из нашего окружения вполне работоспособен.
попробуйте вот так:
```
curl -v https://b2bapi.onliner.by/importers/token -H "Accept: application/json;charset=utf-8" -H "Content-Type: application/json;charset=utf-8" -d '{"client_id":"96eda0033cbd8ad25***","client_secret":"42087c41f42056b8f65b0b1a3049b334fc4b7***"}'
```

**Comment by ptrofimov** [comment]
При отправке курлом под виндой json нужно эскейпить специальным образом, чтобы он корректно отправился.
```
curl -v https://b2bapi.onliner.by/importers/token -H "Accept: application/json;charset=utf-8" -H "Content-Type: application/json;charset=u-8" -d "{\"client_id\":\"96eda0033cbd\",\"client_secret\":\"42087c41f420\"}"
```
Подставьте свои client_id & client_secret.

**Comment by dmkolt** [comment]
Спасибо! Сработало! Ура! :)
