### ISSUE TITLE
Вопросы с описанием

### ISSUE THREAD

**Issue by Goldkaras** [onlinerby/onliner-b2b-api#57]
для метода
GET /pricelists/{pricelistId}/status

у вас написан= один из вариантов ответа
STATUS_WAITING Не обработан 
- но по факту всё обработалось без ошибок - наверное это типа "обождите"

но у вас имеется похожий ответ
STATUS_PROCESSING В обработке

- можете их расписать более подробно в каких случаях - возникают STATUS_WAITING

**Comment by sidorovich** [comment]
STATUS_WAITING -  находится в очереди на обработку
STATUS_PROCESSING - задание взято на обработку воркером, происходит парсинг данных, сопоставление товаров, обновление/создание ценовых предложений
