### ISSUE TITLE
Авторизация импортера

### ISSUE THREAD

**Issue by Kleversoft** [onlinerby/onliner-b2b-api#58]
Добрый день! Клиент получил client_id и client_secret и поручил разработку функционала для работы 1С8 Управление торговлей для Беларуси с вашим порталом. Попытка отправки запроса HTTP по адресу https://b2bapi.onliner.by/importers/token приводит к ошибке типа  "Couldn't resolve host name".
Пинг и трассировка также не доступны. Что не так?

**Comment by Olden** [comment]
что-то не так у вас с сетью

**Comment by Kleversoft** [comment]
Добрый, у клиента другая сеть, но такая же ошибка!

**Comment by Olden** [comment]
давайте выводы команд которые вы делаете, которыми проверяете...

**Comment by Kleversoft** [comment]
ping b2bapi.onliner.by/importers/token

**Comment by Olden** [comment]
> ping b2bapi.onliner.by/importers/token

так конечно же нигде работать не будет

**Comment by Kleversoft** [comment]
А как проверить?

**Comment by Olden** [comment]
ping b2bapi.onliner.by

**Comment by Kleversoft** [comment]
C:\Users\Asus-PC>ping b2bapi.onliner.by

Обмен пакетами с b2bapi.onliner.by [178.124.129.16] с 32 байтами данных:
Превышен интервал ожидания для запроса.
Превышен интервал ожидания для запроса.
Превышен интервал ожидания для запроса.
Превышен интервал ожидания для запроса.

Статистика Ping для 178.124.129.16:
    Пакетов: отправлено = 4, получено = 0, потеряно = 4
    (100% потерь)

**Comment by Olden** [comment]
скажите ваш IP

**Comment by Kleversoft** [comment]
172.27.24.253

**Comment by Kleversoft** [comment]
C:\Temp>curl -uff***fc076b735d1ebf7:a7d0d***606c359135ce5f1db71a87f6e804f027\-H'Accept:application/json' -d'grant_type=client_credentials' -o responce.txt https://b2bapi.onliner.by/oauth/token

**Comment by Kleversoft** [comment]
Пытаюсь посмотреть ответ выведенный в файл - он пустой!

**Comment by Kleversoft** [comment]
И беда заключается в том, что у клиента curl на сервере не установлен...

**Comment by Kleversoft** [comment]
И ответ такой:   
% Total % Received % Xferd  Average Speed Time Time Time Current Dload Upload Total Spent Left Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

**Comment by Olden** [comment]
> 172.27.24.253

укажите пожалуйста не локальный адрес в вашей внутренней сети, а внешний

**Comment by Olden** [comment]
@Kleversoft например вот так
```
curl -s https://serverok.org
```

**Comment by Kleversoft** [comment]
100.92.75.21

**Comment by Olden** [comment]
этот адрес относится к ipv4 address space и не может быть адресом сервера с которого он делает запросы.

**Comment by Kleversoft** [comment]
Где посмотреть?

**Comment by Kleversoft** [comment]
может быть этот: 10.141.232.29

**Comment by Olden** [comment]
curl -s https://serverok.org

приведите полный вывод этой команды

**Comment by Kleversoft** [comment]
93.85.145.15 [BY/]

**Comment by Olden** [comment]
Ваш ip не заблокирован, и более того мы видим от вас запросы. Разбирайтесь в проблеме...
![2018-06-22 19 15 44](https://user-images.githubusercontent.com/546682/41787353-d25d44c6-7650-11e8-9db0-f28caf21dd38.jpg)

**Comment by sidorovich** [comment]
код ответа 415 Unsupported Media Type - проверяйте заголовки Accept и Content-Type. должны быть `application/json`

**Comment by Kleversoft** [comment]
Павел! Спасибо Вам!

Вы – супер!

 

С уважением,

Директор ООО «Клеверсофт»

Вячеслав Санько

e-mail: cleversoft <mailto:cleversoft@tut.by> @tut.by

skype: Вячеслав Санько

+375 29 6266515

**Comment by Kleversoft** [comment]
Павел! Спасибо Вам!
Вы – супер!
Все срослось!

**Comment by Kleversoft** [comment]
Здравствуйте!
Пытаюсь получить  отчет по сопоставленным товарам импортера, ответ:
{"id":"5b3356599d29c90cad257b42","importerId":29,"createdAt":"2018-06-27T12:18:17+03:00","updatedAt":"2018-06-27T12:18:18+03:00","status":"completed","report":[]}
- пустой, импортер говорит, что товары на портал размещал...
Такли это?

**Comment by sidorovich** [comment]
все нормально, у импортера за номером 29 0 сопоставленных статусов.
