### ISSUE TITLE
отчет по сопоставленным товарам импортера

### ISSUE THREAD

**Issue by Kleversoft** [onlinerby/onliner-b2b-api#59]
Здравствуйте!
Пытаюсь получить отчет по сопоставленным товарам импортера, ответ:
{"id":"5b3356599d29c90cad257b42","importerId":29,"createdAt":"2018-06-27T12:18:17+03:00","updatedAt":"2018-06-27T12:18:18+03:00","status":"completed","report":[]}

пустой, импортер говорит, что товары на портал размещал...
Так ли это?

**Comment by sidorovich** [comment]
давайте разберемся с терминологией: "импортер" в данном случае для нас вы. очень странно, что вы говорить о себе в третьем лице. это вносит некоторый сумбур.

в данный момент в нашей базе, у импортера за номером 29 - 0 сопоставленных статусов.
логирование запросов об отправке статусов наличия мы не производим, так как есть метод, который позволяет узнать состояние той или иной выгрузки статусов наличия.

**Comment by Kleversoft** [comment]
хорошо, а для чего тогда предназначен этот отчет?

**Comment by sidorovich** [comment]
какой именно? какой метод нашего API вы сейчас имеете ввиду?

**Comment by Kleversoft** [comment]
имею ввиду вот этот: onliner-b2b-api/docs/importers/match_report_get.md

**Comment by sidorovich** [comment]
в этот отчет, попадают ценовые предложения от магазинов, которые указаны импортером как ретейлеры, на те товары, на которые импортер указал статус наличия.

при этом магазин должен привязывать свои ценовые предложения по артикулу по которому был передан статус наличия от импортера.

конкретно в вашем случае - 0 статусов наличия. такое возможно, если были ошибки в выгрузке статусов наличия, либо если у нас нет товаров, связанных с переданными артикулами. 

проверяйте результаты выгрузки статусов наличия, используя метод https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/importers/status.md

а также проверяйте результаты выгрузки списка импортеров, используя метод https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/importers/retailers_status.md
