### ISSUE TITLE
ошибка при загрузки прайс листа

### ISSUE THREAD

**Issue by e-mogilev** [onlinerby/onliner-b2b-api#60]
магазин e-mogilev.by при загрузки пишет

**Comment by e-mogilev** [comment]
Отчет об импорте прайс-листа "price-list2018-06-26.json"
Не удалось импортировать файл. Невалидный json.

**Comment by Olden** [comment]
А вопрос в чем?

**Comment by e-mogilev** [comment]
Невалидный json.   а в чем у нас ошибка? что это значит?

**Comment by Olden** [comment]
в том что вы передаете нам нечто, что не является json'ом

**Comment by Olden** [comment]
http://json.parser.online.fr можете проверить ваш json тут например

**Comment by e-mogilev** [comment]
спс

**Comment by e-mogilev** [comment]
пробовал загрузить ваш пример - ругается на модель товара.     Откуда брать наименование модели?
MP3-плееры | Apple | MP3 плеер Apple iPod nano 16Gb (7th generation) |   | 1 | 20.00 | BYN | Ваш комментарий | Foxconn,No.2,2nd Donghuan Road,10th Yousong Industrial District,Longhua,Baoan,Shenzhen City,Guangdong Province,China | ООО Музтрейд, г.Минск, ул. Кропоткина, 12 ООО Плеерсервис, г.Гомель, ул. Платонова, 16 | ООО Музсервис, г.Минск, ул. П. Бровки, 5 ООО Плеерсервис, г.Гомель, ул. Платонова, 16 | 12 | нет | нет | 36 | По городу 1 дней 1.00 руб.По стране 5 дней 2.00 руб. | in_stock | Неверно указана или не указана модель товара
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by ptrofimov** [comment]
На странице "Импорт Экспорт" в админке есть ссылка "Структура каталога Onliner (xml)". Названия товаров лучше всего брать из структуры каталога.

**Comment by e-mogilev** [comment]
спасибо но все равно не все понятно.

**Comment by ptrofimov** [comment]
Пишите конкретные вопросы.

**Comment by e-mogilev** [comment]
я исправил...... уже

**Comment by ptrofimov** [comment]
Связи между ссылкой и названием товара в структуре каталога нет. Не совсем понятно, зачем ваши товары было привязывать к ссылке.
И кстати, не забывайте, что можно указывать не название а артикул товара. Он у всех одинаковый, и их можно получать от импортеров.

**Comment by e-mogilev** [comment]
спасибо, а возможно для нас разово в помощь сделать таблицу соответствия вашей ссылке вашему коду, У нас товара 200 000 . работы очень много. 18 поставщиков, не все артикулы дают. Или какой нить другой инструмент для создания таблицы соответствия ссылка - ID. ?

**Comment by ptrofimov** [comment]
Каким образом вы получили 200 тысяч ссылок на страницы нашего каталога?

**Comment by e-mogilev** [comment]
200 тысяч ссылок было создано вручную за последние 2-3 года, мы не знали про апи.
нам нужен инструмент как получить либо имя либо артикул.

**Comment by Olden** [comment]
прикрепите сюда csv файл с этими ссылками, мы посмотрим, что можно с этим сделать.

**Comment by e-mogilev** [comment]
это связи на товары которые есть в нашем каталоге.

**Comment by ptrofimov** [comment]
Если csv нельзя прикрепить, переименуйте в .txt

**Comment by e-mogilev** [comment]
а возможно добавить в структуру каталога https://content.onliner.by/catalog/structure.xml
ссылку на товар???   Мы бы оттуда и забрали модели и производителей для выгрузки.

**Comment by Olden** [comment]
> а возможно добавить в структуру каталога https://content.onliner.by/catalog/structure.xml
ссылку на товар??? Мы бы оттуда и забрали модели и производителей для выгрузки.

нельзя

**Comment by e-mogilev** [comment]
а если мы дадим вам свой файл с ссылками а вы проставите модели и производителей .  возможно?

**Comment by Olden** [comment]
> прикрепите сюда csv файл с этими ссылками, мы посмотрим, что можно с этим сделать.

мы уже написали вам

**Comment by e-mogilev** [comment]
[file.txt](https://github.com/onlinerby/onliner-b2b-api/files/2162708/file.txt)
вот все наши связи к онлайнеру в нашей базе.

**Comment by sidorovich** [comment]
[report.xlsx](https://github.com/onlinerby/onliner-b2b-api/files/2163091/report.xlsx)
[errors.log](https://github.com/onlinerby/onliner-b2b-api/files/2163094/errors.log)

**Comment by e-mogilev** [comment]
на контроллере /pricelists - 413 ошибка при попытке загрузки прайса (выгружаю 67850066 байт). 
может слишком большой размер?

**Comment by Olden** [comment]
> на контроллере /pricelists - 413 ошибка при попытке загрузки прайса (выгружаю 67850066 байт).
может слишком большой размер?

вы правы, грузите до 50мб за раз

**Comment by e-mogilev** [comment]
а при загрузке следующего файла предыдущий разве не удаляется?

**Comment by Olden** [comment]
PUT - полностью замещает все что было загружено до этого, PATCH - обновляет или изменяет

**Comment by e-mogilev** [comment]
спс
