### ISSUE TITLE
Получение результата импорта наличия товаров

### ISSUE THREAD

**Issue by Kleversoft** [onlinerby/onliner-b2b-api#61]
Здравствуйте!
Попытки Обновить наличие товаров увенчались успехом, однако последующие попытки получения результата импорта наличия товаров (GET /importers/stocklists/5b3f36f8dbf3ec47d94f0a42/status) завершаются ошибкой 404, что означает "некорректность идентификатора", что не так?

**Comment by sidorovich** [comment]
некорректный идентификатор загрузки - 5b3f36f8dbf3ec47d94f0a42
попробуйте еще раз произвести обновление наличия с использованием метода PUT|PATCH /importers/stocklists и приложите сюда тело нашего ответа и код статуса. идентификатором загрузки будет поле id в ответе.

**Comment by Kleversoft** [comment]
{"id":"5b3f413b26ece2aa0c181de2","importerId":29,"fileName":"stock-list-2018-07-06.json","size":1301,"date":"2018-07-06 13:15:23","status":"STATUS_WAITING","contentType":"json","statusMessage":null}

Так и отправляю с этим id

**Comment by Kleversoft** [comment]
Может, слишком рано - сразу после загрузки? Как скоро имеет смысл снова проверять статус?

**Comment by sidorovich** [comment]
Проверяйте авторизационный токен, который используете при отправке запроса на получение статуса! Возможно он истек! Информация о загрузке 5b3f413b26ece2aa0c181de2 содержится в базе. С ней все хорошо, она успешно обработана. 

Если не справитесь сами - приложите токен, с которым выполняете запрос на получение статуса загрузки, а также точное серверное время данного запроса (напоминаю, что токен имеет срок жизни и его нужно периодически обновлять)

**Comment by Kleversoft** [comment]
Токен: eyJ0eXAiOiJKV1MiLCJhbGciOiJIUzUxMiJ9.eyJ1c2VyX3R5cGUiOiJpbXBvcnRlcl9hcGkiLCJ1c2VyX2RhdGEiOnsiaWQiOjI5fSwiaWF0IjoxNTMwODkyNTk3LCJzY29wZXMiOltdLCJleHAiOjE1MzA4OTMxOTd9.aI8DHJltQ4Snhso3JesK1YNAYAGJOuopD1igi009wKGpiuy3Ic9SfBXVDbx35Vn_4UVPvUVJG9hsIES9SRCfwg
Серверное время 18.57

**Comment by Kleversoft** [comment]
Павел, здравствуйте! Я вчера отправил токен и время, посмотрите, пожалуйста!

**Comment by sidorovich** [comment]
Токен выдан в 06/07/2018 18:56:37 GMT+3, действителен до 06/07/2018 19:06:37 GMT+3
Время запроса попадает в интервал времени действия токена. 
Завтра в рабочем порядке попробуем что-нибудь придумать.

**Comment by sidorovich** [comment]
не могу воспроизвести вашу проблему. проверяйте корректность токена
запросы выполнял с помощью curl в ubuntu

```
curl -X POST https://b2bapi.onliner.by/importers/token -H "Content-Type: application/json" -H "Accept: application/json" -d '{"client_id": "%YOUR_CLIENT_ID%", "client_secret": "%YOUR_CLIENT_SECRET%"}'

{"access_token":"eyJ0eXAiOiJKV1MiLCJhbGciOiJIUzUxMiJ9.eyJ1c2VyX3R5cGUiOiJpbXBvcnRlcl9hcGkiLCJ1c2VyX2RhdGEiOnsiaWQiOjI5fSwiaWF0IjoxNTMxMTQ3MjU4LCJzY29wZXMiOltdLCJleHAiOjE1MzExNDc4NTh9.PHrthg1gLLlEshD_QgvMcz1_jtQhdcbFv1peGRJdtssZSFTN8SmsMu83aiRJuTyKU-XqVeF29C0HhjNPvw91Fw","expires_in":600,"token_type":"Bearer"}

curl -X GET https://b2bapi.onliner.by/importers/stocklists/5b3f413b26ece2aa0c181de2/status -H "Accept: application/json" -H "Alcl9hcGkiLCJ1c2VyX2RhdGEiOnsiaWQiOjI5fSwiaWF0IjoxNTMxMTQ3MjU4LCJzY29wZXMiOltdLCJleHAiOjE1MzExNDc4NTh9.PHrthg1gLLlEshD_QgvMcz1_jtQhdcbFv1peGRJdtssZSFTN8SmsMu83aiRJuTyKU-XqVeF29C0HhjNPvw91Fw"

{"id":"5b3f413b26ece2aa0c181de2","importerId":29,"fileName":"stock-list-2018-07-06.json","size":1301,"date":"2018-07-06 13:15:23","status":"STATUS_OK","contentType":"json","statusMessage":null}
```
