### ISSUE TITLE
страница настройки OAuth-приложения

### ISSUE THREAD

**Issue by Kleversoft** [onlinerby/onliner-b2b-api#62]
Здравствуйте! Где найти параметры для авторизации Client ID и Client Secret со страницы настройки OAuth-приложения для магазина.

**Comment by ptrofimov** [comment]
Здравствуйте. Client ID и Client Secret можно узнать на странице Импорт/Экспорт в админке b2b.onliner.by

**Comment by Kleversoft** [comment]
Добавлю для тех, кто будет искать: Нужно ввести название приложения и нажать кнопку "сохранить приложение"
