### ISSUE TITLE
Определение товара по id

### ISSUE THREAD

**Issue by Goldkaras** [onlinerby/onliner-b2b-api#63]
каждого вашего товара имеется ID, планируете ли и когда если планируете - в качестве определения товара использовать его id. 
 Предыстория такова - продавцы на создавали товары без указания артикула, например
category:Полотенцесушители  
vendor:Gloss&Reiter
model:Liza 50x100 нижний подвод (Л.50х100.Л2.Z3) 
article:null 
id:792866

и теперь необходимо везде заполнять артикула - хотя артикул и наиvенование на 99% совпадают
Л.50х100.Л2.Z3
а если была бы возможность обновлять состояние остатков по id было бы супер

**Comment by ptrofimov** [comment]
Если нет артикулов, вы можете обновлять цены указывая раздел, производителя и название товара, которые у вас есть.

**Comment by Goldkaras** [comment]
мне не надо обновлять цены, мне в качестве производителя  - необходимо указывать наличие товара. Т.е. я выступаю в качестве "импортера" по вашей терминологии

**Comment by ptrofimov** [comment]
Я понял. Напишите название импортера и телефон, по которому с вами можно связаться.

**Comment by Goldkaras** [comment]
ООО "Глосс энд Рейтер"
+375 29 3 284 525 Еловик Юрий Леонидович
