### ISSUE TITLE
Onliner API для импортеров HTTP/1.1 401 Unauthorized при выполнении любого метода

### ISSUE THREAD

**Issue by Goldkaras** [onlinerby/onliner-b2b-api#64]
Получил Token
https://b2bapi.onliner.by/importers/token

Далее при вызове любого метода (проверял на: 
    (PUT importers/retailers)
    (GETimporters/retailers/"+retailerListId+"/status) 
    (POST importers/match-reports/requests)
возвращает ошибку
HTTP/1.1 401 Unauthorized

везде прописал
Accept = "application/json"
ContentType = "application/json"
 Authorization = "Bearer  eyJ0eXAiOiJKV1MiLCJhbGciOiJIUzUxMiJ9.eyJ1c2VyX3R5cGUiOiJpbXBvcnRlcl9hcGkiLCJ1c2VyX2RhdGEiOnsiaWQiOjI4fSwiaWF0IjoxNTMyODcyMDcxLCJzY29wZXMiOltdLCJleHAiOjE1MzI4NzI2NzF9.XSqAOEtVy1aIR1osq70aLM_rxr1WrfF6t_yxMwmlz3ANNAL5bSg8Le4u1UBLS_AIrjFEiH79dYOHvISizo_Zog"

фирма Gloss&Reiter
client_id = 2943d1b1f64f74fd????
client_secret = b742d944cc88d6fec76fc35563b4cfdb8247????

**Comment by ptrofimov** [comment]
Возможно, истекло время действия токена. Токен выдается на 10 минут. Попробуйте получить токен еще раз и сразу же выполнить запрос.

**Comment by Goldkaras** [comment]
Я выполняю команд сразу после получения токена
только токен в вашем примере 149 символов мне возвращается 252

**Comment by Goldkaras** [comment]
для магазинов делал - всё работает

**Comment by ptrofimov** [comment]
На вид все норм. Сделайте запрос с токеном через курл (curl -v) и пришлите дамп запроса/ответа.

**Comment by Goldkaras** [comment]
никогда курл-ом не пользовался, пришлите пример что ли

**Comment by ptrofimov** [comment]
![risovach ru](https://user-images.githubusercontent.com/867178/43390728-98f3210a-93f7-11e8-9125-3a62ada1923d.jpg)

**Comment by ptrofimov** [comment]
Выполните в консоли терминала
```
curl -X PUT 'https://b2bapi.onliner.by/importers/retailers' -H 'Accept: application/json' -H 'Authorization: Bearer <подставьте ваш токен>' -v
```
и напишите в комментарии вывод этой команды.

**Comment by Goldkaras** [comment]
C:\Users\karas>curl -X PUT "https://b2bapi.onliner.by/importers/retailers" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer eyJ0eXAiOiJKV1MiLCJhbGciOiJIUzUxMiJ9.eyJ1c2VyX3R5cGUiOiJpbXBvcnRlcl9hcGkiLCJ1c2VyX2RhdGEiOnsiaWQiOjI4fSwiaWF0IjoxNTMyOTc1MzA3LCJzY29wZXMiOltdLCJleHAiOjE1MzI5NzU5MDd9.CFq5qE6rFi-Nt1v7_8ysA71DxxxhGlGyvUk_Nc3Ixima7vRnuLRZS65pu-aEVAYmoz1fWWJKbzpInxFjA3PLqA" -v
*   Trying 178.124.129.16...
* TCP_NODELAY set
* Connected to b2bapi.onliner.by (178.124.129.16) port 443 (#0)
* schannel: SSL/TLS connection with b2bapi.onliner.by port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 182 bytes...
* schannel: sent initial handshake data: sent 182 bytes
* schannel: SSL/TLS connection with b2bapi.onliner.by port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with b2bapi.onliner.by port 443 (step 2/3)
* schannel: encrypted data got 4096
* schannel: encrypted data buffer: offset 4096 length 4096
* schannel: encrypted data length: 4022
* schannel: encrypted data buffer: offset 4022 length 4096
* schannel: received incomplete message, need more data
* schannel: SSL/TLS connection with b2bapi.onliner.by port 443 (step 2/3)
* schannel: encrypted data got 1024
* schannel: encrypted data buffer: offset 5046 length 5046
* schannel: encrypted data length: 234
* schannel: encrypted data buffer: offset 234 length 5046
* schannel: received incomplete message, need more data
* schannel: SSL/TLS connection with b2bapi.onliner.by port 443 (step 2/3)
* schannel: encrypted data got 113
* schannel: encrypted data buffer: offset 347 length 5046
* schannel: sending next handshake data: sending 126 bytes...
* schannel: SSL/TLS connection with b2bapi.onliner.by port 443 (step 2/3)
* schannel: encrypted data got 258
* schannel: encrypted data buffer: offset 258 length 5046
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with b2bapi.onliner.by port 443 (step 3/3)
* schannel: stored credential handle in session cache
> PUT /importers/retailers HTTP/1.1
> Host: b2bapi.onliner.by
> User-Agent: curl/7.55.1
> Accept: application/json
> Content-Type: application/json
> Authorization: Bearer eyJ0eXAiOiJKV1MiLCJhbGciOiJIUzUxMiJ9.eyJ1c2VyX3R5cGUiOiJpbXBvcnRlcl9hcGkiLCJ1c2VyX2RhdGEiOnsiaWQiOjI4fSwiaWF0IjoxNTMyOTc1MzA3LCJzY29wZXMiOltdLCJleHAiOjE1MzI5NzU5MDd9.CFq5qE6rFi-Nt1v7_8ysA71DxxxhGlGyvUk_Nc3Ixima7vRnuLRZS65pu-aEVAYmoz1fWWJKbzpInxFjA3PLqA
>
* schannel: client wants to read 102400 bytes
* schannel: encdata_buffer resized 103424
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: encrypted data got 580
* schannel: encrypted data buffer: offset 580 length 103424
* schannel: decrypted data length: 551
* schannel: decrypted data added: 551
* schannel: decrypted data cached: offset 551 length 102400
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: decrypted data buffer: offset 551 length 102400
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 551
* schannel: decrypted data buffer: offset 0 length 102400
< HTTP/1.1 202 Accepted
< Server: nginx
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< Keep-Alive: timeout=15
< Access-Control-Allow-Origin: *
< Cache-Control: no-cache
< Date: Mon, 30 Jul 2018 18:29:56 GMT
< Set-Cookie: ouid=snyBEFtfWSQtUmgxTootAg==; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/
<
{"id":"5b5f59242f7cc6258d61b622","importerId":28,"fileName":"retailer-list-2018-07-30.json","size":0,"date":"2018-07-30 21:29:56","status":"STATUS_WAITING","contentType":"json","statusMessage":null,"errors":[]}* Connection #0 to host b2bapi.onliner.by left intact

**Comment by Goldkaras** [comment]
Проблема есть, вопрос - вы поможете решить или нет? Вы же видите что к Вам приходит, так посмотрите что не так приходит. А тая я и без Вас видел что по curl-у отработало

**Comment by ptrofimov** [comment]
В самом начале вы написали, что наше API возвращает 401-ю ошибку для правильного токена, то есть работает неправильно. С помощью курла мы убедились, что на самом деле это не так. Соответственно, проблема в том коде, который вы написали. Показывайте тогда код.

**Comment by Goldkaras** [comment]
1)Такой же код для обновления данных по магазину работает, и токен срабатывает
2)Вот кусок который относится к данном вопросу  - не знаю что он вам скажет
	Http_vk = СоздатьОбъект("AddIn.Http_VK");
	Http_vk.Accept = "application/json";
	Http_vk.ContentType = "application/json";
	Http_vk.SetHeader("Authorization","Bearer "+Токен);
	Http_vk.BasicAuthentication = 1;

	Http_vk.PutSSLmode("https://b2bapi.onliner.by/importers/retailers",ДанныеЗапроса,ТекстОтвета,"Текст","Текст");

3)Вы может посмотреть что к Вам приходит от меня или нет?

**Comment by ptrofimov** [comment]
Уберите строку Http_vk.BasicAuthentication = 1; или поставьте Http_vk.BasicAuthentication = 0;

**Comment by Goldkaras** [comment]
то же самое
вот токен "eyJ0eXAiOiJKV1MiLCJhbGciOiJIUzUxMiJ9.eyJ1c2VyX3R5cGUiOiJpbXBvcnRlcl9hcGkiLCJ1c2VyX2RhdGEiOnsiaWQiOjI4fSwiaWF0IjoxNTMzMDMyODY3LCJzY29wZXMiOltdLCJleHAiOjE1MzMwMzM0Njd9.1a4MTvHqBIM8XtlXVRWIZ7VwRQOiU2z6Ob3PC6Yv3Nz8pYl5h2EWbmV4IdPVCm3XlMkDzYD1N8XB1UzMrUqhYw"
только что ушел к Вам запрос, гляньте что не так доходит

**Comment by ptrofimov** [comment]
Замените урл с "https://b2bapi.onliner.by/importers/retailers" на "http://requestbin.fullcontact.com/15bz8oq1" и выполните запрос. И я увижу все заголовки.

**Comment by ptrofimov** [comment]
Все понятно. Приходит вот такой запрос 
```http
Accept: application/json
User-Agent: Mozilla/3.0 (compatible; Indy Library)
Cloudfront-Is-Desktop-Viewer: true
Cloudfront-Viewer-Country: BY
Cloudfront-Is-Smarttv-Viewer: false
X-Request-Id: f048d35f-3ee1-4567-8532-991b6adbb5b5
Connection: close
Accept-Encoding: identity
Content-Length: 58
Cloudfront-Is-Mobile-Viewer: false
Via: 1.1 465e661d27b2b6a1c349a5550c745b0f.cloudfront.net (CloudFront), 1.1 vegur
Authorization: Basic Og==
Cloudfront-Forwarded-Proto: http
Cloudfront-Is-Tablet-Viewer: false
X-Amz-Cf-Id: dZdvIMpR9AMRSQ_uZuqAgjHtdGhhnqw1nQFiC8NqgWc077K75v3GEw==
Host: requestbin.fullcontact.com
Connect-Time: 1
Total-Route-Time: 0
Content-Type: application/json
```
```json
{"retailers": [{"unp": "190319225"},{"unp": "192256860"}]}
```

Приходит Authorization: Basic вместо Authorization: Bearer с токеном. Ищите, как в вашем http модуле отключить Authorization: Basic либо найдите другой модуль для отправки запросов.

**Comment by Goldkaras** [comment]
спасибо, понятно где искать

**Comment by Goldkaras** [comment]
Причина была в следующем (для Delphi), в компоненте  TIdHTTP 
свойство Request.CustomHeaders.FoldLines равнялось true, надо было поставить в false
иначе делило заголоовки

**Comment by ptrofimov** [comment]
Если теперь все работает, то отлично.
