### ISSUE TITLE
Загрузка прайс-листа

### ISSUE THREAD

**Issue by Kleversoft** [onlinerby/onliner-b2b-api#65]
Здравствуйте! Помогите разобраться, что не так с загрузкой прайс-листа с ID 5b642c14dbf3ec79ac31fd02, сообщение об ошибке: 

date | "2018-08-03 13:19:00"
errorsCount | 0
id | "5b642c14dbf3ec79ac31fd02"
processedCount | 0
shopId | 12 222
statusCode | "STATUS_PARSE_ERROR"
statusText | "Ошибка валидации"

**Comment by ptrofimov** [comment]
Добрый день. Нарушен формат данных. Вы json используете?

**Comment by Kleversoft** [comment]
Да. json

**Comment by ptrofimov** [comment]
Проверьте правильность синтаксиса JSON. Если online сервис: https://jsonlint.com/

**Comment by Kleversoft** [comment]
Скажите, а после заливки нового прайса, через какое время изменятся значения реквизитов, такие как stockStatus, deliveryTownTime, deliveryTownPrice и т. п.?

**Comment by ptrofimov** [comment]
В течение 10 минут.

**Comment by Kleversoft** [comment]
Прошло уже много больше, состояние не изменилось!

**Comment by ptrofimov** [comment]
Напишите, какой товар смотреть и какое значение должно быть.

**Comment by Kleversoft** [comment]
Здравствуйте! Чтобы легче было искать: в пятницу, 3.08.2018 около 16.00 был отправлен файл, в котором по всем товарам установлено значение is cashless = "да"

**Comment by Kleversoft** [comment]
Здравствуйте! А это правильно два дня ждать ответ?

**Comment by Olden** [comment]
Добрый день, извиняюсь за задержку. около 16 было у вас много загрузок, если можете выполните загрузку прямо сейчас и я проверю

**Comment by Kleversoft** [comment]
Ок!

**Comment by Kleversoft** [comment]
Отправил, ID 5b6abbee9d29c9408421b5c2, статус: STATUS_OK

**Comment by Olden** [comment]
[price-list2018-08-08.txt](https://github.com/onlinerby/onliner-b2b-api/files/2269773/price-list2018-08-08.txt)

вот что вы нам отправляете)) почему-то не выдаем ошибку валидации, но факт в том, что тут нечего обрабатывать

**Comment by Olden** [comment]
новая загрузка: Не удалось импортировать файл. Невалидный json.

**Comment by Olden** [comment]
вы убрали запятую, но там по прежнему невалидный json

**Comment by Kleversoft** [comment]
Александр, скажите, а что за код у символа - разделителя в JSON "EOF"?

**Comment by Kleversoft** [comment]
Проверьте сейчас, отправил валидный JSON

**Comment by Olden** [comment]
с точки зрения  json все валидно
Успешно импортировано 2 из 330 записей

**Comment by Kleversoft** [comment]
Почему остальные неуспешно?

**Comment by Olden** [comment]
в админке есть кнопка отчет возле каждого импорта, там все написано

**Comment by Kleversoft** [comment]
Спасибо! Все получилось!
