### ISSUE TITLE
Onliner API для импортеров - обновление наличия товара

### ISSUE THREAD

**Issue by Goldkaras** [onlinerby/onliner-b2b-api#66]
Два вопроса:
1)отправил запрос на обновления наличия товара - внутренность запроса была неправильная 
в течении суток возвращает мне что находится в обработке(STATUS_PROCESSING), хотя по идее должен был выругаться

{"id":"5b64c5572f7cc6bc442eb632","importerId":28,"fileName":"stock-list-2018-08-04.json","size":33736,"date":"2018-08-04 00:12:55","status":"STATUS_PROCESSING","contentType":"json","statusMessage":null}

2)Отправляю уже правильный запрос (как я думаю) возвращает всё тоже (STATUS_PROCESSING)
возможно связано с представлением "&", я его представлял как "\u0026" и ""\U0026
 и "&amp;" и без всякого преобразования отсылал, все одно и то же
вот пример одноги из запросов 
[{"product": {"manufacturer": "Gloss \u0026 Reiter","article": "Л.50х60.К6 (1\")","ean13": "4814995008165"},"stock": {"status": "in_stock"},"recommended_retail_price": {"amount": "345.77","currency": "BYN"},"package": {"width": "610 мм","length": "150 мм","height": "54 мм","weight": "6200г"}}]

и один и то же ответ "STATUS_PROCESSING"
"id":"5b66d0102f7cc6b6720e0342","importerId":28,"fileName":"stock-list-2018-08-05.json","size":294,"date":"2018-08-05 13:23:12","status":"STATUS_PROCESSING","contentType":"json","statusMessage":null}

**Comment by Goldkaras** [comment]
прошли сутки а запрос все обрабатывается
{"id":"5b64c5572f7cc6bc442eb632","importerId":28,"fileName":"stock-list-2018-08-04.json","size":33736,"date":"2018-08-04 00:12:55","status":"STATUS_PROCESSING","contentType":"json","statusMessage":null}

**Comment by ptrofimov** [comment]
Добавили доплоггирование ошибок. Отправьте запрос еще раз.

**Comment by ptrofimov** [comment]
Detected invalid UTF-8 for fieldname "statusMessage": Syntax error in "{"product": {"manufacturer": "Gloss \U0026 Reiter","article": "�.50�60.�6 (1\")","ean13": "481499500"

**Comment by Goldkaras** [comment]
Переделал запрос, в виде
[{"product": {"manufacturer": "Gloss \u0426 Reiter","article": "\u04cb. 50\u04f560.\u04ca6.G1","ean13": "4814995008165"},"stock": {"status": "in_stock"},"recommended_retail_price": {"amount": "345.77","currency": "BYN"},"package": {"width": "610 \u04ec\u04ec","length": "150 \u04ec\u04ec","height": "54 \u04ec\u04ec","weight": "6200\u04e3"}}]

он уходит и возвращает статус что обработан
{"id":"5b6b525f2f7cc654440c5292","importerId":28,"fileName":"stock-list-2018-08-08.json","size":342,"date":"2018-08-08 23:28:15","status":"STATUS_OK","contentType":"json","statusMessage":null}

, но отчёт по сопоставленным товарам возвращает пустоту
{"id":"5b6b52739d29c9717a2c8312","importerId":28,"createdAt":"2018-08-08T23:28:35+03:00","updatedAt":"2018-08-08T23:29:24+03:00","status":"completed","report":[]}

**Comment by sidorovich** [comment]
А вот эта строка "\u04cb. 50\u04f560.\u04ca6.G1" это вы ее где-то взяли или какой текст подразумевается? Если что, то данный артикул не сопоставился и ушел операторам нашего каталога на проверку.

Сейчас в нашей базе от вас в отчете о несошедшихся артикулах находится следующее:

| Производитель | Артикул |
|---|---| 
|  Gloss \u0426 Reiter | \u04cb. 50\u04f5100.\u04ca9.G1 |
| Gloss Ц Reiter | Ӌ. 50ӵ100.ӊ9.G1 |
| Gloss Ц Reiter | Ӌ. 50ӵ60.ӊ6.G1 |

**Comment by Goldkaras** [comment]
всё получилось, спасибо.
