### ISSUE TITLE
Неверный формат ответа при обновлении позиции магазина

### ISSUE THREAD

**Issue by julia-korotkina** [onlinerby/onliner-b2b-api#67]
Здравствуйте.

При обновлении позиции магазина с определённым id ответ приходит не в формате, который указан в вашей документации (то есть [{"id": myID, "dateUpdate":"2013-01-01 12:00:00"}]), а следующий:
[{"all":"2018-08-06 17:25:15"}]

То есть вместо обновления одной позиции происходит обновление всех.
Пример запроса:

https://b2bapi.onliner.by/pricelist/3600342293/renew?access_token=...

Код, формирующий запрос к серверу:

$process = curl_init("https://b2bapi.onliner.by/pricelist/3600342293/renew?access_token=..."); 
curl_setopt($process, CURLOPT_HTTPHEADER, array('Accept: application/json'));
curl_setopt($process, CURLOPT_CUSTOMREQUEST, "PUT");
$result_access = curl_exec($process);
curl_close($process);

Могли бы вы объяснить, почему так происходит и как исправить?

**Comment by sidorovich** [comment]
Воспользуйтесь HTTP-методом PATCH
```php
curl_setopt($process, CURLOPT_CUSTOMREQUEST, "PATCH");
```

**Comment by sidorovich** [comment]
Сейчас посмотрим.

**Comment by sidorovich** [comment]
Похоже, что есть проблема с формированием ответа, в случае передаче списка, состоящего только из одной позиции. Фактически выполняется обновление только указанной позиции, но ответ формируется иначе.

Отметим данный случай в документации. Рассмотрим вопрос об изменении API. Спасибо!

**Comment by julia-korotkina** [comment]
Хорошо, спасибо большое!

**Comment by julia-korotkina** [comment]
Добрый день.

1. Возник ещё один вопрос по ответам с сервера при использовании запросов /pricelist/renew и /pricelist/{id}/renew. В документации указано, что при запросе  /pricelist/renew без параметров, если список id не получен, то ответ будет:
HTTP/1.1 400 Bad Request
{
    "errors": {
        "Positions id list is required and must not be empty"
    }
}

У меня при таком запросе происходит обновление всех позиций магазина, то есть тот же самый ответ, что и при /pricelist/all/renew.

2. Могли бы вы привести пример правильного оформления запроса со списком id через curl?

**Comment by sidorovich** [comment]
1. Да, ошибка в документации. Судя по коду выполняется полное обновление.

2. curl cli: `curl -d '["postionId1", "positionId2"]' -H 'Accept: application/json' -H 'Authorization: Bearer %YOUR_AUTH_TOKEN%' -H 'Content-Type: application/json' -X PUT https://b2bapi.onliner.by/pricelist/renew`

curl php:
```php
$headers = [
    'Accept: application/json',
    'Content-Type: application/json',
    'Authorization: Bearer %YOUR_AUTH_TOKEN%',
];

$data = json_encode(['positionId1', 'positionId2']);

$ch = curl_init('https://b2bapi.onliner.by/pricelist/renew');
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

$resp  = curl_exec($ch);
if (!$resp) {
    var_dump(curl_error($ch), curl_errno($ch));
} else {
    var_dump($resp);
}
curl_close($ch);
```
В случае возникновения проблем, можно добавлять опцию `curl_setopt($ch, CURLOPT_VERBOSE, true);` и CURL будет выводить отладочную информацию в поток для вывода ошибок.
