### ISSUE TITLE
Отчет импортера

### ISSUE THREAD

**Issue by Kleversoft** [onlinerby/onliner-b2b-api#68]
Здравствуйте! Направьте, где можно прочитать для чего нужен отчет импортера и что он отражает. (GET /importers/stocklists/{stockListId}/status)

**Comment by Olden** [comment]
этот отчет аналогичен отчету по прайсам https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/import/status.md

**Comment by Kleversoft** [comment]
Александр, можете посмотреть по импорту прайса импортера с ID 5b6ad5e326ece2649905a3a2, просит указать цену, вроде все указано...

**Comment by Olden** [comment]
Рекомендованная розничная цена в формате "200.34" с копейками после точки

у вас же: "4550,00"

пожалуйста внимательно читайте документацию

**Comment by Kleversoft** [comment]
Спасибо!

**Comment by Kleversoft** [comment]
И, надеюсь, последний вопрос: поясните, почему в отчете импортера
 /importers/match-reports/5b6b11d3f92ea1c8eb693b32 возвращается пустой массив?

**Comment by sidorovich** [comment]
потому что после вашей выгрузки не произошло ни одного совпадения с ценовыми предложениями от магазинов. чтобы произошло совпадение, магазины в своих прайс-листах должны указывать артикулы. при этом УНП магазина и артикул, должны совпадать с вашими данными.

**Comment by sidorovich** [comment]
посмотрели детально полученную информацию от вас:

1. Вы выгрузили один статус наличия для артикула 11TF1304RU и производителя Miele, Германия. Для данной пары не найдено соответствующего товара, скорее всего название производителя некорректно. 

2. Для успешного сопоставления нужно выгрузить нам список ваших ретейлеров. https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/importers/retailers.md

**Comment by Kleversoft** [comment]
Павел, спасибо! А скажите, по каким именно полям проводится сопоставление?

**Comment by Olden** [comment]
производитель + артикул

**Comment by Kleversoft** [comment]
Спасибо!
