### ISSUE TITLE
Onlinr API для магазина - не обновляется артикул предложения

### ISSUE THREAD

**Issue by Goldkaras** [onlinerby/onliner-b2b-api#70]
отправляю "PATCH"запрос на обновление позиции "https://b2bapi.onliner.by/pricelists" через XML файл, цены обновляются, а артикул нет?

<?xml version="1.0" encoding="UTF-8"?>

-<price-list>

-<items-list>

-<item>

<category>Полотенцесушители</category>

<vendor>Gloss & Reiter</vendor>

<model>Cascade 50x60 [Л.50х60.К6 (1")]</model>

<article>Л. 50х60.К6.G1</article>

<id>1828300</id>

<price>345.77</price>

<currency>BYN</currency>

<comment>. Код товара: 1828300. Скидки при заказе через корзину onliner! Консультация, подбор по параметрам, похожие товары. Преимущество покупки товаров для кухни и ванной в 1 месте. Все виды оплат. Доставка или самовывоз по предзаказу. Более 50 000 товаров.</comment>

<producer>СООО «глосс энд рейтер», РБ, г. Минск, переулок Промышленный 14а</producer>

<importer>СООО «Глосс энд рейтер», РБ, г. Минск</importer>

<serviceCenters>СООО «Глосс энд рейтер», РБ, г. Минск</serviceCenters>

<warranty>12</warranty>

<deliveryTownTime>3</deliveryTownTime>

<deliveryTownPrice>0.00</deliveryTownPrice>

<deliveryCountryTime>4</deliveryCountryTime>

<deliveryCountryPrice>12.00</deliveryCountryPrice>

<productLifeTime>null</productLifeTime>

<isCashless>нет</isCashless>

<isCredit>нет</isCredit>

<stockStatus>null</stockStatus>

</item>

</items-list>

-<settings>

<currency>BYN</currency>

</settings>

</price-list>

**Comment by Goldkaras** [comment]
[http_request_0001 (2).txt](https://github.com/onlinerby/onliner-b2b-api/files/2277655/http_request_0001.2.txt)
пример xml файла (только расширение сменил на txt чтобы сюда закачать)

**Comment by ptrofimov** [comment]
Позиция с ID 1828300 в данный момент отсутствует. Поэтому мы не можем проверить какой там артикул. Она была удалена?

**Comment by Goldkaras** [comment]
Это я отправлял от Client id: 2ad58b76ee53029194a8
предложение это видно на онлайнере
https://catalog.onliner.by/towelrail/glossnreiter/l50x60k61/prices?town=minsk

**Comment by Goldkaras** [comment]
id - товара 881959

а это возвращается описание предложения от Вас
category:Полотенцесушители                    Строка
vendor:Gloss &amp; Reiter                    Строка
model:Cascade 50x60 [Л.50х60.К6 (1")]                    Строка
article:null                    Строка
id:1828300                    Строка
price:345.77                    Строка
currency:BYN                    Строка
comment:. Код товара: 1828300. Скидки при заказе через корзину onliner! Консультация, подбор по параметрам, похожие товары. Преимущество покупки товаров для кухни и ванной в 1 месте. Все виды оплат. Доставка или самовывоз по предзаказу. Более 50 000 товаров.                    Строка
producer:СООО «глосс энд рейтер», РБ, г. Минск, переулок Промышленный 14а                    Строка
importer:СООО «Глосс энд рейтер», РБ, г. Минск                    Строка
serviceCenters:СООО «Глосс энд рейтер», РБ, г. Минск                    Строка
warranty:12                    Строка
deliveryTownTime:3                    Строка
deliveryTownPrice:0.00                    Строка
deliveryCountryTime:4                    Строка
deliveryCountryPrice:12.00                    Строка
productLifeTime:null                    Строка
isCashless:нет                    Строка
isCredit:нет                    Строка
stockStatus:null                    Строка
title =

**Comment by ptrofimov** [comment]
Да, я уже нашел позицию. Артикул проверил, такой есть.

**Comment by Goldkaras** [comment]
он не прописывается в предложении клиента через метод PATCH  "https://b2bapi.onliner.by/pricelists"

**Comment by Goldkaras** [comment]
и поэтому не работает механизм отображения остатков импортера

**Comment by Olden** [comment]
будем разбираться, как что-то станет известно сообщим

**Comment by ptrofimov** [comment]
Артикул не обновляется, потому как позиция вообще не импортируется. Посмотрите отчет об импорте. Там будет ошибка валидации "Наличие: недопустимое значение поля". Это поле является опциональным, однако если оно указано, там должно быть валидное значение.

**Comment by Goldkaras** [comment]
Посмотрел отчёт, ничего не ругается и артикула стали прописываться. Не знаю что вы сделали, но всё равно спасибо :).
