### ISSUE TITLE
Ошибка 404 при получении статуса прайс-листа

### ISSUE THREAD

**Issue by tronicsby** [onlinerby/onliner-b2b-api#72]
https://b2bapi.onliner.by/pricelists/5b7c244ff92ea1a/status

**Comment by sidorovich** [comment]
уточните идентификатор 5b7c244ff92ea1a - по такому идентификатору информации нет, да и выглядит он слишком коротким.

**Comment by tronicsby** [comment]
{"id":"5b7c0df59d29c9516f5fcb12","shopId":1689,"fileName":"price-list2018-08-21.csv","size":57498246,"date":"2018-08-21 16:04:53","status":"STATUS_WAITING","contentType":"csv","statusMessage":null}

**Comment by tronicsby** [comment]
{"id":"5b7c26aadbf3ec926436e572","shopId":1689,"fileName":"price-list2018-08-21.csv","size":57396841,"date":"2018-08-21 17:50:18","status":"STATUS_WAITING","contentType":"csv","statusMessage":null}

**Comment by tronicsby** [comment]
сорри. Понял почему. У меня он обрезался до 15 символов
