### ISSUE TITLE
Добавление товаров

### ISSUE THREAD

**Issue by KyntsevichAndrew** [onlinerby/onliner-b2b-api#74]
Как добавить товар удаленно, посредством вашего API, с помощью ЯП - PHP или 1С, потому что в вашей документации как-то не совсем ясно все описано.

ПРИМЕР на PHP
$cart = array(
    "product" => array(
        "manufacturer" => "Samsung",
        "article" => "NC900",
        "ean13" => "2400000032632",
        "description" => "Samsung NC900 16Gb"
    ),
    "producer" => array(
        "country" => "Канада",
        "factory" => "ООО Кленовый сироп, Монреаль, улица Каштановая 30"
    ),
    "stock" => array(
        "status" => "in_stock",
        "quantity" => 900
    ),
    "recommended_retail_price" => array(
        "amount" => "120.60",
        "currency" => "BYN"
    ),
    "package" => array(
        "width" => "100 мм",
        "length" => "200 мм",
        "height" => "300 мм",
        "weight" => "200 г"
    )
);

$cart = json_encode($cart);

$process = curl_init("https://b2bapi.onliner.by/oauth/token");
curl_setopt($process, CURLOPT_HTTPHEADER, array('Accept: application/json'));
curl_setopt($process, CURLOPT_USERPWD, "c9e78730c8ce0_____:379ebfcde9761058ddd06______");
curl_setopt($process, CURLOPT_POST, 1);
curl_setopt($process, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($process, CURLOPT_POSTFIELDS, array('grant_type' => 'client_credentials'));
$result = curl_exec($process);
curl_close($process);
$result = json_decode($result,true);

$process = curl_init("https://b2bapi.onliner.by/importers/stocklists");
curl_setopt($process, CURLOPT_HTTPHEADER, array('Accept: application/json','Content-Type: application/json','Authorization: Bearer '.$result['access_token']));
curl_setopt($process, CURLOPT_CUSTOMREQUEST, "PUT");
curl_setopt($process, CURLOPT_POST, 1);
curl_setopt($process, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($process, CURLOPT_POSTFIELDS, $cart);
$data_a = curl_exec($process);
curl_close($process);

var_dump($data_a);

Ответ не приходит, поэтому смею предполагать, что я делаю ошибку. И возможно ли загружать не JSON объект, а файл, например, CSV(если да, то покажите пример файла).

**Comment by Olden** [comment]
тут указаны доступные форматы для прайслиста: https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/import/info.md

а тут есть конкретный пример на языке php и с использованием утилиты curl: https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/import/update.md

что такое "ответ не приходит" никому кроме вас не понятно. возможно у вас сетевые проблемы? или еще масса вариантов...

будет конкретный вопрос, дадим конкретный ответ.

**Comment by Olden** [comment]
привел ссылки для прайспозиций магазина, не для импортеров...

**Comment by KyntsevichAndrew** [comment]
Окей, интересует добавление товара, а не прайс листа.
"Ответ не приходит" - это значит что ничего изображенного на скрине не приход
![image](https://user-images.githubusercontent.com/23718246/44664592-5e23a280-aa1c-11e8-8613-da76e03e7df1.png)

**Comment by Olden** [comment]
добавьте опцию
```
curl_setopt($curlhandle, CURLOPT_VERBOSE, true);
```

что выдает ваш var_dump в конце?

**Comment by KyntsevichAndrew** [comment]
ничего

**Comment by Olden** [comment]
curl_setopt($process, CURLOPT_VERBOSE, true);

а если так?)

**Comment by KyntsevichAndrew** [comment]
![image](https://user-images.githubusercontent.com/23718246/44664815-fa4da980-aa1c-11e8-895a-781fb06d1862.png)

**Comment by Olden** [comment]
а получается ли у вас токен для начала? $result = json_decode($result,true);

вот тут?

**Comment by Olden** [comment]
вы используете ключи для магазина, а не для импортера

**Comment by KyntsevichAndrew** [comment]
Серьезно?
![image](https://user-images.githubusercontent.com/23718246/44665676-2833ed80-aa1f-11e8-85d4-adf4ad9d630a.png)

**Comment by Olden** [comment]
это страница чего простите?

**Comment by KyntsevichAndrew** [comment]
Страница магзина
![image](https://user-images.githubusercontent.com/23718246/44665815-86f96700-aa1f-11e8-8e4f-95aba0bd9105.png)

**Comment by Olden** [comment]
перечитайте пожалуйста мой ответ:
> вы используете ключи для магазина, а не для импортера

и о какой серьезности вы меня спрашиваете?

**Comment by KyntsevichAndrew** [comment]
Где написано для чего это ключи?
Если есть вот этот мелкий шрифт
![image](https://user-images.githubusercontent.com/23718246/44665899-c1fb9a80-aa1f-11e8-86e9-6730b28def20.png)

**Comment by Olden** [comment]
крупный шрифтом вверху страницы: "Настройки операций с прайс-листами"

**Comment by ptrofimov** [comment]
<img width="913" alt="screen shot 2018-08-27 at 17 35 53" src="https://user-images.githubusercontent.com/867178/44665888-bad48c80-aa1f-11e8-984f-7706b5eaebf7.png">

Это документация для импортеров. Вы получали доступ для API импортеров? Вам выдавали Client ID и Secret?

**Comment by KyntsevichAndrew** [comment]
нет, не обращался сюда, обращались в справку, там сказали про добавление товаров вручную или через API.

**Comment by Olden** [comment]
вы для начала разберитесь что и куда вы хотите добавлять.

**Comment by KyntsevichAndrew** [comment]
Я не слепой
![image](https://user-images.githubusercontent.com/23718246/44666118-6087fb80-aa20-11e8-88d5-df49cff040ea.png)
![image](https://user-images.githubusercontent.com/23718246/44666142-6f6eae00-aa20-11e8-982b-45c90a279d71.png)
 Позволяет ИМПОРТ/ЭКСПОРТ товаров

**Comment by ptrofimov** [comment]
Если добавить товары в каталог (чтобы показать предложения и цены вашего магазина на страницах каталога) - это https://github.com/onlinerby/onliner-b2b-api/blob/master/shop.md
API импортера нужно для других целей - для обновления наличия на складах.

**Comment by KyntsevichAndrew** [comment]
Спасибо тебе.
Alexander Katynia
Olden 
А вот ты плохой.

**Comment by Olden** [comment]
у меня пока нет раздвоения личности, но пожалуйста

**Comment by KyntsevichAndrew** [comment]
Не пиши сююда

**Comment by Olden** [comment]
<img width="882" alt="2018-08-27 17 52 48" src="https://user-images.githubusercontent.com/546682/44666906-1acc3280-aa22-11e8-99fb-b004648f9b9f.png">
пусть будет на память

**Comment by KyntsevichAndrew** [comment]
Я себе тоже оставлю, смешной «затуп»
Перечитывайте когда настроения нет)


Отправлено с iPhone
