### ISSUE TITLE
Не уникальная цена 

### ISSUE THREAD

**Issue by Vtc18** [onlinerby/onliner-b2b-api#75]
http://prntscr.com/koocsj
Дублей нет, проверяли
Что может быть ?

**Comment by ptrofimov** [comment]
Для каждого товара, если там несколько позиций, они (позиции) должны быть с разными ценами. Проверьте прайс.

**Comment by Vtc18** [comment]
Проверяли, все как и должно быть 
Какие еще варианты ?

**Comment by ptrofimov** [comment]
Напишите номер магазина.

**Comment by Vtc18** [comment]
16184

**Comment by ptrofimov** [comment]
Сейчас посмотрим.

**Comment by ptrofimov** [comment]
У вас первая ошибка про неверное указанную модель товара. Исправьте название товара или укажите артикул вместо названия.

**Comment by Vtc18** [comment]
Этого товара нет в наличии, его мы удаляем с прайс листа, вопрос в другом, как появился статус не уникальная цена? И как сказали сотрудники вашей компании что это не относиться к этому. https://prnt.sc/koo4lh

**Comment by ptrofimov** [comment]
Уберите просто товары, которых нет в наличии, и все будет ОК. Фильтр уникальности цены распространяется на все ненайденные товары.

**Comment by Vtc18** [comment]
Как я понимаю, значит это из-за того, что товара нет в наличии. А как бы развернулась ситуация, если бы товар был в наличии и это была разные модели, но цена одна и та же ?

**Comment by ptrofimov** [comment]
Для разных моделей можно указывать одну и ту же цену.

**Comment by Vtc18** [comment]
Тогда как понимать, что было написано в ошибке? модели все по факту разные и ай у всех разные ?

**Comment by ptrofimov** [comment]
Понимать так, что не товар не найден и остальные ошибки игнорировать.

**Comment by Vtc18** [comment]
Принял к сведению. Спасибо
