### ISSUE TITLE
Какой Url можно использовать для тестирования API onliner ? 

### ISSUE THREAD

**Issue by imxotepux** [onlinerby/onliner-b2b-api#78]
Хочу потестить сайт онлайнера через Postman

**Comment by sidorovich** [comment]
У нас нет тестового окружения. Выберите непопулярный раздел среди ваших подключенных, непопулярный товар в нем и экспериментируйте. Ценовые предложения появляются в публичном доступе в течении 5-10 минут после загрузки, в вашем личном кабинете будут появляться сразу же.
