### ISSUE TITLE
Пустые ответы от сервера при запросе брендов и товаров

### ISSUE THREAD

**Issue by ka4an4eg** [onlinerby/onliner-b2b-api#79]
Добрый день, выбрал все секции про коспетику, потом по всем выбрал бренды, по брендам выбрал товары. В итоге получил вот такую структуру. 
```
>Array
(
    [638] => Array
        (
            [NAME] => Косметика по уходу за волосами
            [BRANDS] => Array
                (
                    [11872] => Array
                        (
                            [NAME] => ЛН-Косметика
                            [PRODUCTS] => Array
                                (
                                )
                        )
                    [11822] => Array
                        (
                            [NAME] => Фитокосметик
                            [PRODUCTS] => Array
                                (
                                )
                        )
                )
        )
    [642] => Array
        (
            [NAME] => Косметика по уходу за лицом
            [BRANDS] => Array
                (
                )
        )
    [645] => Array
        (
            [NAME] => Косметика по уходу за телом
            [BRANDS] => Array
                (
                )
        )
    [655] => Array
        (
            [NAME] => Декоративная косметика для губ
            [BRANDS] => Array
                (
                )
        )
    [656] => Array
        (
            [NAME] => Декоративная косметика для лица
            [BRANDS] => Array
                (
                    [15112] => Array
                        (
                            [NAME] => Фабрика Театральной Косметики
                            [PRODUCTS] => Array
                                (
                                )
                        )
                )
        )
    [657] => Array
        (
            [NAME] => Декоративная косметика для глаз
            [BRANDS] => Array
                (
                )
        )
    [659] => Array
        (
            [NAME] => Аксессуары для косметики
            [BRANDS] => Array
                (
                )
        )
)
<
```
Она сильно разнится с тем что я скачал в структуре из кабинета. Подскажите, я от сервиса правильные ответы получаю, на вашей стороне такая же структура, или на моей стороне где-то косяк?
И подскажите как быть с брендами и товарами которых нет в Вашей стурктуре?

**Comment by ka4an4eg** [comment]
И подскажите как быть с брендами и товарами которых нет в Вашей стурктуре?

**Comment by ptrofimov** [comment]
Добрый день. Вопрос в том, что названия в структуре каталога не совпадают с названиями в вашей системе?

**Comment by ka4an4eg** [comment]
Про пустые ответы - отбой, нашёл у себя опечатку.
Про бренды и товары которых нет у вас в структуре - есть у нас в системе бренды:
- Essenza&Natura
- Laction
- Graymelin

вот на вскидку выбрал 3 и не нашёл из в Вашей структуре, как их товары добавить на онлайнер не понятно.

**Comment by ptrofimov** [comment]
Если товара нет в каталоге, а вы хотите добавить предложения на эти товары, нужно сделать заявку на добавление товаров в каталог на странице https://b2b.onliner.by/support

**Comment by ka4an4eg** [comment]
Подскажите, вот так вот я могу получить бренда в разделе
`GET /sections/{sectionId}/manufacturers`
А есть запрос чтобы получить все бренды? Хочу получить все одним запросом, чтобы провести сопоставление на своей стороне.

**Comment by ptrofimov** [comment]
Метода, чтобы получить список всех брэндов, нет. Но брэнд - это часть названия товара, которые есть в xml структуре каталога.

**Comment by ka4an4eg** [comment]
Далеко не всегда
```
<vendor name="MIYO">
   <model id="1000728" name="Nailed it! (02 Sazzling Silver)">
    <articles/>
   </model>
   <model id="1000729" name="Nailed it! (03 Glitzy Gold)">
    <articles/>
   </model>
   <model id="1000732" name="Nailed it! (04 Ink)">
    <articles/>
   </model>
```
```
<vendor name="Nano Professional">
   <model id="1370780" name="Angel Gel">
    <articles/>
   </model>
   <model id="1370785" name="Clever Gel">
    <articles/>
   </model>
   <model id="1370814" name="Fresh Herbal">
    <articles/>
   </model>
```
да и как наличие бренда в названии поможет мне сопоставить ваши бренды и наши?
до вопроса сопоставления названий товаров я ещё не дошёл, там будет отдельная история.

**Comment by ptrofimov** [comment]
Давайте еще раз. Берем брэнд из вашего списка Graymelin. Если такого брэнда в каталоге нет (а его действительно нет), то не добавляем такой товар в прайс, пишем заявку в https://b2b.onliner.by/support, и ждем. В структуре каталога, куски которой вы привели выше, в атрибуте name для вендора есть название вендора (произодителя или брэнда). Таким образом, всегда по xml структуре можно понять, какие брэнды есть, а каких нет.

**Comment by ptrofimov** [comment]
Можете подсказать, какую систему учета товаров (CRM-систему и тд) вы используете?

**Comment by ptrofimov** [comment]
Добрый день. Передавать товары можно либо по названию, либо по артикулу. Только два варианта. 
> На сколько мне известно, вы его систематизировали под ваши стандарты и загрузили в каталог.

Насчет этого сейчас уточню.

**Comment by KaterinaKazarchuk** [comment]
Если передавать товар по артикулу, какой должен быть его формат? какой именно артикул у вас ведется? поскольку на один товар может приходиться несколько артикулов

**Comment by ptrofimov** [comment]
Уточнил. Весь ассортимент товаров, который вы присылали, был добавлен в каталог. Но были добавлены те названия, которые дает производитель. Они не обязательно совпадают с вашими.

**Comment by KaterinaKazarchuk** [comment]
Есть ли возможность как-то передать аналогичный перечень товаров к вам в каталог по API, без изменения названия? 
В этом файле не было артикула производителя. Вы его добавляли при загрузке в каталог? если да, может быть вы можете как-то передать его нам?

**Comment by KaterinaKazarchuk** [comment]
При попытке интеграции возникала ещё следующая ошибка "Неверно указан или не указан производитель товара" 
Подскажите, в этом случае вы меняли название бренда при загрузке ассортимента?

**Comment by ptrofimov** [comment]
Актуальные названия товаров и производителей есть в структуре каталога https://content.onliner.by/catalog/structure.xml

**Comment by KaterinaKazarchuk** [comment]
Правильно ли я понимаю, что никаких других вариантов, кроме как вручную менять наши названия товара и производителя, нет?

**Comment by KaterinaKazarchuk** [comment]
И подскажите ещё, что означает ошибка "неактуальная цена"?

**Comment by ptrofimov** [comment]
1. Вы можете использовать артикулы производителя. Если у товара несколько артикулов, они добавляются в каталог. 
2. Вы можете у себя использовать свои названия товаров, а при импорте указывать названия, которые были получены от производителя (структура каталога).

**Comment by ptrofimov** [comment]
> И подскажите ещё, что означает ошибка "неактуальная цена"?

Где вы увидели такую ошибку?

**Comment by KaterinaKazarchuk** [comment]
в отчете об импорте прайс-листа

**Comment by ptrofimov** [comment]
Может "Неуникальная цена"?

**Comment by KaterinaKazarchuk** [comment]
Хорошо. По этому вопросу понятно. 
Подскажите, откуда вы загружали артикул производителя?

**Comment by ptrofimov** [comment]
Источники могут быть разными, может быть сайт производителя, может быть список от импортера. Все актуальные артикулы также есть в структуре каталога.

**Comment by KaterinaKazarchuk** [comment]
Подскажите, мы вам передавали файл, где было 1680 товаров, все ли они попали в каталог?

**Comment by ptrofimov** [comment]
Были добавлены все, которые подошли. Добавлено 1119 из 1687.

**Comment by KaterinaKazarchuk** [comment]
Хорошо, спасибо за ответы.

**Comment by KaterinaKazarchuk** [comment]
Добрый день. 
Подскажите с каким ключем нам передавать штрих код днк, который был ранее добавлен вами?

**Comment by ka4an4eg** [comment]
Добрый день, Екатерина передала что Вы на своей стороне сделали полу для шорт кодов товаров из 1с ДНК, подскажите в каком теге мне передавать эти коды в фид?

**Comment by ptrofimov** [comment]
Добрый день. Можете передавать его как артикул.

**Comment by ka4an4eg** [comment]
ок, спасибо

**Comment by ptrofimov** [comment]
С вами свяжется сотрудник отдела продаж.

**Comment by ka4an4eg** [comment]
добрый день, подскажите, есть ли возможность выгрузить отчёт по прайс листу. Ваши коллеги просят названия со штрихкодами невыгруженных товаров, а у меня тут 38 страниц отчёта.

**Comment by KaterinaKazarchuk** [comment]
Добрый день, высылаем файл с названием и шк товаров, по которым не прошла выгрузка. 
http://dnk.test1.newsite.by/1c_exchange/onliner_report.php?report_id=5bed8add9d29c959db68ba62

**Comment by ptrofimov** [comment]
401 Authorization Required

**Comment by KaterinaKazarchuk** [comment]
Попробуйте через этот путь https://dnk.by/1c_exchange/onliner_report.php?report_id=5bed8add9d29c959db68ba62

**Comment by ptrofimov** [comment]
Да, теперь открывается.

**Comment by KaterinaKazarchuk** [comment]
Добрый день. Попробовали запустить обмен. Ниже прикрепляю отчет с товарами по которым не прошел обмен https://dnk.by/1c_exchange/onliner_report.php?report_id=5bf3fa30d535cf2630263b92

**Comment by ptrofimov** [comment]
Добрый день. Отправил в каталог.
