### ISSUE TITLE
Условия получения доступа к вашему API

### ISSUE THREAD

**Issue by DeNoir** [onlinerby/onliner-b2b-api#80]
Доброго дня.
Хотелось бы выяснить следующее: каковы условия получения доступа к вашему API?
API дается только на ту категорию товаров, где мы размещаемся или есть возможность получать интересующие нас данные и из других категорий, но уже на иных условиях?

**Comment by sidorovich** [comment]
какие именно данные вас интересуют? файл со структурой каталога и цены конкурентов доступны независимо от подключенных разделов.

**Comment by DeNoir** [comment]
Интересуют характеристики товаров для фильтров, картинки без watermark, артикул поставщика.
Цены конкурентов не интересуют пока.
К примеру: мы размещаемся у вас в категориях мониторы и мобильные телефоны, но планируем начать работать с комплектующими, пока без размещения в вашем каталоге. Указанные выше данные на комплектующие мы тоже хотим забрать. Что именно нужно от нас для получения этих данных?

**Comment by sidorovich** [comment]
"характеристики товаров для фильтров, картинки без watermark" не нужны для размещения ваших ценовых предложений, боюсь что данная информация в публичном API недоступна. Можете обратиться в отдел по работе с клиентами. 

"артикул поставщика" есть в файле со структурой каталога.

Наше публичное API в большинстве своем реализовано для получения данных от магазинов, а не для передачи от нас к магазинам.
