### ISSUE TITLE
Конкурирующие цены

### ISSUE THREAD

**Issue by a1serheyuk** [onlinerby/onliner-b2b-api#81]
Приветствую. 
Посоветовали написать сюда. 
У нас постоянно сбивается цена и наличие по некоторым товарам. Это вызывает подозрение, что приходят от нас 2 разных выгрузки по АПИ. Есть ли возможность увидеть айпи адреса этих выгрузок или каким-либо образом зафиксировать откуда приходят эти прайсы? Любая информация, которая поможет нашим специалистам найти это несоответствие. 

Речь идет про магазин 1675

**Comment by ptrofimov** [comment]
Добрый день. Вы подозреваете, что кто-то без вашего ведома обновляет цены через API?

**Comment by a1serheyuk** [comment]
Не думаю :) 
Скорее всего, при переезде с сервера на сервер что-то дублировалось или не выключилось. Специалисты по сайту и по 1С бьются над поиском проблемы уже несколько дней. Пытаюсь помочь им с коммуникацией. Может быть с Вашей стороны можно попробовать увидеть откуда ноги растут.

**Comment by ptrofimov** [comment]
Зайдите на вкладку Импорт/Экспорт в админке B2B. Удалите приложение onliner-b2b-api и создайте заново. Вы получите новые ключи, которые можете использовать на новом месте. Старые ключи станут недействительными и старое приложение не сможет отправлять данные. 

Плюс не забывайте, что цены могут обновляться еще кроме админки и API еще и по расписанию, если включена Автоматическая обработка и указан Адрес для скачивания прайс-листа.

**Comment by a1serheyuk** [comment]
Благодарю, попробуем!

**Comment by a1serheyuk** [comment]
Спасибо большое, проблема решилась с помощью Вашей подсказки. Правда, ее причина так и не была найдена, но это уже не срочно. 

Хорошего дня!

**Comment by ptrofimov** [comment]
Отлично. Вам тоже хорошего дня.
