### ISSUE TITLE
Неверно указана или не указана модель товара

### ISSUE THREAD

**Issue by Vtc18** [onlinerby/onliner-b2b-api#85]
Xiaomi Mi Air Purifier 2S
http://prntscr.com/len8jt
Все заполнено, что может быть ?

**Comment by sidorovich** [comment]
Ошибочно в название товара указан производитель.  В данный момент проблема выглдяит вот так:
<img width="1035" alt="2018-11-05 18 21 27" src="https://user-images.githubusercontent.com/3040359/48006984-aef3fd80-e127-11e8-9cc3-dd4e37f81263.png">

Операторы каталога обещали исправить в кратчайшие сроки. Все будет приведено к виду как у Вас на скриншоте.

**Comment by Vtc18** [comment]
Спасибо
