### ISSUE TITLE
Виснет отправка запроса и не передается прайс

### ISSUE THREAD

**Issue by Mamom1993** [onlinerby/onliner-b2b-api#87]
магазин 6352
onliner-b2b-api
id client 4946e32ed6a8f5f59c91

Хронология работы по апи:
скрипт старт - 10.12.2018 16:30
отправка запроса - 10.12.2018 16:30
отправка файла - 10.12.2018 16:35
конец скрипта - 10.12.2018 16:35

В чем может быть причина задержки между отправкой запроса и файла? 

После окончания работы скрипта прайс с сайта на онлайнер не отправляется.
Ошибок в работе скрипта нет.

Последний раз прайс был выгружен 2018-11-23 в 12:15:03

**Comment by ptrofimov** [comment]
Добрый день. А файл большой?

**Comment by Mamom1993** [comment]
немного скорректирую данные
1. около 300 позиций
2. как данные отправили — так и конец. при работе с апи идет зависание запроса и ничего не отправляется по факту.
3. данные отправляются по апи, не файлом.
4. узнать нет возможности, запрос не отправляется и ничего не возвращается.

**Comment by ptrofimov** [comment]
300 позиций это небольшой объем данных, передаваться долго он не может. и запрос в апи отправляется разом, нет отправки запроса и данных отдельно. код возврата можно получить.

Отправьте запрос на урл https://postb.in/TkPrAb3W вместо b2b.api или покажите код.

**Comment by Mamom1993** [comment]
код запроса:
$process = curl_init("https://b2bapi.onliner.by/oauth/token");
curl_setopt($process, CURLOPT_HTTPHEADER, array('Accept: application/json'));
curl_setopt($process, CURLOPT_USERPWD, "3bb65b98c86e54b1af7e:c8a93ea01c9bbb740a2e75607553f74589b8b6ef");
curl_setopt($process, CURLOPT_POST, 1);
curl_setopt($process, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($process, CURLOPT_POSTFIELDS, array('grant_type' => 'client_credentials'));
$result = curl_exec($process);
var_dump($result);
$result = json_decode($result, true);
$access_token = $result["access_token"];
curl_close($process);

отправили и ничего не поменялось, запрос зависает.

**Comment by Mamom1993** [comment]
отредактировал id и secret

**Comment by ptrofimov** [comment]
На вид все норм. Отправьте запрос на https://postb.in/YXhuEy4h

**Comment by ptrofimov** [comment]
Ваш код запустил, все работает без задержек.

**Comment by ptrofimov** [comment]
И добавьте опции чтобы ограничить время ожидания ответа
```
curl_setopt($process, CURLOPT_TIMEOUT, 30);
curl_setopt($process, CURLOPT_CONNECTTIMEOUT, 30);
```

**Comment by ptrofimov** [comment]
И выполните ping b2bapi.onliner.by и пришлите вывод команды.

**Comment by Mamom1993** [comment]
> И выполните ping b2bapi.onliner.by и пришлите вывод команды.
команда ping закрыта, так как сеть закрытая. 
вот весь пинг:
[root@shop ~]# ping b2bapi.onliner.by
PING b2bapi.onliner.by (178.124.129.12) 56(84) bytes of data.

> Отправьте запрос на https://postb.in/YXhuEy4h
добавили, запрос не завис. вернул false http://joxi.ru/EA4o1w8cwBDRB2

**Comment by ptrofimov** [comment]
false потому что урл уже удалился автоматически по времени. отправьте на новый https://postb.in/KSjvwuf2

**Comment by Mamom1993** [comment]
отправили. false вернуло

**Comment by ptrofimov** [comment]
В истории запросов нет ни одного POST https://postb.in/b/KSjvwuf2
Запрос явно не отправляется.
Добавьте строку 
```
var_dump(curl_getinfo($process));
```
перед curl_close
и напишите сюда вывод.

**Comment by ptrofimov** [comment]
Судя по тому, что http_code = 0, это host not found.

Сделайте var_dump(curl_error($process)); после curl_exec. И включите отображение всех ошибок через error_reporting(E_ALL) и ini_set('display_errors',1). Там могут быть warnings по этой теме.

**Comment by Mamom1993** [comment]
http://joxi.ru/KAxLXQPtMgqb8A
эти предупреждения отображаются на любой адрес.

**Comment by ptrofimov** [comment]
Понятно, а таймаут видимо как раз 5 минут. Если на любой адрес, то это проблемы с сетью в целом, а не с b2b.api.

**Comment by Mamom1993** [comment]
спасибо. сетевики исправили проблему с доступом. сейчас все отрабатывает сразу же.

**Comment by ptrofimov** [comment]
Отлично.
