### ISSUE TITLE
не проходит авторизация, пишет нет параметра в запросе

### ISSUE THREAD

**Issue by Rassvetniy** [onlinerby/onliner-b2b-api#89]
вот тело запроса - client_id=f2adf966963fde******&client_secret=********b67e3e357763303dd1073d33aa3bf990&grant_type=client_credentials
возвзращет сообщение - {"error":"invalid_request","error_description":"The grant type was not specified in the request"}

**Comment by sidorovich** [comment]
Поле grant_type должно передаваться в теле POST-запроса, а не как GET-параметр. Внимательнее смотрите документацию - https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/oauth20.md

**Comment by Rassvetniy** [comment]
токен получил, но при проверке метода shop возвзращает 405 код вот пример токена 6ef4c2d847407c3e34e9567466e8ac42c1a806ef, пробовал и get параметром и в заголовках

**Comment by sidorovich** [comment]
https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_HTTP#405

Если речь про https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/shop/info.md то проверьте, что стучитесь с помощью HTTP-метода GET. В авторизации был POST, для /shop нужен GET

**Comment by Rassvetniy** [comment]
да не досмотрел вместо get post запрос передавал, сейчас метод shop работает

**Comment by sidorovich** [comment]
если все хорошо, закройте этот тикет кнопочкой close внизу. спасибо!
