### ISSUE TITLE
Не работает обновление магазина

### ISSUE THREAD

**Issue by julia-korotkina** [onlinerby/onliner-b2b-api#90]
Добрый день.
Не работает обновление позиций магазина.
Используя методы PUT  /pricelist/renew и  PUT  /pricelist/all/renew в ответе приходит массив объектов с id товаров и временем обновления - то есть выглядит будто всё работает верно. Однако на самом деле в каталоге обновления не происходит. Мы поставили обновление по расписанию раз в час и каждый раз скрипт срабатывает успешно (без ошибок, приходит массив с обновлениями). Однако сегодня в каталоге было указано, что последнее обновление было вчера. В связи с этим вариант задержки обновления мы исключили.

**Comment by julia-korotkina** [comment]
Мы сейчас подключили опцию "Склад" и там важно обновлять информацию каждый день, поэтому сегодня я уже сделала обновление просто по "Сделать прайс-лист актуальным".
Но у меня остался скрин с сегодняшним товаром, который должен был быть обновлен, но не был, могу прислать, если это поможет выявить проблему.
Или я могу завтра не обновлять магазин вручную, и тогда предоставлю вам информацию по тем позициям, которые не обновились.

**Comment by ptrofimov** [comment]
Напишите ID магазина.

**Comment by julia-korotkina** [comment]
987

**Comment by julia-korotkina** [comment]
Хм, хорошо, поставим обновление раз в день в полночь и тогда завтра проверим.

**Comment by julia-korotkina** [comment]
Добрый день.
Обновление магазина через методы происходит, но спустя минут 10, ок.
Появился ещё один вопрос, может вы сможете подсказать в чём проблема.
Обновление позиций магазина, а также загрузка прайс-листов успешно проходит только при запуске скрипта с локального сервера.
При запуске скриптов с удалённого сервера приходит код успешного завершения скрипта, но до вас информация не доходит (обновление позиций не происходит, в "Список закачанных в систему файлов" прайс лист не добавляется). Может вы знаете, в чём может быть проблема?

**Comment by ptrofimov** [comment]
Добрый день.
1. Задержка в 5-10 минут - это нормально.
2. Значит с удаленного сервера запрос не отправляется. Надо уточнить HTTP код ответа, он должен быть равен 202. И надо выполнить на том сервере ping b2bapi.onliner.by (пришлите вывод команды), чтобы удостовериться, что наш сервер доступен.

**Comment by julia-korotkina** [comment]
Добрый день. Результат выполнения команды

telnet b2bapi.onliner.by 443
Trying 178.124.129.14...
telnet: connect to address 178.124.129.14: No route to host
Trying 178.124.129.12...
telnet: connect to address 178.124.129.12: No route to host
Trying 178.124.129.16...
telnet: connect to address 178.124.129.16: No route to host

bash-4.1$ ping b2bapi.onliner.by -c13
PING b2bapi.onliner.by (178.124.129.14) 56(84) bytes of data.
From 178.124.132.16 icmp_seq=1 Destination Host Unreachable
From 178.124.132.16 icmp_seq=3 Destination Host Unreachable
From 178.124.132.16 icmp_seq=4 Destination Host Unreachable
From 178.124.132.16 icmp_seq=5 Destination Host Unreachable
From 178.124.132.16 icmp_seq=6 Destination Host Unreachable
From 178.124.132.16 icmp_seq=7 Destination Host Unreachable
From 178.124.132.16 icmp_seq=8 Destination Host Unreachable
From 178.124.132.16 icmp_seq=10 Destination Host Unreachable
From 178.124.132.16 icmp_seq=11 Destination Host Unreachable
From 178.124.132.16 icmp_seq=12 Destination Host Unreachable
From 178.124.132.16 icmp_seq=13 Destination Host Unreachable

--- b2bapi.onliner.by ping statistics ---
13 packets transmitted, 0 received, +11 errors, 100% packet loss, time 22005ms

**Comment by sidorovich** [comment]
Скорее всего проблемы на стороне вашего провайдера - обратитесь к нему. 

На всякий случай скажите Ваш IP-адрес, с которого вы пытаетесь получить доступ. Мы проверим, чтобы он случайно не попал в список заблокированных адресов.

**Comment by julia-korotkina** [comment]
1) Вот информация по ip, с которого я пинговала:

2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:25:90:fc:fa:08 brd ff:ff:ff:ff:ff:ff
    inet 93.125.99.66/24 brd 93.125.99.255 scope global eth0
    inet6 fe80::225:90ff:fefc:fa08/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 00:25:90:fc:fa:09 brd ff:ff:ff:ff:ff:ff

2) При проверке доступности вашего сервера через https://ping-admin.ru/free_test/  говорится, что указанный адрес (https://b2b.onliner.by) не доступен со всего мира. Это же и ответила тех поддержка провайдера.

**Comment by sidorovich** [comment]
Наш сайт закрыт для доступа через TOR-сети, а также для большинства китайских IP-адресов.

Данный IP-адрес (93.125.99.66) не находится в списке заблокированных и вполне пингуется с нашей стороны. Наши администраторы порекомендовали выполнить `traceroute b2bapi.onliner.by`

**Comment by julia-korotkina** [comment]
bash не распознаёт команду 
![image](https://user-images.githubusercontent.com/17277224/53009545-d65ba580-344c-11e9-8970-de82f1329db1.png)

**Comment by julia-korotkina** [comment]
Это hoster.by, по идее не попадает в ваши исключения

**Comment by sidorovich** [comment]
Обращайтесь в поддержку хостера. Кажется у хостера были подобные проблемы с другими нашими клиентами, когда сервера находились в одном датацентре, но в разных подсетях.
Вот наш вывод:
```
sp@event0:~$ traceroute 93.125.99.66
traceroute to 93.125.99.66 (93.125.99.66), 30 hops max, 60 byte packets
 1  core-10g.datacenter.by (178.124.129.1)  0.257 ms  0.250 ms  0.226 ms
 2  vh84.hosterby.com (93.125.99.66)  0.160 ms !X  0.137 ms !X  0.118 ms !X
```

**Comment by julia-korotkina** [comment]
Ответ тех поддержки хостера:
Работу b2bapi.onliner.by мы проверяем не только через сервера, которые располагаются в датацентре. Пинг с наших локальных компьютеров также не проходит.

https://check-host.net/check-ping?host=178.124.129.16

Сервер не доступен нигде.

**Comment by sidorovich** [comment]
Странно. Около 1000 магазинов каждый день выгружают нам свои прайс, а сайт недоступен нигде. Мы по прежнему ожидаем вывод команды traceroute.

**Comment by sidorovich** [comment]
Системные администраторы подсказывают делать команду со следующим набором параметров `traceroute -T -p 443 b2bapi.onliner.by`.

**Comment by julia-korotkina** [comment]
Обратились к другому провайдеру - всё заработало. Спасибо за консультацию!
