### ISSUE TITLE
не пропускает выгрузку через api из за размера файла

### ISSUE THREAD

**Issue by storik88** [onlinerby/onliner-b2b-api#91]
можно ли увеличить с вашей стороны размер принимаемой выгрузки по api?

**Comment by sidorovich** [comment]
в ближайшее время мы не планируем пересматривать данные ограничения, используйте методы API для частичного обновления данных:

https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/import/update.md
