### ISSUE TITLE
415 ответ в методе PUTCH

### ISSUE THREAD

**Issue by Rassvetniy** [onlinerby/onliner-b2b-api#92]
Добрый день. По каким причинам может быть 415 ответ при загрузке прайса, предполагаю что что то не так с хмл я прикрепляю такой:
<?xml version="1.0" encoding="UTF-8"?>
<price-list version="1.0">
	<settings>
		<currency>BYN</currency>
	</settings>
	<items-list>
		<item>
			<category>Электросамокаты и электроскутеры</category>
			<vendor>Kugoo</vendor>
			<model>S2 36V (черный)</model>
			<article/>
			<id>1</id>
			<price>459.00</price>
			<currency>BYN</currency>
			<comment/>
			<producer/>
			<importer/>
			<serviceCenters/>
			<warranty/>
			<deliveryTownTime/>
			<deliveryTownPrice/>
			<deliveryCountryTime/>
			<deliveryCountryPrice/>
			<productLifeTime/>
			<isCashless/>
			<isCredit>нет</isCredit>
			<stockStatus>in_stock</stockStatus>
		</item>
	</items-list>
</price-list>

**Comment by Rassvetniy** [comment]
адрес запроса /pricelists?access_token="+токен
заголовки -  "Accept"  "text/xml"

**Comment by ptrofimov** [comment]
Попробуйте application/xml
А какой Content-Type указываете?

**Comment by ptrofimov** [comment]
Хотя стоямба!!! Если вы отправляете xml то нужно указывать xml в content-type а не в accept. Accept - это тот формат который вы хотите получить в ответ, content-type - тот который вы отправляете. сделайте такие заголовки
Accept: application/json
Content-Type: application/json

**Comment by Rassvetniy** [comment]
да все верно счас запрос идет в обработку но в обработке ошибка, насколько понял поля <producer>,<importer>,<serviceCenters> обязательны для заполнения? в репорте пишет что MUST_NOT_BE_BLANK также вопрос что значит поле isCashless?

**Comment by ptrofimov** [comment]
producer,importer,serviceCenters - обязательны
isCashless - безналичный расчет (для юрлиц)

**Comment by Rassvetniy** [comment]
в общем я разобрался импорт работает, а если эти поля producer,importer,serviceCenters оставлять пустыми строками или например "___" в эти поля записывать загрузит или нет?

**Comment by ptrofimov** [comment]
технически пройдет валидацию, но эта информация показывается пользователям, и символы подчеркивания вместо настоящих данных - это нарушение законодательства, и магазин может быть заблокирован

**Comment by ptrofimov** [comment]
Напишите номер магазина

**Comment by Rassvetniy** [comment]
понял просто в БД сейчас этих данных про импортеру, производителю нет, 16650 вроде номер

**Comment by ptrofimov** [comment]
Нужно их найти

**Comment by Rassvetniy** [comment]
все ясно тему можно закрывать, а что то не видно где кнопка закрыть тему
