### ISSUE TITLE
Обновление прайса на 10 минут убирает показ товара магазина на площадке

### ISSUE THREAD

**Issue by alesiasl** [onlinerby/onliner-b2b-api#94]
Магазин №6498 «Ньютон» (Ньютон)
столкнулись с проблемой, при обновлении прайса все товары пропадают с продажи на 10 минут
каким образом можно обновлять прайс, т.е. все 100% товаров имеют изменения в цене или наличии, чтоб не отсутствовать по 10 минут в предложениях товара от нашего магазина

**Comment by sidorovich** [comment]
Если вы используете метод PUT, то вы очищаете весь прайс-лист, а затем загружаете изменения. Механизм кэширования ценовых предложений работает в 10 минутном интервале. Используйте метод PATCH в API для частичного изменения ценовых предложений по группам товаров. В большинстве случаев это поможет обновлять цены бесшовно.

https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/import/update.md

**Comment by alesiasl** [comment]
подскажите метод который вы предлагаете использовать подходит для полного обновления прайса свыше 60 000 товаров? мы обновляем каждый час цены на все товары.

**Comment by sidorovich** [comment]
мы предлагаем обновлять не 60к позиций раз в час, а обновлять частями по 10к каждые 10 минут. как логически разбить прайс-лист, чтобы получилось равномерно, придется решать вам.
а так же предлагаем отправлять изменения только в том случае, если произошли изменения.
