### ISSUE TITLE
Обновление цены и состояния на складе

### ISSUE THREAD

**Issue by zherelevich** [onlinerby/onliner-b2b-api#95]
Здравствуйте! Есть способ обновить цену и склад по id предложения?

**Comment by sidorovich** [comment]
На данный момент такой возможности нет, но в далекой перспективе планируется сделать такую возможность.

**Comment by zherelevich** [comment]
> На данный момент такой возможности нет, но в далекой перспективе планируется сделать такую возможность.
Можете описать наиболее оптимальный вариант как это сделать сейчас.

**Comment by sidorovich** [comment]
Обновление всех ценовых предложений в рамках группы товаров: https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/import/update.md
