### ISSUE TITLE
после обновления прайса часть или весь товар не выставляется на площадке

### ISSUE THREAD

**Issue by alesiasl** [onlinerby/onliner-b2b-api#96]
Магазин №6498 «Ньютон» (Ньютон) - после обновления прайса часть или весь товар не выставляется на площадке, есть ошибки импорта прайса
проблема наблюдается со вчерашнего дня
выставляем тариф весь каталог и такие простои достаточно критично сказываются
просьба дать развернутый ответ в чем причина (и если причина на нашей стороне, чтоб программист смог из ответа понять что именно нужно исправить).

Спасибо.

**Comment by sidorovich** [comment]
В курсе данной проблемы. Занимаемся, сложность в том, что проявляется довольно редко. В случае возникновения проблемы попробуйте повторить импорт через какое-то время (20-30 минут).

**Comment by sidorovich** [comment]
Выкатили вероятное решение. Рассчитываем, что проблема не должна повторяться. Можете попробовать обновить прайс.
