### ISSUE TITLE
Ошибка импорта

### ISSUE THREAD

**Issue by storik88** [onlinerby/onliner-b2b-api#99]
добрый день, №6498 «Ньютон» (Ньютон)
сегодня заметил, что один из прайсов загружаемых в админку выдаёт ошибку. 
пишет "Не удалось импортировать файл. Невалидный csv. 
В прайсе не должно быть колонок без названия"
сам прайс смотрели, с ним всё в порядке

**Comment by sidorovich** [comment]
Да, есть проблема. Если открыть ваш прайс лист как текстовый файл, то в конце первой строки можно увидеть ; и наш парсер считает, что после нее есть еще одна значащая колонка с пустым названием. А колонки с пустым названием в именованном прайс-листе недопустимы. Будем исправлять в ближайшее время. Пока что контролируйте первую строку и удаляйте лишний символ ; в первой строке.

**Comment by storik88** [comment]
проблема пока что актуальна

**Comment by ShadowsXXX** [comment]
День добрый
магазин 14447 проблема по импорту файла обновления

**Comment by sidorovich** [comment]
аналогичная?

**Comment by ShadowsXXX** [comment]
Можно получить шаблон файла импорта в csv формате, если таковой менялся
--
Отправлено из Mail.Ru для Android понедельник, 01 июля 2019г., 10:53 +03:00 от Pavel Sidorovich  notifications@github.com :

**Comment by sidorovich** [comment]
можете сделать экспорт прайс-листа из личного кабинета B2B

**Comment by ShadowsXXX** [comment]
Сейчас попробую, отпишусь
--
Отправлено из Mail.Ru для Android понедельник, 01 июля 2019г., 11:25 +03:00 от Pavel Sidorovich  notifications@github.com :

**Comment by ShadowsXXX** [comment]
Неверно указана или не указана модель товара,
ID позиции может содержать только цифры и строчные буквы латинского алфавита
выдает на некоторые позиции, но проблема в том что конкретного ID в прайсе не присвоено, там пустые ячейки везде

**Comment by SashaArtis** [comment]
Добрый день!
Магазин №14034
при импорте для всех товаров выдает ошибки http://joxi.ru/brRLRoES74RPN2
подскажите, как решить проблему?

**Comment by Olden** [comment]
@SashaArtis решить проблему можно заполнив поля "производитель" и "модель" правильными(существующими у нас) данными

**Comment by SashaArtis** [comment]
где можно посмотреть список ваших данных? 
а также что значит ошибка http://joxi.ru/E2pVwxWh78pldr Неуникальная цена

**Comment by Olden** [comment]
по поводу производителей и моделей ответ тут:
https://github.com/onlinerby/onliner-b2b-api/issues/60#issuecomment-400745162

неуникальность цены можно почитать тут:
https://github.com/onlinerby/onliner-b2b-api/issues/79#issuecomment-431029194

**Comment by SashaArtis** [comment]
Добрый день!

для некоторых товаров задали названия согласно вашему xml файлу http://joxi.ru/82Q74Nzhw6q4Wr 

произвели импорт, названия товаров полностью совпадают с названием в onliner - но данные товары все равно не сопоставились 

http://joxi.ru/12MQxN0ulnx1y2 - почему даже после передачи точного названия как на onliner модель считается ошибочной?

**Comment by kamadoss** [comment]
@SashaArtis согласно нашему xml файлу товар, который вы пытаетесь загрузить, называется "Контурный (тон 1)", а не "Карандаш Relouis Контурный (тон 1)"

**Comment by SashaArtis** [comment]
Добрый день!
Подскажите, можно ли синхронизацию импорта настроить по штрихкоду? Без сопоставления названия товаров на нашем сайте и в вашей выгрузке?

**Comment by kamadoss** [comment]
@SashaArtis импортировать по штрихкоду возможности нету, но можно импортировать по связке производитель + артикул товара в случае, когда у товара есть артикул. Эта информация указана в нашей xml структуре каталога

**Comment by SashaArtis** [comment]
Уточните, в вашем файле используются номера артикулов согласно заводским артикулам производителей?

**Comment by kamadoss** [comment]
@SashaArtis да, в файле указаны артикулы производителя

**Comment by SashaArtis** [comment]
есть ли у вас значение штрихкодов для товаров?
можно ли получить выгрузку артикулов и штрихкодов?

проблема в том, что у нас более трех тысяч товаров, необходимо решение по автоматической синхронизации данных.

**Comment by Olden** [comment]
в файле структуры каталога есть артикулы для тех товаров для которых есть. вы можете использовать эту информацию для синхронизации. штрихкодов нет.
